#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2024, Azure Magic Modules Generator
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Auto-generated by Azure Magic Modules — do not edit manually

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: azure_rm_appconfiguration
version_added: "0.1.0"
short_description: Manage Azure App Configuration Store instances.
description:
    - Create, update, or delete an Azure AppConfiguration.
    - This module was auto-generated by Azure Magic Modules.
options:
    resource_group:
        description:
            - Name of the resource group.
        type: str
        required: true
    name:
        description:
            - Name of the appconfiguration.
        type: str
        required: true
    location:
        description:
            - Valid Azure location. Defaults to the location of the resource group.
        type: str
    sku_name:
        description:
            - SKU name of the App Configuration store.
        type: str
        choices:
            - "Free"
            - "Standard"
    disable_local_auth:
        description:
            - Whether local authentication is disabled.
        type: bool
    enable_purge_protection:
        description:
            - Whether purge protection is enabled.
        type: bool
    soft_delete_retention_in_days:
        description:
            - Soft delete retention period in days.
        type: int
    public_network_access:
        description:
            - Whether public network access is allowed.
        type: str
        choices:
            - "Enabled"
            - "Disabled"
    encryption_key_vault_key_identifier:
        description:
            - Key Vault key identifier for encryption.
        type: str
    identity_type:
        description:
            - Type of managed identity.
        type: str
        choices:
            - "SystemAssigned"
            - "UserAssigned"
            - "None"
    state:
        description:
            - Assert the state of the appconfiguration.
            - Use C(present) to create or update and C(absent) to delete.
        type: str
        default: present
        choices:
            - present
            - absent
extends_documentation_fragment:
    - azure.azcollection.azure
    - azure.azcollection.azure_tags
author:
    - "Azure Magic Modules Generator (@azure-magic-modules)"
seealso:
    - description: Azure AppConfiguration REST API
      link: https://learn.microsoft.com/en-us/azure/azure-app-configuration/overview
'''

EXAMPLES = r'''
- name: Create AppConfiguration
  azure_rm_appconfiguration:
    resource_group: myResourceGroup
    name: myAppConfiguration
    location: eastus
    state: present

- name: Delete AppConfiguration
  azure_rm_appconfiguration:
    resource_group: myResourceGroup
    name: myAppConfiguration
    state: absent
'''

RETURN = r'''
state:
    description: Current state of the appconfiguration.
    returned: always
    type: dict
    contains:
        id:
            description: Resource ID.
            type: str
        name:
            description: Resource name.
            type: str
        location:
            description: Resource location.
            type: str
        tags:
            description: Resource tags.
            type: dict
        sku_name:
            description: SKU name of the App Configuration store.
            type: str
        disable_local_auth:
            description: Whether local authentication is disabled.
            type: bool
        enable_purge_protection:
            description: Whether purge protection is enabled.
            type: bool
        soft_delete_retention_in_days:
            description: Soft delete retention period in days.
            type: int
        public_network_access:
            description: Whether public network access is allowed.
            type: str
        encryption_key_vault_key_identifier:
            description: Key Vault key identifier for encryption.
            type: str
        identity_type:
            description: Type of managed identity.
            type: str
'''

import json
from ansible_collections.azure.azcollection.plugins.module_utils.azure_rm_common import AzureRMModuleBase


class AzureRMAppConfiguration(AzureRMModuleBase):

    def __init__(self):
        self.module_arg_spec = dict(
            resource_group=dict(type='str', required=True, aliases=['resource_group_name']),
            name=dict(type='str', required=True),
            location=dict(type='str'),
            sku_name=dict(
                type='str',
                choices=['Free', 'Standard'],
            ),
            disable_local_auth=dict(
                type='bool',
            ),
            enable_purge_protection=dict(
                type='bool',
            ),
            soft_delete_retention_in_days=dict(
                type='int',
            ),
            public_network_access=dict(
                type='str',
                choices=['Enabled', 'Disabled'],
            ),
            encryption_key_vault_key_identifier=dict(
                type='str',
            ),
            identity_type=dict(
                type='str',
                choices=['SystemAssigned', 'UserAssigned', 'None'],
            ),
            state=dict(type='str', default='present', choices=['present', 'absent']),
        )

        self.resource_group = None
        self.name = None
        self.location = None
        self.sku_name = None
        self.disable_local_auth = None
        self.enable_purge_protection = None
        self.soft_delete_retention_in_days = None
        self.public_network_access = None
        self.encryption_key_vault_key_identifier = None
        self.identity_type = None
        self.state = None
        self.tags = None

        self.results = dict(changed=False, state=dict())

        required_if = [
            ('state', 'present', ['resource_group', 'name']),
        ]

        super().__init__(
            derived_arg_spec=self.module_arg_spec,
            supports_check_mode=True,
            supports_tags=True,
            required_if=required_if,
        )

    def exec_module(self, **kwargs):
        for key in list(self.module_arg_spec.keys()) + ['tags']:
            setattr(self, key, kwargs[key])

        resource_group = self.resource_group
        name = self.name

        # Get existing resource
        response = self.get_resource()

        if self.state == 'present':
            if not self.location:
                rg = self.get_resource_group(resource_group)
                self.location = rg.location

            # Build the resource body from parameters
            body = self.build_body()

            if response:
                # Check if update needed
                update_tags, new_tags = self.update_tags(response.get('tags'))
                if update_tags:
                    body['tags'] = new_tags
                    self.results['changed'] = True

                if self.check_update(response, body):
                    self.results['changed'] = True

                if self.results['changed']:
                    if not self.check_mode:
                        response = self.create_or_update(resource_group, name, body)
                else:
                    response = response
            else:
                if self.tags:
                    body['tags'] = self.tags
                if not self.check_mode:
                    response = self.create_or_update(resource_group, name, body)
                self.results['changed'] = True

        elif self.state == 'absent':
            if response:
                if not self.check_mode:
                    self.delete_resource(resource_group, name)
                self.results['changed'] = True

        if response:
            self.results['state'] = self.format_response(response)

        return self.results

    def build_body(self):
        body = dict(
            location=self.location,
        )
        if self.sku_name is not None:
            _target = body
            _target = _target.setdefault('sku', {})
            _target['name'] = self.sku_name
        if self.disable_local_auth is not None:
            body['disableLocalAuth'] = self.disable_local_auth
        if self.enable_purge_protection is not None:
            body['enablePurgeProtection'] = self.enable_purge_protection
        if self.soft_delete_retention_in_days is not None:
            body['softDeleteRetentionInDays'] = self.soft_delete_retention_in_days
        if self.public_network_access is not None:
            body['publicNetworkAccess'] = self.public_network_access
        if self.encryption_key_vault_key_identifier is not None:
            _target = body
            _target = _target.setdefault('encryption', {})
            _target = _target.setdefault('keyVaultProperties', {})
            _target['keyIdentifier'] = self.encryption_key_vault_key_identifier
        if self.identity_type is not None:
            _target = body
            _target = _target.setdefault('identity', {})
            _target['type'] = self.identity_type

        if self.tags:
            body['tags'] = self.tags

        return body

    def check_update(self, existing, desired):
        """Compare existing resource with desired state."""
        # Check sku_name
        if self.sku_name is not None:
            _existing = existing
            _existing = _existing.get('sku', {}) if isinstance(_existing, dict) else {}
            if _existing.get('name') != self.sku_name:
                return True
        # Check disable_local_auth
        if self.disable_local_auth is not None:
            if existing.get('disableLocalAuth') != self.disable_local_auth:
                return True
        # Check enable_purge_protection
        if self.enable_purge_protection is not None:
            if existing.get('enablePurgeProtection') != self.enable_purge_protection:
                return True
        # Check soft_delete_retention_in_days
        if self.soft_delete_retention_in_days is not None:
            if existing.get('softDeleteRetentionInDays') != self.soft_delete_retention_in_days:
                return True
        # Check public_network_access
        if self.public_network_access is not None:
            if existing.get('publicNetworkAccess') != self.public_network_access:
                return True
        # Check encryption_key_vault_key_identifier
        if self.encryption_key_vault_key_identifier is not None:
            _existing = existing
            _existing = _existing.get('encryption', {}) if isinstance(_existing, dict) else {}
            _existing = _existing.get('keyVaultProperties', {}) if isinstance(_existing, dict) else {}
            if _existing.get('keyIdentifier') != self.encryption_key_vault_key_identifier:
                return True
        # Check identity_type
        if self.identity_type is not None:
            _existing = existing
            _existing = _existing.get('identity', {}) if isinstance(_existing, dict) else {}
            if _existing.get('type') != self.identity_type:
                return True

        return False

    def get_resource(self):
        try:
            url = self.get_resource_url()
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2023-03-01'},
                None, None, [200], 0, 0,
            )
            return self.deserialize_response(response)
        except Exception:
            return None

    def create_or_update(self, resource_group, name, body):
        url = self.get_resource_url()
        response = self.mgmt_client.query(
            url, "PUT",
            {'api-version': '2023-03-01'},
            None, body, [200, 201], 0, 0,
        )
        return self.deserialize_response(response)

    def delete_resource(self, resource_group, name):
        url = self.get_resource_url()
        self.mgmt_client.query(
            url, "DELETE",
            {'api-version': '2023-03-01'},
            None, None, [200, 202, 204], 0, 0,
        )

    def get_resource_url(self):
        return (
            '/subscriptions/{subscription_id}'
            '/resourceGroups/{resource_group}'
            '/providers/Microsoft.AppConfiguration/configurationStores/{name}'
        ).format(
            subscription_id=self.subscription_id,
            resource_group=self.resource_group,
            name=self.name,
        )

    def format_response(self, response):
        result = dict(
            id=response.get('id'),
            name=response.get('name'),
            location=response.get('location'),
            tags=response.get('tags'),
        )
        _body = response
        _body = _body.get('sku', {}) if isinstance(_body, dict) else {}
        result['sku_name'] = _body.get('name')
        result['disable_local_auth'] = response.get('disableLocalAuth')
        result['enable_purge_protection'] = response.get('enablePurgeProtection')
        result['soft_delete_retention_in_days'] = response.get('softDeleteRetentionInDays')
        result['public_network_access'] = response.get('publicNetworkAccess')
        _body = response
        _body = _body.get('encryption', {}) if isinstance(_body, dict) else {}
        _body = _body.get('keyVaultProperties', {}) if isinstance(_body, dict) else {}
        result['encryption_key_vault_key_identifier'] = _body.get('keyIdentifier')
        _body = response
        _body = _body.get('identity', {}) if isinstance(_body, dict) else {}
        result['identity_type'] = _body.get('type')
        return result

    @staticmethod
    def deserialize_response(response):
        try:
            return json.loads(response.text)
        except (ValueError, AttributeError):
            return None


def main():
    AzureRMAppConfiguration()


if __name__ == '__main__':
    main()
