#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2024, Azure Magic Modules Generator
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Auto-generated by Azure Magic Modules — do not edit manually

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: azure_rm_maintenanceconfiguration
version_added: "0.1.0"
short_description: Manage Azure Maintenance Configuration instances.
description:
    - Create, update, or delete an Azure MaintenanceConfiguration.
    - This module was auto-generated by Azure Magic Modules.
options:
    resource_group:
        description:
            - Name of the resource group.
        type: str
        required: true
    name:
        description:
            - Name of the maintenanceconfiguration.
        type: str
        required: true
    location:
        description:
            - Valid Azure location. Defaults to the location of the resource group.
        type: str
    maintenance_scope:
        description:
            - Scope of the maintenance configuration.
        type: str
        choices:
            - "Host"
            - "OSImage"
            - "Extension"
            - "InGuestPatch"
            - "SQLDB"
            - "SQLManagedInstance"
            - "Resource"
    visibility:
        description:
            - Visibility of the maintenance configuration.
        type: str
        choices:
            - "Custom"
            - "Public"
    start_date_time:
        description:
            - Start date and time for the maintenance window.
        type: str
    expiration_date_time:
        description:
            - Expiration date and time for the maintenance window.
        type: str
    duration:
        description:
            - Duration of the maintenance window.
        type: str
    time_zone:
        description:
            - Time zone for the maintenance window.
        type: str
    recur_every:
        description:
            - Recurrence pattern for the maintenance window.
        type: str
    state:
        description:
            - Assert the state of the maintenanceconfiguration.
            - Use C(present) to create or update and C(absent) to delete.
        type: str
        default: present
        choices:
            - present
            - absent
extends_documentation_fragment:
    - azure.azcollection.azure
    - azure.azcollection.azure_tags
author:
    - "Azure Magic Modules Generator (@azure-magic-modules)"
seealso:
    - description: Azure MaintenanceConfiguration REST API
      link: https://learn.microsoft.com/en-us/azure/virtual-machines/maintenance-configurations
'''

EXAMPLES = r'''
- name: Create MaintenanceConfiguration
  azure_rm_maintenanceconfiguration:
    resource_group: myResourceGroup
    name: myMaintenanceConfiguration
    location: eastus
    state: present

- name: Delete MaintenanceConfiguration
  azure_rm_maintenanceconfiguration:
    resource_group: myResourceGroup
    name: myMaintenanceConfiguration
    state: absent
'''

RETURN = r'''
state:
    description: Current state of the maintenanceconfiguration.
    returned: always
    type: dict
    contains:
        id:
            description: Resource ID.
            type: str
        name:
            description: Resource name.
            type: str
        location:
            description: Resource location.
            type: str
        tags:
            description: Resource tags.
            type: dict
        maintenance_scope:
            description: Scope of the maintenance configuration.
            type: str
        visibility:
            description: Visibility of the maintenance configuration.
            type: str
        start_date_time:
            description: Start date and time for the maintenance window.
            type: str
        expiration_date_time:
            description: Expiration date and time for the maintenance window.
            type: str
        duration:
            description: Duration of the maintenance window.
            type: str
        time_zone:
            description: Time zone for the maintenance window.
            type: str
        recur_every:
            description: Recurrence pattern for the maintenance window.
            type: str
'''

import json
from ansible_collections.azure.azcollection.plugins.module_utils.azure_rm_common import AzureRMModuleBase


class AzureRMMaintenanceConfiguration(AzureRMModuleBase):

    def __init__(self):
        self.module_arg_spec = dict(
            resource_group=dict(type='str', required=True, aliases=['resource_group_name']),
            name=dict(type='str', required=True),
            location=dict(type='str'),
            maintenance_scope=dict(
                type='str',
                choices=['Host', 'OSImage', 'Extension', 'InGuestPatch', 'SQLDB', 'SQLManagedInstance', 'Resource'],
            ),
            visibility=dict(
                type='str',
                choices=['Custom', 'Public'],
            ),
            start_date_time=dict(
                type='str',
            ),
            expiration_date_time=dict(
                type='str',
            ),
            duration=dict(
                type='str',
            ),
            time_zone=dict(
                type='str',
            ),
            recur_every=dict(
                type='str',
            ),
            state=dict(type='str', default='present', choices=['present', 'absent']),
        )

        self.resource_group = None
        self.name = None
        self.location = None
        self.maintenance_scope = None
        self.visibility = None
        self.start_date_time = None
        self.expiration_date_time = None
        self.duration = None
        self.time_zone = None
        self.recur_every = None
        self.state = None
        self.tags = None

        self.results = dict(changed=False, state=dict())

        required_if = [
            ('state', 'present', ['resource_group', 'name']),
        ]

        super().__init__(
            derived_arg_spec=self.module_arg_spec,
            supports_check_mode=True,
            supports_tags=True,
            required_if=required_if,
        )

    def exec_module(self, **kwargs):
        for key in list(self.module_arg_spec.keys()) + ['tags']:
            setattr(self, key, kwargs[key])

        resource_group = self.resource_group
        name = self.name

        # Get existing resource
        response = self.get_resource()

        if self.state == 'present':
            if not self.location:
                rg = self.get_resource_group(resource_group)
                self.location = rg.location

            # Build the resource body from parameters
            body = self.build_body()

            if response:
                # Check if update needed
                update_tags, new_tags = self.update_tags(response.get('tags'))
                if update_tags:
                    body['tags'] = new_tags
                    self.results['changed'] = True

                if self.check_update(response, body):
                    self.results['changed'] = True

                if self.results['changed']:
                    if not self.check_mode:
                        response = self.create_or_update(resource_group, name, body)
                else:
                    response = response
            else:
                if self.tags:
                    body['tags'] = self.tags
                if not self.check_mode:
                    response = self.create_or_update(resource_group, name, body)
                self.results['changed'] = True

        elif self.state == 'absent':
            if response:
                if not self.check_mode:
                    self.delete_resource(resource_group, name)
                self.results['changed'] = True

        if response:
            self.results['state'] = self.format_response(response)

        return self.results

    def build_body(self):
        body = dict(
            location=self.location,
        )
        if self.maintenance_scope is not None:
            body['maintenanceScope'] = self.maintenance_scope
        if self.visibility is not None:
            body['visibility'] = self.visibility
        if self.start_date_time is not None:
            _target = body
            _target = _target.setdefault('maintenanceWindow', {})
            _target['startDateTime'] = self.start_date_time
        if self.expiration_date_time is not None:
            _target = body
            _target = _target.setdefault('maintenanceWindow', {})
            _target['expirationDateTime'] = self.expiration_date_time
        if self.duration is not None:
            _target = body
            _target = _target.setdefault('maintenanceWindow', {})
            _target['duration'] = self.duration
        if self.time_zone is not None:
            _target = body
            _target = _target.setdefault('maintenanceWindow', {})
            _target['timeZone'] = self.time_zone
        if self.recur_every is not None:
            _target = body
            _target = _target.setdefault('maintenanceWindow', {})
            _target['recurEvery'] = self.recur_every

        if self.tags:
            body['tags'] = self.tags

        return body

    def check_update(self, existing, desired):
        """Compare existing resource with desired state."""
        # Check maintenance_scope
        if self.maintenance_scope is not None:
            if existing.get('maintenanceScope') != self.maintenance_scope:
                return True
        # Check visibility
        if self.visibility is not None:
            if existing.get('visibility') != self.visibility:
                return True
        # Check start_date_time
        if self.start_date_time is not None:
            _existing = existing
            _existing = _existing.get('maintenanceWindow', {}) if isinstance(_existing, dict) else {}
            if _existing.get('startDateTime') != self.start_date_time:
                return True
        # Check expiration_date_time
        if self.expiration_date_time is not None:
            _existing = existing
            _existing = _existing.get('maintenanceWindow', {}) if isinstance(_existing, dict) else {}
            if _existing.get('expirationDateTime') != self.expiration_date_time:
                return True
        # Check duration
        if self.duration is not None:
            _existing = existing
            _existing = _existing.get('maintenanceWindow', {}) if isinstance(_existing, dict) else {}
            if _existing.get('duration') != self.duration:
                return True
        # Check time_zone
        if self.time_zone is not None:
            _existing = existing
            _existing = _existing.get('maintenanceWindow', {}) if isinstance(_existing, dict) else {}
            if _existing.get('timeZone') != self.time_zone:
                return True
        # Check recur_every
        if self.recur_every is not None:
            _existing = existing
            _existing = _existing.get('maintenanceWindow', {}) if isinstance(_existing, dict) else {}
            if _existing.get('recurEvery') != self.recur_every:
                return True

        return False

    def get_resource(self):
        try:
            url = self.get_resource_url()
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2023-10-01-preview'},
                None, None, [200], 0, 0,
            )
            return self.deserialize_response(response)
        except Exception:
            return None

    def create_or_update(self, resource_group, name, body):
        url = self.get_resource_url()
        response = self.mgmt_client.query(
            url, "PUT",
            {'api-version': '2023-10-01-preview'},
            None, body, [200, 201], 0, 0,
        )
        return self.deserialize_response(response)

    def delete_resource(self, resource_group, name):
        url = self.get_resource_url()
        self.mgmt_client.query(
            url, "DELETE",
            {'api-version': '2023-10-01-preview'},
            None, None, [200, 202, 204], 0, 0,
        )

    def get_resource_url(self):
        return (
            '/subscriptions/{subscription_id}'
            '/resourceGroups/{resource_group}'
            '/providers/Microsoft.Maintenance/maintenanceConfigurations/{name}'
        ).format(
            subscription_id=self.subscription_id,
            resource_group=self.resource_group,
            name=self.name,
        )

    def format_response(self, response):
        result = dict(
            id=response.get('id'),
            name=response.get('name'),
            location=response.get('location'),
            tags=response.get('tags'),
        )
        result['maintenance_scope'] = response.get('maintenanceScope')
        result['visibility'] = response.get('visibility')
        _body = response
        _body = _body.get('maintenanceWindow', {}) if isinstance(_body, dict) else {}
        result['start_date_time'] = _body.get('startDateTime')
        _body = response
        _body = _body.get('maintenanceWindow', {}) if isinstance(_body, dict) else {}
        result['expiration_date_time'] = _body.get('expirationDateTime')
        _body = response
        _body = _body.get('maintenanceWindow', {}) if isinstance(_body, dict) else {}
        result['duration'] = _body.get('duration')
        _body = response
        _body = _body.get('maintenanceWindow', {}) if isinstance(_body, dict) else {}
        result['time_zone'] = _body.get('timeZone')
        _body = response
        _body = _body.get('maintenanceWindow', {}) if isinstance(_body, dict) else {}
        result['recur_every'] = _body.get('recurEvery')
        return result

    @staticmethod
    def deserialize_response(response):
        try:
            return json.loads(response.text)
        except (ValueError, AttributeError):
            return None


def main():
    AzureRMMaintenanceConfiguration()


if __name__ == '__main__':
    main()
