#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2024, Azure Magic Modules Generator
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Auto-generated by Azure Magic Modules — do not edit manually

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: azure_rm_functionapp_info
version_added: "0.1.0"
short_description: Get facts for Azure FunctionApp
description:
    - Get facts for a specific FunctionApp or list all FunctionApps in a resource group.
    - This module was auto-generated by Azure Magic Modules.
options:
    resource_group:
        description:
            - Name of the resource group.
        type: str
        required: true
    name:
        description:
            - Name of the functionapp.
            - If not specified, all functionapps in the resource group will be listed.
        type: str
extends_documentation_fragment:
    - azure.azcollection.azure
    - azure.azcollection.azure_tags
author:
    - "Azure Magic Modules Generator (@azure-magic-modules)"
seealso:
    - description: Azure FunctionApp REST API
      link: https://learn.microsoft.com/en-us/azure/azure-functions/functions-overview
'''

EXAMPLES = r'''
- name: Get facts for a specific FunctionApp
  azure_rm_functionapp_info:
    resource_group: myResourceGroup
    name: myFunctionApp

- name: List all FunctionApps in a resource group
  azure_rm_functionapp_info:
    resource_group: myResourceGroup
'''

RETURN = r'''
functionapps:
    description:
        - List of functionapp dicts.
    returned: always
    type: list
    elements: dict
    contains:
        id:
            description: Resource ID.
            type: str
        name:
            description: Resource name.
            type: str
        location:
            description: Resource location.
            type: str
        tags:
            description: Resource tags.
            type: dict
        server_farm_id:
            description: Resource ID of the App Service Plan.
            type: str
        kind:
            description: Kind of the Function App.
            type: str
        storage_account_name:
            description: Name of the storage account for the Function App.
            type: str
        storage_account_access_key:
            description: Access key for the storage account.
            type: str
        runtime_stack:
            description: Runtime stack for the Function App.
            type: str
        runtime_version:
            description: Runtime version for the Function App.
            type: str
        functions_extension_version:
            description: Functions runtime extension version.
            type: str
        https_only:
            description: Whether the Function App only accepts HTTPS traffic.
            type: bool
'''

import json
from ansible_collections.azure.azcollection.plugins.module_utils.azure_rm_common import AzureRMModuleBase


class AzureRMFunctionAppInfo(AzureRMModuleBase):

    def __init__(self):
        self.module_arg_spec = dict(
            resource_group=dict(type='str', required=True, aliases=['resource_group_name']),
            name=dict(type='str'),
        )

        self.resource_group = None
        self.name = None
        self.tags = None

        self.results = dict(
            changed=False,
            functionapps=[],
        )

        super().__init__(
            derived_arg_spec=self.module_arg_spec,
            supports_check_mode=True,
            supports_tags=False,
            facts_module=True,
        )

    def exec_module(self, **kwargs):
        for key in list(self.module_arg_spec.keys()) + ['tags']:
            setattr(self, key, kwargs[key])

        result_key = 'functionapps'

        if self.name:
            response = self.get_resource()
            if response:
                if self.has_tags(response.get('tags'), self.tags):
                    self.results[result_key] = [self.format_response(response)]
        else:
            responses = self.list_by_resource_group()
            for item in responses:
                if self.has_tags(item.get('tags'), self.tags):
                    self.results[result_key].append(self.format_response(item))

        return self.results

    def get_resource(self):
        try:
            url = (
                '/subscriptions/{subscription_id}'
                '/resourceGroups/{resource_group}'
                '/providers/Microsoft.Web/sites/{name}'
            ).format(
                subscription_id=self.subscription_id,
                resource_group=self.resource_group,
                name=self.name,
            )
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2023-12-01'},
                None, None, [200], 0, 0,
            )
            return self.deserialize_response(response)
        except Exception:
            return None

    def list_by_resource_group(self):
        try:
            url = (
                '/subscriptions/{subscription_id}'
                '/resourceGroups/{resource_group}'
                '/providers/Microsoft.Web/sites'
            ).format(
                subscription_id=self.subscription_id,
                resource_group=self.resource_group,
            )
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2023-12-01'},
                None, None, [200], 0, 0,
            )
            result = self.deserialize_response(response)
            if result and isinstance(result, dict):
                return result.get('value', [])
            return []
        except Exception:
            return []

    def format_response(self, response):
        result = dict(
            id=response.get('id'),
            name=response.get('name'),
            location=response.get('location'),
            tags=response.get('tags'),
        )
        result['server_farm_id'] = response.get('serverFarmId')
        result['kind'] = response.get('kind')
        _body = response
        _body = _body.get('siteConfig', {}) if isinstance(_body, dict) else {}
        _body = _body.get('appSettings', {}) if isinstance(_body, dict) else {}
        result['storage_account_name'] = _body.get('AzureWebJobsStorage')
        _body = response
        _body = _body.get('siteConfig', {}) if isinstance(_body, dict) else {}
        _body = _body.get('appSettings', {}) if isinstance(_body, dict) else {}
        result['storage_account_access_key'] = _body.get('AzureWebJobsStorageKey')
        _body = response
        _body = _body.get('siteConfig', {}) if isinstance(_body, dict) else {}
        _body = _body.get('appSettings', {}) if isinstance(_body, dict) else {}
        result['runtime_stack'] = _body.get('FUNCTIONS_WORKER_RUNTIME')
        _body = response
        _body = _body.get('siteConfig', {}) if isinstance(_body, dict) else {}
        result['runtime_version'] = _body.get('linuxFxVersion')
        _body = response
        _body = _body.get('siteConfig', {}) if isinstance(_body, dict) else {}
        _body = _body.get('appSettings', {}) if isinstance(_body, dict) else {}
        result['functions_extension_version'] = _body.get('FUNCTIONS_EXTENSION_VERSION')
        result['https_only'] = response.get('httpsOnly')
        return result

    @staticmethod
    def deserialize_response(response):
        try:
            return json.loads(response.text)
        except (ValueError, AttributeError):
            return None


def main():
    AzureRMFunctionAppInfo()


if __name__ == '__main__':
    main()
