#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2024, Azure Magic Modules Generator
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Auto-generated by Azure Magic Modules — do not edit manually

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: azure_rm_loganalyticsworkspace
version_added: "0.1.0"
short_description: Manage Azure Log Analytics workspaces.
description:
    - Create, update, or delete an Azure LogAnalyticsWorkspace.
    - This module was auto-generated by Azure Magic Modules.
options:
    resource_group:
        description:
            - Name of the resource group.
        type: str
        required: true
    name:
        description:
            - Name of the loganalyticsworkspace.
        type: str
        required: true
    location:
        description:
            - Valid Azure location. Defaults to the location of the resource group.
        type: str
    sku_name:
        description:
            - The SKU of the workspace.
        type: str
        choices:
            - "PerGB2018"
            - "Free"
            - "Standalone"
            - "PerNode"
            - "Standard"
            - "Premium"
            - "CapacityReservation"
    retention_in_days:
        description:
            - Workspace data retention in days.
        type: int
        default: "30"
    daily_quota_gb:
        description:
            - Daily volume cap in GB. Use -1 for unlimited.
        type: float
    internet_ingestion_enabled:
        description:
            - Whether ingestion from the public internet is enabled.
        type: bool
        default: "True"
    internet_query_enabled:
        description:
            - Whether queries from the public internet are enabled.
        type: bool
        default: "True"
    state:
        description:
            - Assert the state of the loganalyticsworkspace.
            - Use C(present) to create or update and C(absent) to delete.
        type: str
        default: present
        choices:
            - present
            - absent
extends_documentation_fragment:
    - azure.azcollection.azure
    - azure.azcollection.azure_tags
author:
    - "Azure Magic Modules Generator (@azure-magic-modules)"
seealso:
    - description: Azure LogAnalyticsWorkspace REST API
      link: https://learn.microsoft.com/en-us/azure/azure-monitor/logs/log-analytics-workspace-overview
'''

EXAMPLES = r'''
- name: Create LogAnalyticsWorkspace
  azure_rm_loganalyticsworkspace:
    resource_group: myResourceGroup
    name: myLogAnalyticsWorkspace
    location: eastus
    state: present

- name: Delete LogAnalyticsWorkspace
  azure_rm_loganalyticsworkspace:
    resource_group: myResourceGroup
    name: myLogAnalyticsWorkspace
    state: absent
'''

RETURN = r'''
state:
    description: Current state of the loganalyticsworkspace.
    returned: always
    type: dict
    contains:
        id:
            description: Resource ID.
            type: str
        name:
            description: Resource name.
            type: str
        location:
            description: Resource location.
            type: str
        tags:
            description: Resource tags.
            type: dict
        sku_name:
            description: The SKU of the workspace.
            type: str
        retention_in_days:
            description: Workspace data retention in days.
            type: int
        daily_quota_gb:
            description: Daily volume cap in GB. Use -1 for unlimited.
            type: float
        internet_ingestion_enabled:
            description: Whether ingestion from the public internet is enabled.
            type: bool
        internet_query_enabled:
            description: Whether queries from the public internet are enabled.
            type: bool
'''

import json
from ansible_collections.azure.azcollection.plugins.module_utils.azure_rm_common import AzureRMModuleBase


class AzureRMLogAnalyticsWorkspace(AzureRMModuleBase):

    def __init__(self):
        self.module_arg_spec = dict(
            resource_group=dict(type='str', required=True, aliases=['resource_group_name']),
            name=dict(type='str', required=True),
            location=dict(type='str'),
            sku_name=dict(
                type='str',
                choices=['PerGB2018', 'Free', 'Standalone', 'PerNode', 'Standard', 'Premium', 'CapacityReservation'],
            ),
            retention_in_days=dict(
                type='int',
                default=30,
            ),
            daily_quota_gb=dict(
                type='float',
            ),
            internet_ingestion_enabled=dict(
                type='bool',
                default=True,
            ),
            internet_query_enabled=dict(
                type='bool',
                default=True,
            ),
            state=dict(type='str', default='present', choices=['present', 'absent']),
        )

        self.resource_group = None
        self.name = None
        self.location = None
        self.sku_name = None
        self.retention_in_days = None
        self.daily_quota_gb = None
        self.internet_ingestion_enabled = None
        self.internet_query_enabled = None
        self.state = None
        self.tags = None

        self.results = dict(changed=False, state=dict())

        required_if = [
            ('state', 'present', ['resource_group', 'name']),
        ]

        super().__init__(
            derived_arg_spec=self.module_arg_spec,
            supports_check_mode=True,
            supports_tags=True,
            required_if=required_if,
        )

    def exec_module(self, **kwargs):
        for key in list(self.module_arg_spec.keys()) + ['tags']:
            setattr(self, key, kwargs[key])

        resource_group = self.resource_group
        name = self.name

        # Get existing resource
        response = self.get_resource()

        if self.state == 'present':
            if not self.location:
                rg = self.get_resource_group(resource_group)
                self.location = rg.location

            # Build the resource body from parameters
            body = self.build_body()

            if response:
                # Check if update needed
                update_tags, new_tags = self.update_tags(response.get('tags'))
                if update_tags:
                    body['tags'] = new_tags
                    self.results['changed'] = True

                if self.check_update(response, body):
                    self.results['changed'] = True

                if self.results['changed']:
                    if not self.check_mode:
                        response = self.create_or_update(resource_group, name, body)
                else:
                    response = response
            else:
                if self.tags:
                    body['tags'] = self.tags
                if not self.check_mode:
                    response = self.create_or_update(resource_group, name, body)
                self.results['changed'] = True

        elif self.state == 'absent':
            if response:
                if not self.check_mode:
                    self.delete_resource(resource_group, name)
                self.results['changed'] = True

        if response:
            self.results['state'] = self.format_response(response)

        return self.results

    def build_body(self):
        body = dict(
            location=self.location,
        )

        properties = body.setdefault('properties', {})
        if self.sku_name is not None:
            _target = properties
            _target = _target.setdefault('sku', {})
            _target['name'] = self.sku_name
        if self.retention_in_days is not None:
            properties['retentionInDays'] = self.retention_in_days
        if self.daily_quota_gb is not None:
            _target = properties
            _target = _target.setdefault('workspaceCapping', {})
            _target['dailyQuotaGb'] = self.daily_quota_gb
        if self.internet_ingestion_enabled is not None:
            properties['publicNetworkAccessForIngestion'] = self.internet_ingestion_enabled
        if self.internet_query_enabled is not None:
            properties['publicNetworkAccessForQuery'] = self.internet_query_enabled

        if self.tags:
            body['tags'] = self.tags

        return body

    def check_update(self, existing, desired):
        """Compare existing resource with desired state."""
        # Check sku_name
        if self.sku_name is not None:
            _existing = existing.get('properties', {})
            _existing = _existing.get('sku', {}) if isinstance(_existing, dict) else {}
            if _existing.get('name') != self.sku_name:
                return True
        # Check retention_in_days
        if self.retention_in_days is not None:
            if existing.get('properties', {}).get('retentionInDays') != self.retention_in_days:
                return True
        # Check daily_quota_gb
        if self.daily_quota_gb is not None:
            _existing = existing.get('properties', {})
            _existing = _existing.get('workspaceCapping', {}) if isinstance(_existing, dict) else {}
            if _existing.get('dailyQuotaGb') != self.daily_quota_gb:
                return True
        # Check internet_ingestion_enabled
        if self.internet_ingestion_enabled is not None:
            if existing.get('properties', {}).get('publicNetworkAccessForIngestion') != self.internet_ingestion_enabled:
                return True
        # Check internet_query_enabled
        if self.internet_query_enabled is not None:
            if existing.get('properties', {}).get('publicNetworkAccessForQuery') != self.internet_query_enabled:
                return True

        return False

    def get_resource(self):
        try:
            url = self.get_resource_url()
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2023-09-01'},
                None, None, [200], 0, 0,
            )
            return self.deserialize_response(response)
        except Exception:
            return None

    def create_or_update(self, resource_group, name, body):
        url = self.get_resource_url()
        response = self.mgmt_client.query(
            url, "PUT",
            {'api-version': '2023-09-01'},
            None, body, [200, 201], 0, 0,
        )
        return self.deserialize_response(response)

    def delete_resource(self, resource_group, name):
        url = self.get_resource_url()
        self.mgmt_client.query(
            url, "DELETE",
            {'api-version': '2023-09-01'},
            None, None, [200, 202, 204], 0, 0,
        )

    def get_resource_url(self):
        return (
            '/subscriptions/{subscription_id}'
            '/resourceGroups/{resource_group}'
            '/providers/Microsoft.OperationalInsights/workspaces/{name}'
        ).format(
            subscription_id=self.subscription_id,
            resource_group=self.resource_group,
            name=self.name,
        )

    def format_response(self, response):
        result = dict(
            id=response.get('id'),
            name=response.get('name'),
            location=response.get('location'),
            tags=response.get('tags'),
        )
        _props = response.get('properties', {})
        _props = _props.get('sku', {}) if isinstance(_props, dict) else {}
        result['sku_name'] = _props.get('name')
        result['retention_in_days'] = response.get('properties', {}).get('retentionInDays')
        _props = response.get('properties', {})
        _props = _props.get('workspaceCapping', {}) if isinstance(_props, dict) else {}
        result['daily_quota_gb'] = _props.get('dailyQuotaGb')
        result['internet_ingestion_enabled'] = response.get('properties', {}).get('publicNetworkAccessForIngestion')
        result['internet_query_enabled'] = response.get('properties', {}).get('publicNetworkAccessForQuery')
        return result

    @staticmethod
    def deserialize_response(response):
        try:
            return json.loads(response.text)
        except (ValueError, AttributeError):
            return None


def main():
    AzureRMLogAnalyticsWorkspace()


if __name__ == '__main__':
    main()
