#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2024, Azure Magic Modules Generator
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Auto-generated by Azure Magic Modules — do not edit manually

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: azure_rm_virtualnetworkgateway
version_added: "0.1.0"
short_description: Manage Azure virtual network gateways.
description:
    - Create, update, or delete an Azure VirtualNetworkGateway.
    - This module was auto-generated by Azure Magic Modules.
options:
    resource_group:
        description:
            - Name of the resource group.
        type: str
        required: true
    name:
        description:
            - Name of the virtualnetworkgateway.
        type: str
        required: true
    location:
        description:
            - Valid Azure location. Defaults to the location of the resource group.
        type: str
    gateway_type:
        description:
            - Type of the virtual network gateway.
        type: str
        choices:
            - "Vpn"
            - "ExpressRoute"
    vpn_type:
        description:
            - VPN type of the gateway.
        type: str
        choices:
            - "RouteBased"
            - "PolicyBased"
    sku_name:
        description:
            - SKU name of the virtual network gateway.
        type: str
        choices:
            - "Basic"
            - "VpnGw1"
            - "VpnGw2"
            - "VpnGw3"
            - "VpnGw4"
            - "VpnGw5"
            - "VpnGw1AZ"
            - "VpnGw2AZ"
            - "VpnGw3AZ"
            - "VpnGw4AZ"
            - "VpnGw5AZ"
            - "ErGw1AZ"
            - "ErGw2AZ"
            - "ErGw3AZ"
    enable_bgp:
        description:
            - Enable BGP on the gateway.
        type: bool
    ip_configuration_subnet_id:
        description:
            - Resource ID of the gateway subnet.
        type: str
    ip_configuration_public_ip_id:
        description:
            - Resource ID of the public IP for the gateway.
        type: str
    state:
        description:
            - Assert the state of the virtualnetworkgateway.
            - Use C(present) to create or update and C(absent) to delete.
        type: str
        default: present
        choices:
            - present
            - absent
extends_documentation_fragment:
    - azure.azcollection.azure
    - azure.azcollection.azure_tags
author:
    - "Azure Magic Modules Generator (@azure-magic-modules)"
seealso:
    - description: Azure VirtualNetworkGateway REST API
      link: https://learn.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-about-vpngateways
'''

EXAMPLES = r'''
- name: Create VirtualNetworkGateway
  azure_rm_virtualnetworkgateway:
    resource_group: myResourceGroup
    name: myVirtualNetworkGateway
    location: eastus
    state: present

- name: Delete VirtualNetworkGateway
  azure_rm_virtualnetworkgateway:
    resource_group: myResourceGroup
    name: myVirtualNetworkGateway
    state: absent
'''

RETURN = r'''
state:
    description: Current state of the virtualnetworkgateway.
    returned: always
    type: dict
    contains:
        id:
            description: Resource ID.
            type: str
        name:
            description: Resource name.
            type: str
        location:
            description: Resource location.
            type: str
        tags:
            description: Resource tags.
            type: dict
        gateway_type:
            description: Type of the virtual network gateway.
            type: str
        vpn_type:
            description: VPN type of the gateway.
            type: str
        sku_name:
            description: SKU name of the virtual network gateway.
            type: str
        enable_bgp:
            description: Enable BGP on the gateway.
            type: bool
        ip_configuration_subnet_id:
            description: Resource ID of the gateway subnet.
            type: str
        ip_configuration_public_ip_id:
            description: Resource ID of the public IP for the gateway.
            type: str
'''

import json
from ansible_collections.azure.azcollection.plugins.module_utils.azure_rm_common import AzureRMModuleBase


class AzureRMVirtualNetworkGateway(AzureRMModuleBase):

    def __init__(self):
        self.module_arg_spec = dict(
            resource_group=dict(type='str', required=True, aliases=['resource_group_name']),
            name=dict(type='str', required=True),
            location=dict(type='str'),
            gateway_type=dict(
                type='str',
                choices=['Vpn', 'ExpressRoute'],
            ),
            vpn_type=dict(
                type='str',
                choices=['RouteBased', 'PolicyBased'],
            ),
            sku_name=dict(
                type='str',
                choices=[
                    'Basic',
                    'VpnGw1',
                    'VpnGw2',
                    'VpnGw3',
                    'VpnGw4',
                    'VpnGw5',
                    'VpnGw1AZ',
                    'VpnGw2AZ',
                    'VpnGw3AZ',
                    'VpnGw4AZ',
                    'VpnGw5AZ',
                    'ErGw1AZ',
                    'ErGw2AZ',
                    'ErGw3AZ',
                ],
            ),
            enable_bgp=dict(
                type='bool',
            ),
            ip_configuration_subnet_id=dict(
                type='str',
            ),
            ip_configuration_public_ip_id=dict(
                type='str',
            ),
            state=dict(type='str', default='present', choices=['present', 'absent']),
        )

        self.resource_group = None
        self.name = None
        self.location = None
        self.gateway_type = None
        self.vpn_type = None
        self.sku_name = None
        self.enable_bgp = None
        self.ip_configuration_subnet_id = None
        self.ip_configuration_public_ip_id = None
        self.state = None
        self.tags = None

        self.results = dict(changed=False, state=dict())

        required_if = [
            ('state', 'present', ['resource_group', 'name']),
        ]

        super().__init__(
            derived_arg_spec=self.module_arg_spec,
            supports_check_mode=True,
            supports_tags=True,
            required_if=required_if,
        )

    def exec_module(self, **kwargs):
        for key in list(self.module_arg_spec.keys()) + ['tags']:
            setattr(self, key, kwargs[key])

        resource_group = self.resource_group
        name = self.name

        # Get existing resource
        response = self.get_resource()

        if self.state == 'present':
            if not self.location:
                rg = self.get_resource_group(resource_group)
                self.location = rg.location

            # Build the resource body from parameters
            body = self.build_body()

            if response:
                # Check if update needed
                update_tags, new_tags = self.update_tags(response.get('tags'))
                if update_tags:
                    body['tags'] = new_tags
                    self.results['changed'] = True

                if self.check_update(response, body):
                    self.results['changed'] = True

                if self.results['changed']:
                    if not self.check_mode:
                        response = self.create_or_update(resource_group, name, body)
                else:
                    response = response
            else:
                if self.tags:
                    body['tags'] = self.tags
                if not self.check_mode:
                    response = self.create_or_update(resource_group, name, body)
                self.results['changed'] = True

        elif self.state == 'absent':
            if response:
                if not self.check_mode:
                    self.delete_resource(resource_group, name)
                self.results['changed'] = True

        if response:
            self.results['state'] = self.format_response(response)

        return self.results

    def build_body(self):
        body = dict(
            location=self.location,
        )
        if self.gateway_type is not None:
            body['gatewayType'] = self.gateway_type
        if self.vpn_type is not None:
            body['vpnType'] = self.vpn_type
        if self.sku_name is not None:
            _target = body
            _target = _target.setdefault('sku', {})
            _target['name'] = self.sku_name
        if self.enable_bgp is not None:
            body['enableBgp'] = self.enable_bgp
        if self.ip_configuration_subnet_id is not None:
            _target = body
            _target = _target.setdefault('ipConfigurations[0]', {})
            _target = _target.setdefault('subnet', {})
            _target['id'] = self.ip_configuration_subnet_id
        if self.ip_configuration_public_ip_id is not None:
            _target = body
            _target = _target.setdefault('ipConfigurations[0]', {})
            _target = _target.setdefault('publicIPAddress', {})
            _target['id'] = self.ip_configuration_public_ip_id

        if self.tags:
            body['tags'] = self.tags

        return body

    def check_update(self, existing, desired):
        """Compare existing resource with desired state."""
        # Check gateway_type
        if self.gateway_type is not None:
            if existing.get('gatewayType') != self.gateway_type:
                return True
        # Check vpn_type
        if self.vpn_type is not None:
            if existing.get('vpnType') != self.vpn_type:
                return True
        # Check sku_name
        if self.sku_name is not None:
            _existing = existing
            _existing = _existing.get('sku', {}) if isinstance(_existing, dict) else {}
            if _existing.get('name') != self.sku_name:
                return True
        # Check enable_bgp
        if self.enable_bgp is not None:
            if existing.get('enableBgp') != self.enable_bgp:
                return True
        # Check ip_configuration_subnet_id
        if self.ip_configuration_subnet_id is not None:
            _existing = existing
            _existing = _existing.get('ipConfigurations[0]', {}) if isinstance(_existing, dict) else {}
            _existing = _existing.get('subnet', {}) if isinstance(_existing, dict) else {}
            if _existing.get('id') != self.ip_configuration_subnet_id:
                return True
        # Check ip_configuration_public_ip_id
        if self.ip_configuration_public_ip_id is not None:
            _existing = existing
            _existing = _existing.get('ipConfigurations[0]', {}) if isinstance(_existing, dict) else {}
            _existing = _existing.get('publicIPAddress', {}) if isinstance(_existing, dict) else {}
            if _existing.get('id') != self.ip_configuration_public_ip_id:
                return True

        return False

    def get_resource(self):
        try:
            url = self.get_resource_url()
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2024-03-01'},
                None, None, [200], 0, 0,
            )
            return self.deserialize_response(response)
        except Exception:
            return None

    def create_or_update(self, resource_group, name, body):
        url = self.get_resource_url()
        response = self.mgmt_client.query(
            url, "PUT",
            {'api-version': '2024-03-01'},
            None, body, [200, 201], 0, 0,
        )
        return self.deserialize_response(response)

    def delete_resource(self, resource_group, name):
        url = self.get_resource_url()
        self.mgmt_client.query(
            url, "DELETE",
            {'api-version': '2024-03-01'},
            None, None, [200, 202, 204], 0, 0,
        )

    def get_resource_url(self):
        return (
            '/subscriptions/{subscription_id}'
            '/resourceGroups/{resource_group}'
            '/providers/Microsoft.Network/virtualNetworkGateways/{name}'
        ).format(
            subscription_id=self.subscription_id,
            resource_group=self.resource_group,
            name=self.name,
        )

    def format_response(self, response):
        result = dict(
            id=response.get('id'),
            name=response.get('name'),
            location=response.get('location'),
            tags=response.get('tags'),
        )
        result['gateway_type'] = response.get('gatewayType')
        result['vpn_type'] = response.get('vpnType')
        _body = response
        _body = _body.get('sku', {}) if isinstance(_body, dict) else {}
        result['sku_name'] = _body.get('name')
        result['enable_bgp'] = response.get('enableBgp')
        _body = response
        _body = _body.get('ipConfigurations[0]', {}) if isinstance(_body, dict) else {}
        _body = _body.get('subnet', {}) if isinstance(_body, dict) else {}
        result['ip_configuration_subnet_id'] = _body.get('id')
        _body = response
        _body = _body.get('ipConfigurations[0]', {}) if isinstance(_body, dict) else {}
        _body = _body.get('publicIPAddress', {}) if isinstance(_body, dict) else {}
        result['ip_configuration_public_ip_id'] = _body.get('id')
        return result

    @staticmethod
    def deserialize_response(response):
        try:
            return json.loads(response.text)
        except (ValueError, AttributeError):
            return None


def main():
    AzureRMVirtualNetworkGateway()


if __name__ == '__main__':
    main()
