#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2024, Azure Magic Modules Generator
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Auto-generated by Azure Magic Modules — do not edit manually

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: azure_rm_bastionhost_info
version_added: "0.1.0"
short_description: Get facts for Azure BastionHost
description:
    - Get facts for a specific BastionHost or list all BastionHosts in a resource group.
    - This module was auto-generated by Azure Magic Modules.
options:
    resource_group:
        description:
            - Name of the resource group.
        type: str
        required: true
    name:
        description:
            - Name of the bastionhost.
            - If not specified, all bastionhosts in the resource group will be listed.
        type: str
extends_documentation_fragment:
    - azure.azcollection.azure
    - azure.azcollection.azure_tags
author:
    - "Azure Magic Modules Generator (@azure-magic-modules)"
seealso:
    - description: Azure BastionHost REST API
      link: https://learn.microsoft.com/en-us/azure/bastion/bastion-overview
'''

EXAMPLES = r'''
- name: Get facts for a specific BastionHost
  azure_rm_bastionhost_info:
    resource_group: myResourceGroup
    name: myBastionHost

- name: List all BastionHosts in a resource group
  azure_rm_bastionhost_info:
    resource_group: myResourceGroup
'''

RETURN = r'''
bastionhosts:
    description:
        - List of bastionhost dicts.
    returned: always
    type: list
    elements: dict
    contains:
        id:
            description: Resource ID.
            type: str
        name:
            description: Resource name.
            type: str
        location:
            description: Resource location.
            type: str
        tags:
            description: Resource tags.
            type: dict
        sku_name:
            description: SKU name of the Bastion host.
            type: str
        ip_configuration_subnet_id:
            description: Resource ID of the AzureBastionSubnet.
            type: str
        ip_configuration_public_ip_id:
            description: Resource ID of the public IP for the Bastion host.
            type: str
        enable_tunneling:
            description: Enable native client tunneling support.
            type: bool
        enable_shareable_link:
            description: Enable shareable link for the Bastion host.
            type: bool
'''

import json
from ansible_collections.azure.azcollection.plugins.module_utils.azure_rm_common import AzureRMModuleBase


class AzureRMBastionHostInfo(AzureRMModuleBase):

    def __init__(self):
        self.module_arg_spec = dict(
            resource_group=dict(type='str', required=True, aliases=['resource_group_name']),
            name=dict(type='str'),
        )

        self.resource_group = None
        self.name = None
        self.tags = None

        self.results = dict(
            changed=False,
            bastionhosts=[],
        )

        super().__init__(
            derived_arg_spec=self.module_arg_spec,
            supports_check_mode=True,
            supports_tags=False,
            facts_module=True,
        )

    def exec_module(self, **kwargs):
        for key in list(self.module_arg_spec.keys()) + ['tags']:
            setattr(self, key, kwargs[key])

        result_key = 'bastionhosts'

        if self.name:
            response = self.get_resource()
            if response:
                if self.has_tags(response.get('tags'), self.tags):
                    self.results[result_key] = [self.format_response(response)]
        else:
            responses = self.list_by_resource_group()
            for item in responses:
                if self.has_tags(item.get('tags'), self.tags):
                    self.results[result_key].append(self.format_response(item))

        return self.results

    def get_resource(self):
        try:
            url = (
                '/subscriptions/{subscription_id}'
                '/resourceGroups/{resource_group}'
                '/providers/Microsoft.Network/bastionHosts/{name}'
            ).format(
                subscription_id=self.subscription_id,
                resource_group=self.resource_group,
                name=self.name,
            )
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2024-03-01'},
                None, None, [200], 0, 0,
            )
            return self.deserialize_response(response)
        except Exception:
            return None

    def list_by_resource_group(self):
        try:
            url = (
                '/subscriptions/{subscription_id}'
                '/resourceGroups/{resource_group}'
                '/providers/Microsoft.Network/bastionHosts'
            ).format(
                subscription_id=self.subscription_id,
                resource_group=self.resource_group,
            )
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2024-03-01'},
                None, None, [200], 0, 0,
            )
            result = self.deserialize_response(response)
            if result and isinstance(result, dict):
                return result.get('value', [])
            return []
        except Exception:
            return []

    def format_response(self, response):
        result = dict(
            id=response.get('id'),
            name=response.get('name'),
            location=response.get('location'),
            tags=response.get('tags'),
        )
        _body = response
        _body = _body.get('sku', {}) if isinstance(_body, dict) else {}
        result['sku_name'] = _body.get('name')
        _body = response
        _body = _body.get('ipConfigurations[0]', {}) if isinstance(_body, dict) else {}
        _body = _body.get('subnet', {}) if isinstance(_body, dict) else {}
        result['ip_configuration_subnet_id'] = _body.get('id')
        _body = response
        _body = _body.get('ipConfigurations[0]', {}) if isinstance(_body, dict) else {}
        _body = _body.get('publicIPAddress', {}) if isinstance(_body, dict) else {}
        result['ip_configuration_public_ip_id'] = _body.get('id')
        result['enable_tunneling'] = response.get('enableTunneling')
        result['enable_shareable_link'] = response.get('enableShareableLink')
        return result

    @staticmethod
    def deserialize_response(response):
        try:
            return json.loads(response.text)
        except (ValueError, AttributeError):
            return None


def main():
    AzureRMBastionHostInfo()


if __name__ == '__main__':
    main()
