#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2024, Azure Magic Modules Generator
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Auto-generated by Azure Magic Modules — do not edit manually

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: azure_rm_keyvaultkey_info
version_added: "0.1.0"
short_description: Get facts for Azure KeyVaultKey
description:
    - Get facts for a specific KeyVaultKey or list all KeyVaultKeys in a resource group.
    - This module was auto-generated by Azure Magic Modules.
options:
    resource_group:
        description:
            - Name of the resource group.
        type: str
        required: true
    name:
        description:
            - Name of the keyvaultkey.
            - If not specified, all keyvaultkeys in the resource group will be listed.
        type: str
extends_documentation_fragment:
    - azure.azcollection.azure
    - azure.azcollection.azure_tags
author:
    - "Azure Magic Modules Generator (@azure-magic-modules)"
seealso:
    - description: Azure KeyVaultKey REST API
      link: https://learn.microsoft.com/en-us/azure/key-vault/keys/
'''

EXAMPLES = r'''
- name: Get facts for a specific KeyVaultKey
  azure_rm_keyvaultkey_info:
    resource_group: myResourceGroup
    name: myKeyVaultKey

- name: List all KeyVaultKeys in a resource group
  azure_rm_keyvaultkey_info:
    resource_group: myResourceGroup
'''

RETURN = r'''
keyvaultkeys:
    description:
        - List of keyvaultkey dicts.
    returned: always
    type: list
    elements: dict
    contains:
        id:
            description: Resource ID.
            type: str
        name:
            description: Resource name.
            type: str
        location:
            description: Resource location.
            type: str
        tags:
            description: Resource tags.
            type: dict
        vault_name:
            description: Name of the Key Vault.
            type: str
        key_type:
            description: The type of key to create.
            type: str
        key_size:
            description: The key size in bits.
            type: int
        curve_name:
            description: The elliptic curve name for EC key types.
            type: str
        key_ops:
            description: Permitted JSON web key operations.
            type: list
        enabled:
            description: Whether the key is enabled.
            type: bool
        not_before:
            description: Key not usable before this UTC datetime.
            type: str
        expires:
            description: Key expiry UTC datetime.
            type: str
'''

import json
from ansible_collections.azure.azcollection.plugins.module_utils.azure_rm_common import AzureRMModuleBase


class AzureRMKeyVaultKeyInfo(AzureRMModuleBase):

    def __init__(self):
        self.module_arg_spec = dict(
            resource_group=dict(type='str', required=True, aliases=['resource_group_name']),
            name=dict(type='str'),
        )

        self.resource_group = None
        self.name = None
        self.tags = None

        self.results = dict(
            changed=False,
            keyvaultkeys=[],
        )

        super().__init__(
            derived_arg_spec=self.module_arg_spec,
            supports_check_mode=True,
            supports_tags=False,
            facts_module=True,
        )

    def exec_module(self, **kwargs):
        for key in list(self.module_arg_spec.keys()) + ['tags']:
            setattr(self, key, kwargs[key])

        result_key = 'keyvaultkeys'

        if self.name:
            response = self.get_resource()
            if response:
                if self.has_tags(response.get('tags'), self.tags):
                    self.results[result_key] = [self.format_response(response)]
        else:
            responses = self.list_by_resource_group()
            for item in responses:
                if self.has_tags(item.get('tags'), self.tags):
                    self.results[result_key].append(self.format_response(item))

        return self.results

    def get_resource(self):
        try:
            url = (
                '/subscriptions/{subscription_id}'
                '/resourceGroups/{resource_group}'
                '/providers/Microsoft.KeyVault/vaults/keys/{name}'
            ).format(
                subscription_id=self.subscription_id,
                resource_group=self.resource_group,
                name=self.name,
            )
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2023-07-01'},
                None, None, [200], 0, 0,
            )
            return self.deserialize_response(response)
        except Exception:
            return None

    def list_by_resource_group(self):
        try:
            url = (
                '/subscriptions/{subscription_id}'
                '/resourceGroups/{resource_group}'
                '/providers/Microsoft.KeyVault/vaults/keys'
            ).format(
                subscription_id=self.subscription_id,
                resource_group=self.resource_group,
            )
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2023-07-01'},
                None, None, [200], 0, 0,
            )
            result = self.deserialize_response(response)
            if result and isinstance(result, dict):
                return result.get('value', [])
            return []
        except Exception:
            return []

    def format_response(self, response):
        result = dict(
            id=response.get('id'),
            name=response.get('name'),
            location=response.get('location'),
            tags=response.get('tags'),
        )
        result['vault_name'] = response.get('vaultName')
        result['key_type'] = response.get('properties', {}).get('kty')
        result['key_size'] = response.get('properties', {}).get('keySize')
        result['curve_name'] = response.get('properties', {}).get('curveName')
        result['key_ops'] = response.get('properties', {}).get('keyOps')
        _props = response.get('properties', {})
        _props = _props.get('attributes', {}) if isinstance(_props, dict) else {}
        result['enabled'] = _props.get('enabled')
        _props = response.get('properties', {})
        _props = _props.get('attributes', {}) if isinstance(_props, dict) else {}
        result['not_before'] = _props.get('nbf')
        _props = response.get('properties', {})
        _props = _props.get('attributes', {}) if isinstance(_props, dict) else {}
        result['expires'] = _props.get('exp')
        return result

    @staticmethod
    def deserialize_response(response):
        try:
            return json.loads(response.text)
        except (ValueError, AttributeError):
            return None


def main():
    AzureRMKeyVaultKeyInfo()


if __name__ == '__main__':
    main()
