#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2024, Azure Magic Modules Generator
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Auto-generated by Azure Magic Modules — do not edit manually

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: azure_rm_expressroutecircuit
version_added: "0.1.0"
short_description: Manage Azure ExpressRoute circuits.
description:
    - Create, update, or delete an Azure ExpressRouteCircuit.
    - This module was auto-generated by Azure Magic Modules.
options:
    resource_group:
        description:
            - Name of the resource group.
        type: str
        required: true
    name:
        description:
            - Name of the expressroutecircuit.
        type: str
        required: true
    location:
        description:
            - Valid Azure location. Defaults to the location of the resource group.
        type: str
    sku_name:
        description:
            - SKU name of the ExpressRoute circuit.
        type: str
    sku_tier:
        description:
            - SKU tier of the ExpressRoute circuit.
        type: str
        choices:
            - "Standard"
            - "Premium"
    sku_family:
        description:
            - SKU billing family of the ExpressRoute circuit.
        type: str
        choices:
            - "MeteredData"
            - "UnlimitedData"
    service_provider_name:
        description:
            - Name of the ExpressRoute service provider.
        type: str
    peering_location:
        description:
            - Peering location of the ExpressRoute circuit.
        type: str
    bandwidth_in_mbps:
        description:
            - Bandwidth in Mbps of the ExpressRoute circuit.
        type: int
    state:
        description:
            - Assert the state of the expressroutecircuit.
            - Use C(present) to create or update and C(absent) to delete.
        type: str
        default: present
        choices:
            - present
            - absent
extends_documentation_fragment:
    - azure.azcollection.azure
    - azure.azcollection.azure_tags
author:
    - "Azure Magic Modules Generator (@azure-magic-modules)"
seealso:
    - description: Azure ExpressRouteCircuit REST API
      link: https://learn.microsoft.com/en-us/azure/expressroute/expressroute-circuit-peerings
'''

EXAMPLES = r'''
- name: Create ExpressRouteCircuit
  azure_rm_expressroutecircuit:
    resource_group: myResourceGroup
    name: myExpressRouteCircuit
    location: eastus
    state: present

- name: Delete ExpressRouteCircuit
  azure_rm_expressroutecircuit:
    resource_group: myResourceGroup
    name: myExpressRouteCircuit
    state: absent
'''

RETURN = r'''
state:
    description: Current state of the expressroutecircuit.
    returned: always
    type: dict
    contains:
        id:
            description: Resource ID.
            type: str
        name:
            description: Resource name.
            type: str
        location:
            description: Resource location.
            type: str
        tags:
            description: Resource tags.
            type: dict
        sku_name:
            description: SKU name of the ExpressRoute circuit.
            type: str
        sku_tier:
            description: SKU tier of the ExpressRoute circuit.
            type: str
        sku_family:
            description: SKU billing family of the ExpressRoute circuit.
            type: str
        service_provider_name:
            description: Name of the ExpressRoute service provider.
            type: str
        peering_location:
            description: Peering location of the ExpressRoute circuit.
            type: str
        bandwidth_in_mbps:
            description: Bandwidth in Mbps of the ExpressRoute circuit.
            type: int
'''

import json
from ansible_collections.azure.azcollection.plugins.module_utils.azure_rm_common import AzureRMModuleBase


class AzureRMExpressRouteCircuit(AzureRMModuleBase):

    def __init__(self):
        self.module_arg_spec = dict(
            resource_group=dict(type='str', required=True, aliases=['resource_group_name']),
            name=dict(type='str', required=True),
            location=dict(type='str'),
            sku_name=dict(
                type='str',
            ),
            sku_tier=dict(
                type='str',
                choices=['Standard', 'Premium'],
            ),
            sku_family=dict(
                type='str',
                choices=['MeteredData', 'UnlimitedData'],
            ),
            service_provider_name=dict(
                type='str',
            ),
            peering_location=dict(
                type='str',
            ),
            bandwidth_in_mbps=dict(
                type='int',
            ),
            state=dict(type='str', default='present', choices=['present', 'absent']),
        )

        self.resource_group = None
        self.name = None
        self.location = None
        self.sku_name = None
        self.sku_tier = None
        self.sku_family = None
        self.service_provider_name = None
        self.peering_location = None
        self.bandwidth_in_mbps = None
        self.state = None
        self.tags = None

        self.results = dict(changed=False, state=dict())

        required_if = [
            ('state', 'present', ['resource_group', 'name']),
        ]

        super().__init__(
            derived_arg_spec=self.module_arg_spec,
            supports_check_mode=True,
            supports_tags=True,
            required_if=required_if,
        )

    def exec_module(self, **kwargs):
        for key in list(self.module_arg_spec.keys()) + ['tags']:
            setattr(self, key, kwargs[key])

        resource_group = self.resource_group
        name = self.name

        # Get existing resource
        response = self.get_resource()

        if self.state == 'present':
            if not self.location:
                rg = self.get_resource_group(resource_group)
                self.location = rg.location

            # Build the resource body from parameters
            body = self.build_body()

            if response:
                # Check if update needed
                update_tags, new_tags = self.update_tags(response.get('tags'))
                if update_tags:
                    body['tags'] = new_tags
                    self.results['changed'] = True

                if self.check_update(response, body):
                    self.results['changed'] = True

                if self.results['changed']:
                    if not self.check_mode:
                        response = self.create_or_update(resource_group, name, body)
                else:
                    response = response
            else:
                if self.tags:
                    body['tags'] = self.tags
                if not self.check_mode:
                    response = self.create_or_update(resource_group, name, body)
                self.results['changed'] = True

        elif self.state == 'absent':
            if response:
                if not self.check_mode:
                    self.delete_resource(resource_group, name)
                self.results['changed'] = True

        if response:
            self.results['state'] = self.format_response(response)

        return self.results

    def build_body(self):
        body = dict(
            location=self.location,
        )
        if self.sku_name is not None:
            _target = body
            _target = _target.setdefault('sku', {})
            _target['name'] = self.sku_name
        if self.sku_tier is not None:
            _target = body
            _target = _target.setdefault('sku', {})
            _target['tier'] = self.sku_tier
        if self.sku_family is not None:
            _target = body
            _target = _target.setdefault('sku', {})
            _target['family'] = self.sku_family
        if self.service_provider_name is not None:
            _target = body
            _target = _target.setdefault('serviceProviderProperties', {})
            _target['serviceProviderName'] = self.service_provider_name
        if self.peering_location is not None:
            _target = body
            _target = _target.setdefault('serviceProviderProperties', {})
            _target['peeringLocation'] = self.peering_location
        if self.bandwidth_in_mbps is not None:
            _target = body
            _target = _target.setdefault('serviceProviderProperties', {})
            _target['bandwidthInMbps'] = self.bandwidth_in_mbps

        if self.tags:
            body['tags'] = self.tags

        return body

    def check_update(self, existing, desired):
        """Compare existing resource with desired state."""
        # Check sku_name
        if self.sku_name is not None:
            _existing = existing
            _existing = _existing.get('sku', {}) if isinstance(_existing, dict) else {}
            if _existing.get('name') != self.sku_name:
                return True
        # Check sku_tier
        if self.sku_tier is not None:
            _existing = existing
            _existing = _existing.get('sku', {}) if isinstance(_existing, dict) else {}
            if _existing.get('tier') != self.sku_tier:
                return True
        # Check sku_family
        if self.sku_family is not None:
            _existing = existing
            _existing = _existing.get('sku', {}) if isinstance(_existing, dict) else {}
            if _existing.get('family') != self.sku_family:
                return True
        # Check service_provider_name
        if self.service_provider_name is not None:
            _existing = existing
            _existing = _existing.get('serviceProviderProperties', {}) if isinstance(_existing, dict) else {}
            if _existing.get('serviceProviderName') != self.service_provider_name:
                return True
        # Check peering_location
        if self.peering_location is not None:
            _existing = existing
            _existing = _existing.get('serviceProviderProperties', {}) if isinstance(_existing, dict) else {}
            if _existing.get('peeringLocation') != self.peering_location:
                return True
        # Check bandwidth_in_mbps
        if self.bandwidth_in_mbps is not None:
            _existing = existing
            _existing = _existing.get('serviceProviderProperties', {}) if isinstance(_existing, dict) else {}
            if _existing.get('bandwidthInMbps') != self.bandwidth_in_mbps:
                return True

        return False

    def get_resource(self):
        try:
            url = self.get_resource_url()
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2024-03-01'},
                None, None, [200], 0, 0,
            )
            return self.deserialize_response(response)
        except Exception:
            return None

    def create_or_update(self, resource_group, name, body):
        url = self.get_resource_url()
        response = self.mgmt_client.query(
            url, "PUT",
            {'api-version': '2024-03-01'},
            None, body, [200, 201], 0, 0,
        )
        return self.deserialize_response(response)

    def delete_resource(self, resource_group, name):
        url = self.get_resource_url()
        self.mgmt_client.query(
            url, "DELETE",
            {'api-version': '2024-03-01'},
            None, None, [200, 202, 204], 0, 0,
        )

    def get_resource_url(self):
        return (
            '/subscriptions/{subscription_id}'
            '/resourceGroups/{resource_group}'
            '/providers/Microsoft.Network/expressRouteCircuits/{name}'
        ).format(
            subscription_id=self.subscription_id,
            resource_group=self.resource_group,
            name=self.name,
        )

    def format_response(self, response):
        result = dict(
            id=response.get('id'),
            name=response.get('name'),
            location=response.get('location'),
            tags=response.get('tags'),
        )
        _body = response
        _body = _body.get('sku', {}) if isinstance(_body, dict) else {}
        result['sku_name'] = _body.get('name')
        _body = response
        _body = _body.get('sku', {}) if isinstance(_body, dict) else {}
        result['sku_tier'] = _body.get('tier')
        _body = response
        _body = _body.get('sku', {}) if isinstance(_body, dict) else {}
        result['sku_family'] = _body.get('family')
        _body = response
        _body = _body.get('serviceProviderProperties', {}) if isinstance(_body, dict) else {}
        result['service_provider_name'] = _body.get('serviceProviderName')
        _body = response
        _body = _body.get('serviceProviderProperties', {}) if isinstance(_body, dict) else {}
        result['peering_location'] = _body.get('peeringLocation')
        _body = response
        _body = _body.get('serviceProviderProperties', {}) if isinstance(_body, dict) else {}
        result['bandwidth_in_mbps'] = _body.get('bandwidthInMbps')
        return result

    @staticmethod
    def deserialize_response(response):
        try:
            return json.loads(response.text)
        except (ValueError, AttributeError):
            return None


def main():
    AzureRMExpressRouteCircuit()


if __name__ == '__main__':
    main()
