#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2024, Azure Magic Modules Generator
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Auto-generated by Azure Magic Modules — do not edit manually

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: azure_rm_cosmosdbsqldatabase
version_added: "0.1.0"
short_description: Manage Azure Cosmos DB SQL API databases.
description:
    - Create, update, or delete an Azure CosmosDbSqlDatabase.
    - This module was auto-generated by Azure Magic Modules.
options:
    resource_group:
        description:
            - Name of the resource group.
        type: str
        required: true
    name:
        description:
            - Name of the cosmosdbsqldatabase.
        type: str
        required: true
    location:
        description:
            - Valid Azure location. Defaults to the location of the resource group.
        type: str
    account_name:
        description:
            - Name of the parent Cosmos DB account.
        type: str
        required: true
    throughput:
        description:
            - Request units per second for the database.
        type: int
    autoscale_max_throughput:
        description:
            - Max throughput for autoscale in request units.
        type: int
    state:
        description:
            - Assert the state of the cosmosdbsqldatabase.
            - Use C(present) to create or update and C(absent) to delete.
        type: str
        default: present
        choices:
            - present
            - absent
extends_documentation_fragment:
    - azure.azcollection.azure
    - azure.azcollection.azure_tags
author:
    - "Azure Magic Modules Generator (@azure-magic-modules)"
seealso:
    - description: Azure CosmosDbSqlDatabase REST API
      link: https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/how-to-create-container
'''

EXAMPLES = r'''
- name: Create CosmosDbSqlDatabase
  azure_rm_cosmosdbsqldatabase:
    resource_group: myResourceGroup
    name: myCosmosDbSqlDatabase
    location: eastus
    account_name: "example_value"
    state: present

- name: Delete CosmosDbSqlDatabase
  azure_rm_cosmosdbsqldatabase:
    resource_group: myResourceGroup
    name: myCosmosDbSqlDatabase
    state: absent
'''

RETURN = r'''
state:
    description: Current state of the cosmosdbsqldatabase.
    returned: always
    type: dict
    contains:
        id:
            description: Resource ID.
            type: str
        name:
            description: Resource name.
            type: str
        location:
            description: Resource location.
            type: str
        tags:
            description: Resource tags.
            type: dict
        account_name:
            description: Name of the parent Cosmos DB account.
            type: str
        throughput:
            description: Request units per second for the database.
            type: int
        autoscale_max_throughput:
            description: Max throughput for autoscale in request units.
            type: int
'''

import json
from ansible_collections.azure.azcollection.plugins.module_utils.azure_rm_common import AzureRMModuleBase


class AzureRMCosmosDbSqlDatabase(AzureRMModuleBase):

    def __init__(self):
        self.module_arg_spec = dict(
            resource_group=dict(type='str', required=True, aliases=['resource_group_name']),
            name=dict(type='str', required=True),
            location=dict(type='str'),
            account_name=dict(
                type='str',
                required=True,
            ),
            throughput=dict(
                type='int',
            ),
            autoscale_max_throughput=dict(
                type='int',
            ),
            state=dict(type='str', default='present', choices=['present', 'absent']),
        )

        self.resource_group = None
        self.name = None
        self.location = None
        self.account_name = None
        self.throughput = None
        self.autoscale_max_throughput = None
        self.state = None
        self.tags = None

        self.results = dict(changed=False, state=dict())

        required_if = [
            ('state', 'present', ['resource_group', 'name']),
        ]

        super().__init__(
            derived_arg_spec=self.module_arg_spec,
            supports_check_mode=True,
            supports_tags=True,
            required_if=required_if,
        )

    def exec_module(self, **kwargs):
        for key in list(self.module_arg_spec.keys()) + ['tags']:
            setattr(self, key, kwargs[key])

        resource_group = self.resource_group
        name = self.name

        # Get existing resource
        response = self.get_resource()

        if self.state == 'present':
            if not self.location:
                rg = self.get_resource_group(resource_group)
                self.location = rg.location

            # Build the resource body from parameters
            body = self.build_body()

            if response:
                # Check if update needed
                update_tags, new_tags = self.update_tags(response.get('tags'))
                if update_tags:
                    body['tags'] = new_tags
                    self.results['changed'] = True

                if self.check_update(response, body):
                    self.results['changed'] = True

                if self.results['changed']:
                    if not self.check_mode:
                        response = self.create_or_update(resource_group, name, body)
                else:
                    response = response
            else:
                if self.tags:
                    body['tags'] = self.tags
                if not self.check_mode:
                    response = self.create_or_update(resource_group, name, body)
                self.results['changed'] = True

        elif self.state == 'absent':
            if response:
                if not self.check_mode:
                    self.delete_resource(resource_group, name)
                self.results['changed'] = True

        if response:
            self.results['state'] = self.format_response(response)

        return self.results

    def build_body(self):
        body = dict(
            location=self.location,
        )
        if self.account_name is not None:
            body['AccountName'] = self.account_name

        properties = body.setdefault('properties', {})
        if self.throughput is not None:
            properties['throughput'] = self.throughput
        if self.autoscale_max_throughput is not None:
            properties['autoscaleMaxThroughput'] = self.autoscale_max_throughput

        if self.tags:
            body['tags'] = self.tags

        return body

    def check_update(self, existing, desired):
        """Compare existing resource with desired state."""
        # Check account_name
        if self.account_name is not None:
            if existing.get('AccountName') != self.account_name:
                return True
        # Check throughput
        if self.throughput is not None:
            if existing.get('properties', {}).get('throughput') != self.throughput:
                return True
        # Check autoscale_max_throughput
        if self.autoscale_max_throughput is not None:
            if existing.get('properties', {}).get('autoscaleMaxThroughput') != self.autoscale_max_throughput:
                return True

        return False

    def get_resource(self):
        try:
            url = self.get_resource_url()
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2024-05-15'},
                None, None, [200], 0, 0,
            )
            return self.deserialize_response(response)
        except Exception:
            return None

    def create_or_update(self, resource_group, name, body):
        url = self.get_resource_url()
        response = self.mgmt_client.query(
            url, "PUT",
            {'api-version': '2024-05-15'},
            None, body, [200, 201], 0, 0,
        )
        return self.deserialize_response(response)

    def delete_resource(self, resource_group, name):
        url = self.get_resource_url()
        self.mgmt_client.query(
            url, "DELETE",
            {'api-version': '2024-05-15'},
            None, None, [200, 202, 204], 0, 0,
        )

    def get_resource_url(self):
        return (
            '/subscriptions/{subscription_id}'
            '/resourceGroups/{resource_group}'
            '/providers/Microsoft.DocumentDB/databaseAccounts/sqlDatabases/{name}'
        ).format(
            subscription_id=self.subscription_id,
            resource_group=self.resource_group,
            name=self.name,
        )

    def format_response(self, response):
        result = dict(
            id=response.get('id'),
            name=response.get('name'),
            location=response.get('location'),
            tags=response.get('tags'),
        )
        result['account_name'] = response.get('AccountName')
        result['throughput'] = response.get('properties', {}).get('throughput')
        result['autoscale_max_throughput'] = response.get('properties', {}).get('autoscaleMaxThroughput')
        return result

    @staticmethod
    def deserialize_response(response):
        try:
            return json.loads(response.text)
        except (ValueError, AttributeError):
            return None


def main():
    AzureRMCosmosDbSqlDatabase()


if __name__ == '__main__':
    main()
