#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2024, Azure Magic Modules Generator
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Auto-generated by Azure Magic Modules — do not edit manually

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: azure_rm_purviewaccount
version_added: "0.1.0"
short_description: Manage Microsoft Purview accounts.
description:
    - Create, update, or delete an Azure PurviewAccount.
    - This module was auto-generated by Azure Magic Modules.
options:
    resource_group:
        description:
            - Name of the resource group.
        type: str
        required: true
    name:
        description:
            - Name of the purviewaccount.
        type: str
        required: true
    location:
        description:
            - Valid Azure location. Defaults to the location of the resource group.
        type: str
    managed_resource_group_name:
        description:
            - Name of the managed resource group.
        type: str
    public_network_access:
        description:
            - Whether public network access is allowed.
        type: str
        choices:
            - "Enabled"
            - "Disabled"
    identity_type:
        description:
            - Type of managed identity.
        type: str
        choices:
            - "SystemAssigned"
            - "UserAssigned"
    state:
        description:
            - Assert the state of the purviewaccount.
            - Use C(present) to create or update and C(absent) to delete.
        type: str
        default: present
        choices:
            - present
            - absent
extends_documentation_fragment:
    - azure.azcollection.azure
    - azure.azcollection.azure_tags
author:
    - "Azure Magic Modules Generator (@azure-magic-modules)"
seealso:
    - description: Azure PurviewAccount REST API
      link: https://learn.microsoft.com/en-us/azure/purview/
'''

EXAMPLES = r'''
- name: Create PurviewAccount
  azure_rm_purviewaccount:
    resource_group: myResourceGroup
    name: myPurviewAccount
    location: eastus
    state: present

- name: Delete PurviewAccount
  azure_rm_purviewaccount:
    resource_group: myResourceGroup
    name: myPurviewAccount
    state: absent
'''

RETURN = r'''
state:
    description: Current state of the purviewaccount.
    returned: always
    type: dict
    contains:
        id:
            description: Resource ID.
            type: str
        name:
            description: Resource name.
            type: str
        location:
            description: Resource location.
            type: str
        tags:
            description: Resource tags.
            type: dict
        managed_resource_group_name:
            description: Name of the managed resource group.
            type: str
        public_network_access:
            description: Whether public network access is allowed.
            type: str
        identity_type:
            description: Type of managed identity.
            type: str
'''

import json
from ansible_collections.azure.azcollection.plugins.module_utils.azure_rm_common import AzureRMModuleBase


class AzureRMPurviewAccount(AzureRMModuleBase):

    def __init__(self):
        self.module_arg_spec = dict(
            resource_group=dict(type='str', required=True, aliases=['resource_group_name']),
            name=dict(type='str', required=True),
            location=dict(type='str'),
            managed_resource_group_name=dict(
                type='str',
            ),
            public_network_access=dict(
                type='str',
                choices=['Enabled', 'Disabled'],
            ),
            identity_type=dict(
                type='str',
                choices=['SystemAssigned', 'UserAssigned'],
            ),
            state=dict(type='str', default='present', choices=['present', 'absent']),
        )

        self.resource_group = None
        self.name = None
        self.location = None
        self.managed_resource_group_name = None
        self.public_network_access = None
        self.identity_type = None
        self.state = None
        self.tags = None

        self.results = dict(changed=False, state=dict())

        required_if = [
            ('state', 'present', ['resource_group', 'name']),
        ]

        super().__init__(
            derived_arg_spec=self.module_arg_spec,
            supports_check_mode=True,
            supports_tags=True,
            required_if=required_if,
        )

    def exec_module(self, **kwargs):
        for key in list(self.module_arg_spec.keys()) + ['tags']:
            setattr(self, key, kwargs[key])

        resource_group = self.resource_group
        name = self.name

        # Get existing resource
        response = self.get_resource()

        if self.state == 'present':
            if not self.location:
                rg = self.get_resource_group(resource_group)
                self.location = rg.location

            # Build the resource body from parameters
            body = self.build_body()

            if response:
                # Check if update needed
                update_tags, new_tags = self.update_tags(response.get('tags'))
                if update_tags:
                    body['tags'] = new_tags
                    self.results['changed'] = True

                if self.check_update(response, body):
                    self.results['changed'] = True

                if self.results['changed']:
                    if not self.check_mode:
                        response = self.create_or_update(resource_group, name, body)
                else:
                    response = response
            else:
                if self.tags:
                    body['tags'] = self.tags
                if not self.check_mode:
                    response = self.create_or_update(resource_group, name, body)
                self.results['changed'] = True

        elif self.state == 'absent':
            if response:
                if not self.check_mode:
                    self.delete_resource(resource_group, name)
                self.results['changed'] = True

        if response:
            self.results['state'] = self.format_response(response)

        return self.results

    def build_body(self):
        body = dict(
            location=self.location,
        )
        if self.managed_resource_group_name is not None:
            body['managedResourceGroupName'] = self.managed_resource_group_name
        if self.public_network_access is not None:
            body['publicNetworkAccess'] = self.public_network_access
        if self.identity_type is not None:
            _target = body
            _target = _target.setdefault('identity', {})
            _target['type'] = self.identity_type

        if self.tags:
            body['tags'] = self.tags

        return body

    def check_update(self, existing, desired):
        """Compare existing resource with desired state."""
        # Check managed_resource_group_name
        if self.managed_resource_group_name is not None:
            if existing.get('managedResourceGroupName') != self.managed_resource_group_name:
                return True
        # Check public_network_access
        if self.public_network_access is not None:
            if existing.get('publicNetworkAccess') != self.public_network_access:
                return True
        # Check identity_type
        if self.identity_type is not None:
            _existing = existing
            _existing = _existing.get('identity', {}) if isinstance(_existing, dict) else {}
            if _existing.get('type') != self.identity_type:
                return True

        return False

    def get_resource(self):
        try:
            url = self.get_resource_url()
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2021-07-01'},
                None, None, [200], 0, 0,
            )
            return self.deserialize_response(response)
        except Exception:
            return None

    def create_or_update(self, resource_group, name, body):
        url = self.get_resource_url()
        response = self.mgmt_client.query(
            url, "PUT",
            {'api-version': '2021-07-01'},
            None, body, [200, 201], 0, 0,
        )
        return self.deserialize_response(response)

    def delete_resource(self, resource_group, name):
        url = self.get_resource_url()
        self.mgmt_client.query(
            url, "DELETE",
            {'api-version': '2021-07-01'},
            None, None, [200, 202, 204], 0, 0,
        )

    def get_resource_url(self):
        return (
            '/subscriptions/{subscription_id}'
            '/resourceGroups/{resource_group}'
            '/providers/Microsoft.Purview/accounts/{name}'
        ).format(
            subscription_id=self.subscription_id,
            resource_group=self.resource_group,
            name=self.name,
        )

    def format_response(self, response):
        result = dict(
            id=response.get('id'),
            name=response.get('name'),
            location=response.get('location'),
            tags=response.get('tags'),
        )
        result['managed_resource_group_name'] = response.get('managedResourceGroupName')
        result['public_network_access'] = response.get('publicNetworkAccess')
        _body = response
        _body = _body.get('identity', {}) if isinstance(_body, dict) else {}
        result['identity_type'] = _body.get('type')
        return result

    @staticmethod
    def deserialize_response(response):
        try:
            return json.loads(response.text)
        except (ValueError, AttributeError):
            return None


def main():
    AzureRMPurviewAccount()


if __name__ == '__main__':
    main()
