#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2024, Azure Magic Modules Generator
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Auto-generated by Azure Magic Modules — do not edit manually

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: azure_rm_synapsesqlpool
version_added: "0.1.0"
short_description: Manage Azure Synapse Analytics SQL pools.
description:
    - Create, update, or delete an Azure SynapseSqlPool.
    - This module was auto-generated by Azure Magic Modules.
options:
    resource_group:
        description:
            - Name of the resource group.
        type: str
        required: true
    name:
        description:
            - Name of the synapsesqlpool.
        type: str
        required: true
    location:
        description:
            - Valid Azure location. Defaults to the location of the resource group.
        type: str
    workspace_name:
        description:
            - Name of the parent Synapse workspace.
        type: str
        required: true
    sku_name:
        description:
            - SKU name for the SQL pool performance level.
        type: str
        choices:
            - "DW100c"
            - "DW200c"
            - "DW300c"
            - "DW400c"
            - "DW500c"
            - "DW1000c"
            - "DW1500c"
            - "DW2000c"
            - "DW2500c"
            - "DW3000c"
            - "DW5000c"
            - "DW6000c"
            - "DW7500c"
            - "DW10000c"
            - "DW15000c"
            - "DW30000c"
    collation:
        description:
            - Database collation for the SQL pool.
        type: str
        default: "SQL_Latin1_General_CP1_CI_AS"
    create_mode:
        description:
            - Specifies the mode of SQL pool creation.
        type: str
        choices:
            - "Default"
            - "Recovery"
            - "PointInTimeRestore"
            - "Restore"
    state:
        description:
            - Assert the state of the synapsesqlpool.
            - Use C(present) to create or update and C(absent) to delete.
        type: str
        default: present
        choices:
            - present
            - absent
extends_documentation_fragment:
    - azure.azcollection.azure
    - azure.azcollection.azure_tags
author:
    - "Azure Magic Modules Generator (@azure-magic-modules)"
seealso:
    - description: Azure SynapseSqlPool REST API
      link: https://learn.microsoft.com/en-us/azure/synapse-analytics/sql-data-warehouse/
'''

EXAMPLES = r'''
- name: Create SynapseSqlPool
  azure_rm_synapsesqlpool:
    resource_group: myResourceGroup
    name: mySynapseSqlPool
    location: eastus
    workspace_name: "example_value"
    state: present

- name: Delete SynapseSqlPool
  azure_rm_synapsesqlpool:
    resource_group: myResourceGroup
    name: mySynapseSqlPool
    state: absent
'''

RETURN = r'''
state:
    description: Current state of the synapsesqlpool.
    returned: always
    type: dict
    contains:
        id:
            description: Resource ID.
            type: str
        name:
            description: Resource name.
            type: str
        location:
            description: Resource location.
            type: str
        tags:
            description: Resource tags.
            type: dict
        workspace_name:
            description: Name of the parent Synapse workspace.
            type: str
        sku_name:
            description: SKU name for the SQL pool performance level.
            type: str
        collation:
            description: Database collation for the SQL pool.
            type: str
        create_mode:
            description: Specifies the mode of SQL pool creation.
            type: str
'''

import json
from ansible_collections.azure.azcollection.plugins.module_utils.azure_rm_common import AzureRMModuleBase


class AzureRMSynapseSqlPool(AzureRMModuleBase):

    def __init__(self):
        self.module_arg_spec = dict(
            resource_group=dict(type='str', required=True, aliases=['resource_group_name']),
            name=dict(type='str', required=True),
            location=dict(type='str'),
            workspace_name=dict(
                type='str',
                required=True,
            ),
            sku_name=dict(
                type='str',
                choices=[
                    'DW100c',
                    'DW200c',
                    'DW300c',
                    'DW400c',
                    'DW500c',
                    'DW1000c',
                    'DW1500c',
                    'DW2000c',
                    'DW2500c',
                    'DW3000c',
                    'DW5000c',
                    'DW6000c',
                    'DW7500c',
                    'DW10000c',
                    'DW15000c',
                    'DW30000c',
                ],
            ),
            collation=dict(
                type='str',
                default='SQL_Latin1_General_CP1_CI_AS',
            ),
            create_mode=dict(
                type='str',
                choices=['Default', 'Recovery', 'PointInTimeRestore', 'Restore'],
            ),
            state=dict(type='str', default='present', choices=['present', 'absent']),
        )

        self.resource_group = None
        self.name = None
        self.location = None
        self.workspace_name = None
        self.sku_name = None
        self.collation = None
        self.create_mode = None
        self.state = None
        self.tags = None

        self.results = dict(changed=False, state=dict())

        required_if = [
            ('state', 'present', ['resource_group', 'name']),
        ]

        super().__init__(
            derived_arg_spec=self.module_arg_spec,
            supports_check_mode=True,
            supports_tags=True,
            required_if=required_if,
        )

    def exec_module(self, **kwargs):
        for key in list(self.module_arg_spec.keys()) + ['tags']:
            setattr(self, key, kwargs[key])

        resource_group = self.resource_group
        name = self.name

        # Get existing resource
        response = self.get_resource()

        if self.state == 'present':
            if not self.location:
                rg = self.get_resource_group(resource_group)
                self.location = rg.location

            # Build the resource body from parameters
            body = self.build_body()

            if response:
                # Check if update needed
                update_tags, new_tags = self.update_tags(response.get('tags'))
                if update_tags:
                    body['tags'] = new_tags
                    self.results['changed'] = True

                if self.check_update(response, body):
                    self.results['changed'] = True

                if self.results['changed']:
                    if not self.check_mode:
                        response = self.create_or_update(resource_group, name, body)
                else:
                    response = response
            else:
                if self.tags:
                    body['tags'] = self.tags
                if not self.check_mode:
                    response = self.create_or_update(resource_group, name, body)
                self.results['changed'] = True

        elif self.state == 'absent':
            if response:
                if not self.check_mode:
                    self.delete_resource(resource_group, name)
                self.results['changed'] = True

        if response:
            self.results['state'] = self.format_response(response)

        return self.results

    def build_body(self):
        body = dict(
            location=self.location,
        )
        if self.workspace_name is not None:
            body['WorkspaceName'] = self.workspace_name
        if self.sku_name is not None:
            _target = body
            _target = _target.setdefault('sku', {})
            _target['name'] = self.sku_name
        if self.collation is not None:
            body['collation'] = self.collation
        if self.create_mode is not None:
            body['createMode'] = self.create_mode

        if self.tags:
            body['tags'] = self.tags

        return body

    def check_update(self, existing, desired):
        """Compare existing resource with desired state."""
        # Check workspace_name
        if self.workspace_name is not None:
            if existing.get('WorkspaceName') != self.workspace_name:
                return True
        # Check sku_name
        if self.sku_name is not None:
            _existing = existing
            _existing = _existing.get('sku', {}) if isinstance(_existing, dict) else {}
            if _existing.get('name') != self.sku_name:
                return True
        # Check collation
        if self.collation is not None:
            if existing.get('collation') != self.collation:
                return True
        # Check create_mode
        if self.create_mode is not None:
            if existing.get('createMode') != self.create_mode:
                return True

        return False

    def get_resource(self):
        try:
            url = self.get_resource_url()
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2021-06-01'},
                None, None, [200], 0, 0,
            )
            return self.deserialize_response(response)
        except Exception:
            return None

    def create_or_update(self, resource_group, name, body):
        url = self.get_resource_url()
        response = self.mgmt_client.query(
            url, "PUT",
            {'api-version': '2021-06-01'},
            None, body, [200, 201], 0, 0,
        )
        return self.deserialize_response(response)

    def delete_resource(self, resource_group, name):
        url = self.get_resource_url()
        self.mgmt_client.query(
            url, "DELETE",
            {'api-version': '2021-06-01'},
            None, None, [200, 202, 204], 0, 0,
        )

    def get_resource_url(self):
        return (
            '/subscriptions/{subscription_id}'
            '/resourceGroups/{resource_group}'
            '/providers/Microsoft.Synapse/workspaces/sqlPools/{name}'
        ).format(
            subscription_id=self.subscription_id,
            resource_group=self.resource_group,
            name=self.name,
        )

    def format_response(self, response):
        result = dict(
            id=response.get('id'),
            name=response.get('name'),
            location=response.get('location'),
            tags=response.get('tags'),
        )
        result['workspace_name'] = response.get('WorkspaceName')
        _body = response
        _body = _body.get('sku', {}) if isinstance(_body, dict) else {}
        result['sku_name'] = _body.get('name')
        result['collation'] = response.get('collation')
        result['create_mode'] = response.get('createMode')
        return result

    @staticmethod
    def deserialize_response(response):
        try:
            return json.loads(response.text)
        except (ValueError, AttributeError):
            return None


def main():
    AzureRMSynapseSqlPool()


if __name__ == '__main__':
    main()
