#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2024, Azure Magic Modules Generator
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Auto-generated by Azure Magic Modules — do not edit manually

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: azure_rm_containerregistry
version_added: "0.1.0"
short_description: Manage Azure Container Registry instances.
description:
    - Create, update, or delete an Azure ContainerRegistry.
    - This module was auto-generated by Azure Magic Modules.
options:
    resource_group:
        description:
            - Name of the resource group.
        type: str
        required: true
    name:
        description:
            - Name of the containerregistry.
        type: str
        required: true
    location:
        description:
            - Valid Azure location. Defaults to the location of the resource group.
        type: str
    sku_name:
        description:
            - SKU name for the container registry.
        type: str
        choices:
            - "Basic"
            - "Standard"
            - "Premium"
    admin_user_enabled:
        description:
            - Whether the admin user is enabled.
        type: bool
        default: "False"
    public_network_access:
        description:
            - Whether public network access is allowed.
        type: str
        choices:
            - "Enabled"
            - "Disabled"
    zone_redundancy:
        description:
            - Whether zone redundancy is enabled.
        type: str
        choices:
            - "Enabled"
            - "Disabled"
    encryption_status:
        description:
            - Whether encryption is enabled.
        type: str
        choices:
            - "enabled"
            - "disabled"
    state:
        description:
            - Assert the state of the containerregistry.
            - Use C(present) to create or update and C(absent) to delete.
        type: str
        default: present
        choices:
            - present
            - absent
extends_documentation_fragment:
    - azure.azcollection.azure
    - azure.azcollection.azure_tags
author:
    - "Azure Magic Modules Generator (@azure-magic-modules)"
seealso:
    - description: Azure ContainerRegistry REST API
      link: https://learn.microsoft.com/en-us/azure/container-registry/
'''

EXAMPLES = r'''
- name: Create ContainerRegistry
  azure_rm_containerregistry:
    resource_group: myResourceGroup
    name: myContainerRegistry
    location: eastus
    state: present

- name: Delete ContainerRegistry
  azure_rm_containerregistry:
    resource_group: myResourceGroup
    name: myContainerRegistry
    state: absent
'''

RETURN = r'''
state:
    description: Current state of the containerregistry.
    returned: always
    type: dict
    contains:
        id:
            description: Resource ID.
            type: str
        name:
            description: Resource name.
            type: str
        location:
            description: Resource location.
            type: str
        tags:
            description: Resource tags.
            type: dict
        sku_name:
            description: SKU name for the container registry.
            type: str
        admin_user_enabled:
            description: Whether the admin user is enabled.
            type: bool
        public_network_access:
            description: Whether public network access is allowed.
            type: str
        zone_redundancy:
            description: Whether zone redundancy is enabled.
            type: str
        encryption_status:
            description: Whether encryption is enabled.
            type: str
'''

import json
from ansible_collections.azure.azcollection.plugins.module_utils.azure_rm_common import AzureRMModuleBase


class AzureRMContainerRegistry(AzureRMModuleBase):

    def __init__(self):
        self.module_arg_spec = dict(
            resource_group=dict(type='str', required=True, aliases=['resource_group_name']),
            name=dict(type='str', required=True),
            location=dict(type='str'),
            sku_name=dict(
                type='str',
                choices=['Basic', 'Standard', 'Premium'],
            ),
            admin_user_enabled=dict(
                type='bool',
                default=False,
            ),
            public_network_access=dict(
                type='str',
                choices=['Enabled', 'Disabled'],
            ),
            zone_redundancy=dict(
                type='str',
                choices=['Enabled', 'Disabled'],
            ),
            encryption_status=dict(
                type='str',
                choices=['enabled', 'disabled'],
            ),
            state=dict(type='str', default='present', choices=['present', 'absent']),
        )

        self.resource_group = None
        self.name = None
        self.location = None
        self.sku_name = None
        self.admin_user_enabled = None
        self.public_network_access = None
        self.zone_redundancy = None
        self.encryption_status = None
        self.state = None
        self.tags = None

        self.results = dict(changed=False, state=dict())

        required_if = [
            ('state', 'present', ['resource_group', 'name']),
        ]

        super().__init__(
            derived_arg_spec=self.module_arg_spec,
            supports_check_mode=True,
            supports_tags=True,
            required_if=required_if,
        )

    def exec_module(self, **kwargs):
        for key in list(self.module_arg_spec.keys()) + ['tags']:
            setattr(self, key, kwargs[key])

        resource_group = self.resource_group
        name = self.name

        # Get existing resource
        response = self.get_resource()

        if self.state == 'present':
            if not self.location:
                rg = self.get_resource_group(resource_group)
                self.location = rg.location

            # Build the resource body from parameters
            body = self.build_body()

            if response:
                # Check if update needed
                update_tags, new_tags = self.update_tags(response.get('tags'))
                if update_tags:
                    body['tags'] = new_tags
                    self.results['changed'] = True

                if self.check_update(response, body):
                    self.results['changed'] = True

                if self.results['changed']:
                    if not self.check_mode:
                        response = self.create_or_update(resource_group, name, body)
                else:
                    response = response
            else:
                if self.tags:
                    body['tags'] = self.tags
                if not self.check_mode:
                    response = self.create_or_update(resource_group, name, body)
                self.results['changed'] = True

        elif self.state == 'absent':
            if response:
                if not self.check_mode:
                    self.delete_resource(resource_group, name)
                self.results['changed'] = True

        if response:
            self.results['state'] = self.format_response(response)

        return self.results

    def build_body(self):
        body = dict(
            location=self.location,
        )
        if self.sku_name is not None:
            _target = body
            _target = _target.setdefault('sku', {})
            _target['name'] = self.sku_name
        if self.admin_user_enabled is not None:
            body['adminUserEnabled'] = self.admin_user_enabled
        if self.public_network_access is not None:
            body['publicNetworkAccess'] = self.public_network_access
        if self.zone_redundancy is not None:
            body['zoneRedundancy'] = self.zone_redundancy
        if self.encryption_status is not None:
            _target = body
            _target = _target.setdefault('encryption', {})
            _target['status'] = self.encryption_status

        if self.tags:
            body['tags'] = self.tags

        return body

    def check_update(self, existing, desired):
        """Compare existing resource with desired state."""
        # Check sku_name
        if self.sku_name is not None:
            _existing = existing
            _existing = _existing.get('sku', {}) if isinstance(_existing, dict) else {}
            if _existing.get('name') != self.sku_name:
                return True
        # Check admin_user_enabled
        if self.admin_user_enabled is not None:
            if existing.get('adminUserEnabled') != self.admin_user_enabled:
                return True
        # Check public_network_access
        if self.public_network_access is not None:
            if existing.get('publicNetworkAccess') != self.public_network_access:
                return True
        # Check zone_redundancy
        if self.zone_redundancy is not None:
            if existing.get('zoneRedundancy') != self.zone_redundancy:
                return True
        # Check encryption_status
        if self.encryption_status is not None:
            _existing = existing
            _existing = _existing.get('encryption', {}) if isinstance(_existing, dict) else {}
            if _existing.get('status') != self.encryption_status:
                return True

        return False

    def get_resource(self):
        try:
            url = self.get_resource_url()
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2023-07-01'},
                None, None, [200], 0, 0,
            )
            return self.deserialize_response(response)
        except Exception:
            return None

    def create_or_update(self, resource_group, name, body):
        url = self.get_resource_url()
        response = self.mgmt_client.query(
            url, "PUT",
            {'api-version': '2023-07-01'},
            None, body, [200, 201], 0, 0,
        )
        return self.deserialize_response(response)

    def delete_resource(self, resource_group, name):
        url = self.get_resource_url()
        self.mgmt_client.query(
            url, "DELETE",
            {'api-version': '2023-07-01'},
            None, None, [200, 202, 204], 0, 0,
        )

    def get_resource_url(self):
        return (
            '/subscriptions/{subscription_id}'
            '/resourceGroups/{resource_group}'
            '/providers/Microsoft.ContainerRegistry/registries/{name}'
        ).format(
            subscription_id=self.subscription_id,
            resource_group=self.resource_group,
            name=self.name,
        )

    def format_response(self, response):
        result = dict(
            id=response.get('id'),
            name=response.get('name'),
            location=response.get('location'),
            tags=response.get('tags'),
        )
        _body = response
        _body = _body.get('sku', {}) if isinstance(_body, dict) else {}
        result['sku_name'] = _body.get('name')
        result['admin_user_enabled'] = response.get('adminUserEnabled')
        result['public_network_access'] = response.get('publicNetworkAccess')
        result['zone_redundancy'] = response.get('zoneRedundancy')
        _body = response
        _body = _body.get('encryption', {}) if isinstance(_body, dict) else {}
        result['encryption_status'] = _body.get('status')
        return result

    @staticmethod
    def deserialize_response(response):
        try:
            return json.loads(response.text)
        except (ValueError, AttributeError):
            return None


def main():
    AzureRMContainerRegistry()


if __name__ == '__main__':
    main()
