#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2024, Azure Magic Modules Generator
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Auto-generated by Azure Magic Modules — do not edit manually

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: azure_rm_managementlock
version_added: "0.1.0"
short_description: Manage Azure management locks on resources.
description:
    - Create, update, or delete an Azure ManagementLock.
    - This module was auto-generated by Azure Magic Modules.
options:
    resource_group:
        description:
            - Name of the resource group.
        type: str
        required: true
    name:
        description:
            - Name of the managementlock.
        type: str
        required: true
    location:
        description:
            - Valid Azure location. Defaults to the location of the resource group.
        type: str
    scope:
        description:
            - The scope to apply the lock to.
        type: str
        required: true
    lock_level:
        description:
            - The level of the management lock.
        type: str
        required: true
        choices:
            - "CanNotDelete"
            - "ReadOnly"
    notes:
        description:
            - Notes about the management lock.
        type: str
    state:
        description:
            - Assert the state of the managementlock.
            - Use C(present) to create or update and C(absent) to delete.
        type: str
        default: present
        choices:
            - present
            - absent
extends_documentation_fragment:
    - azure.azcollection.azure
    - azure.azcollection.azure_tags
author:
    - "Azure Magic Modules Generator (@azure-magic-modules)"
seealso:
    - description: Azure ManagementLock REST API
      link: https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/lock-resources
'''

EXAMPLES = r'''
- name: Create ManagementLock
  azure_rm_managementlock:
    resource_group: myResourceGroup
    name: myManagementLock
    location: eastus
    scope: "example_value"
    lock_level: "example_value"
    state: present

- name: Delete ManagementLock
  azure_rm_managementlock:
    resource_group: myResourceGroup
    name: myManagementLock
    state: absent
'''

RETURN = r'''
state:
    description: Current state of the managementlock.
    returned: always
    type: dict
    contains:
        id:
            description: Resource ID.
            type: str
        name:
            description: Resource name.
            type: str
        location:
            description: Resource location.
            type: str
        tags:
            description: Resource tags.
            type: dict
        scope:
            description: The scope to apply the lock to.
            type: str
        lock_level:
            description: The level of the management lock.
            type: str
        notes:
            description: Notes about the management lock.
            type: str
'''

import json
from ansible_collections.azure.azcollection.plugins.module_utils.azure_rm_common import AzureRMModuleBase


class AzureRMManagementLock(AzureRMModuleBase):

    def __init__(self):
        self.module_arg_spec = dict(
            resource_group=dict(type='str', required=True, aliases=['resource_group_name']),
            name=dict(type='str', required=True),
            location=dict(type='str'),
            scope=dict(
                type='str',
                required=True,
            ),
            lock_level=dict(
                type='str',
                required=True,
                choices=['CanNotDelete', 'ReadOnly'],
            ),
            notes=dict(
                type='str',
            ),
            state=dict(type='str', default='present', choices=['present', 'absent']),
        )

        self.resource_group = None
        self.name = None
        self.location = None
        self.scope = None
        self.lock_level = None
        self.notes = None
        self.state = None
        self.tags = None

        self.results = dict(changed=False, state=dict())

        required_if = [
            ('state', 'present', ['resource_group', 'name']),
        ]

        super().__init__(
            derived_arg_spec=self.module_arg_spec,
            supports_check_mode=True,
            supports_tags=True,
            required_if=required_if,
        )

    def exec_module(self, **kwargs):
        for key in list(self.module_arg_spec.keys()) + ['tags']:
            setattr(self, key, kwargs[key])

        resource_group = self.resource_group
        name = self.name

        # Get existing resource
        response = self.get_resource()

        if self.state == 'present':
            if not self.location:
                rg = self.get_resource_group(resource_group)
                self.location = rg.location

            # Build the resource body from parameters
            body = self.build_body()

            if response:
                # Check if update needed
                update_tags, new_tags = self.update_tags(response.get('tags'))
                if update_tags:
                    body['tags'] = new_tags
                    self.results['changed'] = True

                if self.check_update(response, body):
                    self.results['changed'] = True

                if self.results['changed']:
                    if not self.check_mode:
                        response = self.create_or_update(resource_group, name, body)
                else:
                    response = response
            else:
                if self.tags:
                    body['tags'] = self.tags
                if not self.check_mode:
                    response = self.create_or_update(resource_group, name, body)
                self.results['changed'] = True

        elif self.state == 'absent':
            if response:
                if not self.check_mode:
                    self.delete_resource(resource_group, name)
                self.results['changed'] = True

        if response:
            self.results['state'] = self.format_response(response)

        return self.results

    def build_body(self):
        body = dict(
            location=self.location,
        )
        if self.scope is not None:
            body['scope'] = self.scope

        properties = body.setdefault('properties', {})
        if self.lock_level is not None:
            properties['level'] = self.lock_level
        if self.notes is not None:
            properties['notes'] = self.notes

        if self.tags:
            body['tags'] = self.tags

        return body

    def check_update(self, existing, desired):
        """Compare existing resource with desired state."""
        # Check scope
        if self.scope is not None:
            if existing.get('scope') != self.scope:
                return True
        # Check lock_level
        if self.lock_level is not None:
            if existing.get('properties', {}).get('level') != self.lock_level:
                return True
        # Check notes
        if self.notes is not None:
            if existing.get('properties', {}).get('notes') != self.notes:
                return True

        return False

    def get_resource(self):
        try:
            url = self.get_resource_url()
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2020-05-01'},
                None, None, [200], 0, 0,
            )
            return self.deserialize_response(response)
        except Exception:
            return None

    def create_or_update(self, resource_group, name, body):
        url = self.get_resource_url()
        response = self.mgmt_client.query(
            url, "PUT",
            {'api-version': '2020-05-01'},
            None, body, [200, 201], 0, 0,
        )
        return self.deserialize_response(response)

    def delete_resource(self, resource_group, name):
        url = self.get_resource_url()
        self.mgmt_client.query(
            url, "DELETE",
            {'api-version': '2020-05-01'},
            None, None, [200, 202, 204], 0, 0,
        )

    def get_resource_url(self):
        return (
            '/subscriptions/{subscription_id}'
            '/resourceGroups/{resource_group}'
            '/providers/Microsoft.Authorization/locks/{name}'
        ).format(
            subscription_id=self.subscription_id,
            resource_group=self.resource_group,
            name=self.name,
        )

    def format_response(self, response):
        result = dict(
            id=response.get('id'),
            name=response.get('name'),
            location=response.get('location'),
            tags=response.get('tags'),
        )
        result['scope'] = response.get('scope')
        result['lock_level'] = response.get('properties', {}).get('level')
        result['notes'] = response.get('properties', {}).get('notes')
        return result

    @staticmethod
    def deserialize_response(response):
        try:
            return json.loads(response.text)
        except (ValueError, AttributeError):
            return None


def main():
    AzureRMManagementLock()


if __name__ == '__main__':
    main()
