#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2024, Azure Magic Modules Generator
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Auto-generated by Azure Magic Modules — do not edit manually

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: azure_rm_mariadbserver
version_added: "0.1.0"
short_description: Manage Azure Database for MariaDB server instances.
description:
    - Create, update, or delete an Azure MariaDbServer.
    - This module was auto-generated by Azure Magic Modules.
options:
    resource_group:
        description:
            - Name of the resource group.
        type: str
        required: true
    name:
        description:
            - Name of the mariadbserver.
        type: str
        required: true
    location:
        description:
            - Valid Azure location. Defaults to the location of the resource group.
        type: str
    sku_name:
        description:
            - Name of the SKU for the server.
        type: str
    sku_tier:
        description:
            - Tier of the SKU for the server.
        type: str
    administrator_login:
        description:
            - Administrator login name for the server.
        type: str
    administrator_login_password:
        description:
            - Administrator login password for the server.
        type: str
    version:
        description:
            - MariaDB server version.
        type: str
        choices:
            - "10.2"
            - "10.3"
    storage_mb:
        description:
            - Maximum storage allowed for the server in MB.
        type: int
    backup_retention_days:
        description:
            - Backup retention period in days.
        type: int
    geo_redundant_backup:
        description:
            - Whether geo-redundant backup is enabled.
        type: str
        choices:
            - "Enabled"
            - "Disabled"
    ssl_enforcement:
        description:
            - Whether SSL enforcement is enabled.
        type: str
        choices:
            - "Enabled"
            - "Disabled"
    state:
        description:
            - Assert the state of the mariadbserver.
            - Use C(present) to create or update and C(absent) to delete.
        type: str
        default: present
        choices:
            - present
            - absent
extends_documentation_fragment:
    - azure.azcollection.azure
    - azure.azcollection.azure_tags
author:
    - "Azure Magic Modules Generator (@azure-magic-modules)"
seealso:
    - description: Azure MariaDbServer REST API
      link: https://learn.microsoft.com/en-us/azure/mariadb/overview
'''

EXAMPLES = r'''
- name: Create MariaDbServer
  azure_rm_mariadbserver:
    resource_group: myResourceGroup
    name: myMariaDbServer
    location: eastus
    state: present

- name: Delete MariaDbServer
  azure_rm_mariadbserver:
    resource_group: myResourceGroup
    name: myMariaDbServer
    state: absent
'''

RETURN = r'''
state:
    description: Current state of the mariadbserver.
    returned: always
    type: dict
    contains:
        id:
            description: Resource ID.
            type: str
        name:
            description: Resource name.
            type: str
        location:
            description: Resource location.
            type: str
        tags:
            description: Resource tags.
            type: dict
        sku_name:
            description: Name of the SKU for the server.
            type: str
        sku_tier:
            description: Tier of the SKU for the server.
            type: str
        administrator_login:
            description: Administrator login name for the server.
            type: str
        administrator_login_password:
            description: Administrator login password for the server.
            type: str
        version:
            description: MariaDB server version.
            type: str
        storage_mb:
            description: Maximum storage allowed for the server in MB.
            type: int
        backup_retention_days:
            description: Backup retention period in days.
            type: int
        geo_redundant_backup:
            description: Whether geo-redundant backup is enabled.
            type: str
        ssl_enforcement:
            description: Whether SSL enforcement is enabled.
            type: str
'''

import json
from ansible_collections.azure.azcollection.plugins.module_utils.azure_rm_common import AzureRMModuleBase


class AzureRMMariaDbServer(AzureRMModuleBase):

    def __init__(self):
        self.module_arg_spec = dict(
            resource_group=dict(type='str', required=True, aliases=['resource_group_name']),
            name=dict(type='str', required=True),
            location=dict(type='str'),
            sku_name=dict(
                type='str',
            ),
            sku_tier=dict(
                type='str',
            ),
            administrator_login=dict(
                type='str',
            ),
            administrator_login_password=dict(
                type='str',
            ),
            version=dict(
                type='str',
                choices=['10.2', '10.3'],
            ),
            storage_mb=dict(
                type='int',
            ),
            backup_retention_days=dict(
                type='int',
            ),
            geo_redundant_backup=dict(
                type='str',
                choices=['Enabled', 'Disabled'],
            ),
            ssl_enforcement=dict(
                type='str',
                choices=['Enabled', 'Disabled'],
            ),
            state=dict(type='str', default='present', choices=['present', 'absent']),
        )

        self.resource_group = None
        self.name = None
        self.location = None
        self.sku_name = None
        self.sku_tier = None
        self.administrator_login = None
        self.administrator_login_password = None
        self.version = None
        self.storage_mb = None
        self.backup_retention_days = None
        self.geo_redundant_backup = None
        self.ssl_enforcement = None
        self.state = None
        self.tags = None

        self.results = dict(changed=False, state=dict())

        required_if = [
            ('state', 'present', ['resource_group', 'name']),
        ]

        super().__init__(
            derived_arg_spec=self.module_arg_spec,
            supports_check_mode=True,
            supports_tags=True,
            required_if=required_if,
        )

    def exec_module(self, **kwargs):
        for key in list(self.module_arg_spec.keys()) + ['tags']:
            setattr(self, key, kwargs[key])

        resource_group = self.resource_group
        name = self.name

        # Get existing resource
        response = self.get_resource()

        if self.state == 'present':
            if not self.location:
                rg = self.get_resource_group(resource_group)
                self.location = rg.location

            # Build the resource body from parameters
            body = self.build_body()

            if response:
                # Check if update needed
                update_tags, new_tags = self.update_tags(response.get('tags'))
                if update_tags:
                    body['tags'] = new_tags
                    self.results['changed'] = True

                if self.check_update(response, body):
                    self.results['changed'] = True

                if self.results['changed']:
                    if not self.check_mode:
                        response = self.create_or_update(resource_group, name, body)
                else:
                    response = response
            else:
                if self.tags:
                    body['tags'] = self.tags
                if not self.check_mode:
                    response = self.create_or_update(resource_group, name, body)
                self.results['changed'] = True

        elif self.state == 'absent':
            if response:
                if not self.check_mode:
                    self.delete_resource(resource_group, name)
                self.results['changed'] = True

        if response:
            self.results['state'] = self.format_response(response)

        return self.results

    def build_body(self):
        body = dict(
            location=self.location,
        )
        if self.sku_name is not None:
            _target = body
            _target = _target.setdefault('sku', {})
            _target['name'] = self.sku_name
        if self.sku_tier is not None:
            _target = body
            _target = _target.setdefault('sku', {})
            _target['tier'] = self.sku_tier

        properties = body.setdefault('properties', {})
        if self.administrator_login is not None:
            properties['administratorLogin'] = self.administrator_login
        if self.administrator_login_password is not None:
            properties['administratorLoginPassword'] = self.administrator_login_password
        if self.version is not None:
            properties['version'] = self.version
        if self.storage_mb is not None:
            properties['storageMB'] = self.storage_mb
        if self.backup_retention_days is not None:
            properties['backupRetentionDays'] = self.backup_retention_days
        if self.geo_redundant_backup is not None:
            properties['geoRedundantBackup'] = self.geo_redundant_backup
        if self.ssl_enforcement is not None:
            properties['sslEnforcement'] = self.ssl_enforcement

        if self.tags:
            body['tags'] = self.tags

        return body

    def check_update(self, existing, desired):
        """Compare existing resource with desired state."""
        # Check sku_name
        if self.sku_name is not None:
            _existing = existing
            _existing = _existing.get('sku', {}) if isinstance(_existing, dict) else {}
            if _existing.get('name') != self.sku_name:
                return True
        # Check sku_tier
        if self.sku_tier is not None:
            _existing = existing
            _existing = _existing.get('sku', {}) if isinstance(_existing, dict) else {}
            if _existing.get('tier') != self.sku_tier:
                return True
        # Check administrator_login
        if self.administrator_login is not None:
            if existing.get('properties', {}).get('administratorLogin') != self.administrator_login:
                return True
        # Check administrator_login_password
        if self.administrator_login_password is not None:
            if existing.get('properties', {}).get('administratorLoginPassword') != self.administrator_login_password:
                return True
        # Check version
        if self.version is not None:
            if existing.get('properties', {}).get('version') != self.version:
                return True
        # Check storage_mb
        if self.storage_mb is not None:
            if existing.get('properties', {}).get('storageMB') != self.storage_mb:
                return True
        # Check backup_retention_days
        if self.backup_retention_days is not None:
            if existing.get('properties', {}).get('backupRetentionDays') != self.backup_retention_days:
                return True
        # Check geo_redundant_backup
        if self.geo_redundant_backup is not None:
            if existing.get('properties', {}).get('geoRedundantBackup') != self.geo_redundant_backup:
                return True
        # Check ssl_enforcement
        if self.ssl_enforcement is not None:
            if existing.get('properties', {}).get('sslEnforcement') != self.ssl_enforcement:
                return True

        return False

    def get_resource(self):
        try:
            url = self.get_resource_url()
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2018-06-01'},
                None, None, [200], 0, 0,
            )
            return self.deserialize_response(response)
        except Exception:
            return None

    def create_or_update(self, resource_group, name, body):
        url = self.get_resource_url()
        response = self.mgmt_client.query(
            url, "PUT",
            {'api-version': '2018-06-01'},
            None, body, [200, 201], 0, 0,
        )
        return self.deserialize_response(response)

    def delete_resource(self, resource_group, name):
        url = self.get_resource_url()
        self.mgmt_client.query(
            url, "DELETE",
            {'api-version': '2018-06-01'},
            None, None, [200, 202, 204], 0, 0,
        )

    def get_resource_url(self):
        return (
            '/subscriptions/{subscription_id}'
            '/resourceGroups/{resource_group}'
            '/providers/Microsoft.DBforMariaDB/servers/{name}'
        ).format(
            subscription_id=self.subscription_id,
            resource_group=self.resource_group,
            name=self.name,
        )

    def format_response(self, response):
        result = dict(
            id=response.get('id'),
            name=response.get('name'),
            location=response.get('location'),
            tags=response.get('tags'),
        )
        _body = response
        _body = _body.get('sku', {}) if isinstance(_body, dict) else {}
        result['sku_name'] = _body.get('name')
        _body = response
        _body = _body.get('sku', {}) if isinstance(_body, dict) else {}
        result['sku_tier'] = _body.get('tier')
        result['administrator_login'] = response.get('properties', {}).get('administratorLogin')
        result['administrator_login_password'] = response.get('properties', {}).get('administratorLoginPassword')
        result['version'] = response.get('properties', {}).get('version')
        result['storage_mb'] = response.get('properties', {}).get('storageMB')
        result['backup_retention_days'] = response.get('properties', {}).get('backupRetentionDays')
        result['geo_redundant_backup'] = response.get('properties', {}).get('geoRedundantBackup')
        result['ssl_enforcement'] = response.get('properties', {}).get('sslEnforcement')
        return result

    @staticmethod
    def deserialize_response(response):
        try:
            return json.loads(response.text)
        except (ValueError, AttributeError):
            return None


def main():
    AzureRMMariaDbServer()


if __name__ == '__main__':
    main()
