#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2024, Azure Magic Modules Generator
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Auto-generated by Azure Magic Modules — do not edit manually

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: azure_rm_keyvault
version_added: "0.1.0"
short_description: Manage Azure Key Vault instances.
description:
    - Create, update, or delete an Azure KeyVault.
    - This module was auto-generated by Azure Magic Modules.
options:
    resource_group:
        description:
            - Name of the resource group.
        type: str
        required: true
    name:
        description:
            - Name of the keyvault.
        type: str
        required: true
    location:
        description:
            - Valid Azure location. Defaults to the location of the resource group.
        type: str
    sku_name:
        description:
            - SKU name for the Key Vault.
        type: str
        required: true
        choices:
            - "standard"
            - "premium"
    tenant_id:
        description:
            - The Azure Active Directory tenant ID for the vault.
        type: str
        required: true
    enabled_for_deployment:
        description:
            - Whether VMs can retrieve certificates stored as secrets.
        type: bool
    enabled_for_disk_encryption:
        description:
            - Whether Azure Disk Encryption can retrieve secrets.
        type: bool
    enabled_for_template_deployment:
        description:
            - Whether Azure Resource Manager can retrieve secrets.
        type: bool
    enable_soft_delete:
        description:
            - Whether soft delete is enabled for the vault.
        type: bool
        default: "True"
    soft_delete_retention_in_days:
        description:
            - Number of days to retain soft-deleted vaults.
        type: int
        default: "90"
    enable_purge_protection:
        description:
            - Whether purge protection is enabled for the vault.
        type: bool
    enable_rbac_authorization:
        description:
            - Whether RBAC authorization is used for data actions.
        type: bool
    public_network_access:
        description:
            - Whether the vault accepts traffic from public networks.
        type: str
        choices:
            - "Enabled"
            - "Disabled"
    network_acls_default_action:
        description:
            - Default action for network ACLs.
        type: str
        choices:
            - "Allow"
            - "Deny"
    state:
        description:
            - Assert the state of the keyvault.
            - Use C(present) to create or update and C(absent) to delete.
        type: str
        default: present
        choices:
            - present
            - absent
extends_documentation_fragment:
    - azure.azcollection.azure
    - azure.azcollection.azure_tags
author:
    - "Azure Magic Modules Generator (@azure-magic-modules)"
seealso:
    - description: Azure KeyVault REST API
      link: https://learn.microsoft.com/en-us/azure/key-vault/
'''

EXAMPLES = r'''
- name: Create KeyVault
  azure_rm_keyvault:
    resource_group: myResourceGroup
    name: myKeyVault
    location: eastus
    sku_name: "example_value"
    tenant_id: "example_value"
    state: present

- name: Delete KeyVault
  azure_rm_keyvault:
    resource_group: myResourceGroup
    name: myKeyVault
    state: absent
'''

RETURN = r'''
state:
    description: Current state of the keyvault.
    returned: always
    type: dict
    contains:
        id:
            description: Resource ID.
            type: str
        name:
            description: Resource name.
            type: str
        location:
            description: Resource location.
            type: str
        tags:
            description: Resource tags.
            type: dict
        sku_name:
            description: SKU name for the Key Vault.
            type: str
        tenant_id:
            description: The Azure Active Directory tenant ID for the vault.
            type: str
        enabled_for_deployment:
            description: Whether VMs can retrieve certificates stored as secrets.
            type: bool
        enabled_for_disk_encryption:
            description: Whether Azure Disk Encryption can retrieve secrets.
            type: bool
        enabled_for_template_deployment:
            description: Whether Azure Resource Manager can retrieve secrets.
            type: bool
        enable_soft_delete:
            description: Whether soft delete is enabled for the vault.
            type: bool
        soft_delete_retention_in_days:
            description: Number of days to retain soft-deleted vaults.
            type: int
        enable_purge_protection:
            description: Whether purge protection is enabled for the vault.
            type: bool
        enable_rbac_authorization:
            description: Whether RBAC authorization is used for data actions.
            type: bool
        public_network_access:
            description: Whether the vault accepts traffic from public networks.
            type: str
        network_acls_default_action:
            description: Default action for network ACLs.
            type: str
'''

import json
from ansible_collections.azure.azcollection.plugins.module_utils.azure_rm_common import AzureRMModuleBase


class AzureRMKeyVault(AzureRMModuleBase):

    def __init__(self):
        self.module_arg_spec = dict(
            resource_group=dict(type='str', required=True, aliases=['resource_group_name']),
            name=dict(type='str', required=True),
            location=dict(type='str'),
            sku_name=dict(
                type='str',
                required=True,
                choices=['standard', 'premium'],
            ),
            tenant_id=dict(
                type='str',
                required=True,
            ),
            enabled_for_deployment=dict(
                type='bool',
            ),
            enabled_for_disk_encryption=dict(
                type='bool',
            ),
            enabled_for_template_deployment=dict(
                type='bool',
            ),
            enable_soft_delete=dict(
                type='bool',
                default=True,
            ),
            soft_delete_retention_in_days=dict(
                type='int',
                default=90,
            ),
            enable_purge_protection=dict(
                type='bool',
            ),
            enable_rbac_authorization=dict(
                type='bool',
            ),
            public_network_access=dict(
                type='str',
                choices=['Enabled', 'Disabled'],
            ),
            network_acls_default_action=dict(
                type='str',
                choices=['Allow', 'Deny'],
            ),
            state=dict(type='str', default='present', choices=['present', 'absent']),
        )

        self.resource_group = None
        self.name = None
        self.location = None
        self.sku_name = None
        self.tenant_id = None
        self.enabled_for_deployment = None
        self.enabled_for_disk_encryption = None
        self.enabled_for_template_deployment = None
        self.enable_soft_delete = None
        self.soft_delete_retention_in_days = None
        self.enable_purge_protection = None
        self.enable_rbac_authorization = None
        self.public_network_access = None
        self.network_acls_default_action = None
        self.state = None
        self.tags = None

        self.results = dict(changed=False, state=dict())

        required_if = [
            ('state', 'present', ['resource_group', 'name']),
        ]

        super().__init__(
            derived_arg_spec=self.module_arg_spec,
            supports_check_mode=True,
            supports_tags=True,
            required_if=required_if,
        )

    def exec_module(self, **kwargs):
        for key in list(self.module_arg_spec.keys()) + ['tags']:
            setattr(self, key, kwargs[key])

        resource_group = self.resource_group
        name = self.name

        # Get existing resource
        response = self.get_resource()

        if self.state == 'present':
            if not self.location:
                rg = self.get_resource_group(resource_group)
                self.location = rg.location

            # Build the resource body from parameters
            body = self.build_body()

            if response:
                # Check if update needed
                update_tags, new_tags = self.update_tags(response.get('tags'))
                if update_tags:
                    body['tags'] = new_tags
                    self.results['changed'] = True

                if self.check_update(response, body):
                    self.results['changed'] = True

                if self.results['changed']:
                    if not self.check_mode:
                        response = self.create_or_update(resource_group, name, body)
                else:
                    response = response
            else:
                if self.tags:
                    body['tags'] = self.tags
                if not self.check_mode:
                    response = self.create_or_update(resource_group, name, body)
                self.results['changed'] = True

        elif self.state == 'absent':
            if response:
                if not self.check_mode:
                    self.delete_resource(resource_group, name)
                self.results['changed'] = True

        if response:
            self.results['state'] = self.format_response(response)

        return self.results

    def build_body(self):
        body = dict(
            location=self.location,
        )

        properties = body.setdefault('properties', {})
        if self.sku_name is not None:
            _target = properties
            _target = _target.setdefault('sku', {})
            _target['name'] = self.sku_name
        if self.tenant_id is not None:
            properties['tenantId'] = self.tenant_id
        if self.enabled_for_deployment is not None:
            properties['enabledForDeployment'] = self.enabled_for_deployment
        if self.enabled_for_disk_encryption is not None:
            properties['enabledForDiskEncryption'] = self.enabled_for_disk_encryption
        if self.enabled_for_template_deployment is not None:
            properties['enabledForTemplateDeployment'] = self.enabled_for_template_deployment
        if self.enable_soft_delete is not None:
            properties['enableSoftDelete'] = self.enable_soft_delete
        if self.soft_delete_retention_in_days is not None:
            properties['softDeleteRetentionInDays'] = self.soft_delete_retention_in_days
        if self.enable_purge_protection is not None:
            properties['enablePurgeProtection'] = self.enable_purge_protection
        if self.enable_rbac_authorization is not None:
            properties['enableRbacAuthorization'] = self.enable_rbac_authorization
        if self.public_network_access is not None:
            properties['publicNetworkAccess'] = self.public_network_access
        if self.network_acls_default_action is not None:
            _target = properties
            _target = _target.setdefault('networkAcls', {})
            _target['defaultAction'] = self.network_acls_default_action

        if self.tags:
            body['tags'] = self.tags

        return body

    def check_update(self, existing, desired):
        """Compare existing resource with desired state."""
        # Check sku_name
        if self.sku_name is not None:
            _existing = existing.get('properties', {})
            _existing = _existing.get('sku', {}) if isinstance(_existing, dict) else {}
            if _existing.get('name') != self.sku_name:
                return True
        # Check tenant_id
        if self.tenant_id is not None:
            if existing.get('properties', {}).get('tenantId') != self.tenant_id:
                return True
        # Check enabled_for_deployment
        if self.enabled_for_deployment is not None:
            if existing.get('properties', {}).get('enabledForDeployment') != self.enabled_for_deployment:
                return True
        # Check enabled_for_disk_encryption
        if self.enabled_for_disk_encryption is not None:
            if existing.get('properties', {}).get('enabledForDiskEncryption') != self.enabled_for_disk_encryption:
                return True
        # Check enabled_for_template_deployment
        if self.enabled_for_template_deployment is not None:
            if existing.get('properties', {}).get('enabledForTemplateDeployment') != self.enabled_for_template_deployment:
                return True
        # Check enable_soft_delete
        if self.enable_soft_delete is not None:
            if existing.get('properties', {}).get('enableSoftDelete') != self.enable_soft_delete:
                return True
        # Check soft_delete_retention_in_days
        if self.soft_delete_retention_in_days is not None:
            if existing.get('properties', {}).get('softDeleteRetentionInDays') != self.soft_delete_retention_in_days:
                return True
        # Check enable_purge_protection
        if self.enable_purge_protection is not None:
            if existing.get('properties', {}).get('enablePurgeProtection') != self.enable_purge_protection:
                return True
        # Check enable_rbac_authorization
        if self.enable_rbac_authorization is not None:
            if existing.get('properties', {}).get('enableRbacAuthorization') != self.enable_rbac_authorization:
                return True
        # Check public_network_access
        if self.public_network_access is not None:
            if existing.get('properties', {}).get('publicNetworkAccess') != self.public_network_access:
                return True
        # Check network_acls_default_action
        if self.network_acls_default_action is not None:
            _existing = existing.get('properties', {})
            _existing = _existing.get('networkAcls', {}) if isinstance(_existing, dict) else {}
            if _existing.get('defaultAction') != self.network_acls_default_action:
                return True

        return False

    def get_resource(self):
        try:
            url = self.get_resource_url()
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2023-07-01'},
                None, None, [200], 0, 0,
            )
            return self.deserialize_response(response)
        except Exception:
            return None

    def create_or_update(self, resource_group, name, body):
        url = self.get_resource_url()
        response = self.mgmt_client.query(
            url, "PUT",
            {'api-version': '2023-07-01'},
            None, body, [200, 201], 0, 0,
        )
        return self.deserialize_response(response)

    def delete_resource(self, resource_group, name):
        url = self.get_resource_url()
        self.mgmt_client.query(
            url, "DELETE",
            {'api-version': '2023-07-01'},
            None, None, [200, 202, 204], 0, 0,
        )

    def get_resource_url(self):
        return (
            '/subscriptions/{subscription_id}'
            '/resourceGroups/{resource_group}'
            '/providers/Microsoft.KeyVault/vaults/{name}'
        ).format(
            subscription_id=self.subscription_id,
            resource_group=self.resource_group,
            name=self.name,
        )

    def format_response(self, response):
        result = dict(
            id=response.get('id'),
            name=response.get('name'),
            location=response.get('location'),
            tags=response.get('tags'),
        )
        _props = response.get('properties', {})
        _props = _props.get('sku', {}) if isinstance(_props, dict) else {}
        result['sku_name'] = _props.get('name')
        result['tenant_id'] = response.get('properties', {}).get('tenantId')
        result['enabled_for_deployment'] = response.get('properties', {}).get('enabledForDeployment')
        result['enabled_for_disk_encryption'] = response.get('properties', {}).get('enabledForDiskEncryption')
        result['enabled_for_template_deployment'] = response.get('properties', {}).get('enabledForTemplateDeployment')
        result['enable_soft_delete'] = response.get('properties', {}).get('enableSoftDelete')
        result['soft_delete_retention_in_days'] = response.get('properties', {}).get('softDeleteRetentionInDays')
        result['enable_purge_protection'] = response.get('properties', {}).get('enablePurgeProtection')
        result['enable_rbac_authorization'] = response.get('properties', {}).get('enableRbacAuthorization')
        result['public_network_access'] = response.get('properties', {}).get('publicNetworkAccess')
        _props = response.get('properties', {})
        _props = _props.get('networkAcls', {}) if isinstance(_props, dict) else {}
        result['network_acls_default_action'] = _props.get('defaultAction')
        return result

    @staticmethod
    def deserialize_response(response):
        try:
            return json.loads(response.text)
        except (ValueError, AttributeError):
            return None


def main():
    AzureRMKeyVault()


if __name__ == '__main__':
    main()
