#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2024, Azure Magic Modules Generator
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Auto-generated by Azure Magic Modules — do not edit manually

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: azure_rm_subnet
version_added: "0.1.0"
short_description: Manage Azure virtual network subnets.
description:
    - Create, update, or delete an Azure Subnet.
    - This module was auto-generated by Azure Magic Modules.
options:
    resource_group:
        description:
            - Name of the resource group.
        type: str
        required: true
    name:
        description:
            - Name of the subnet.
        type: str
        required: true
    location:
        description:
            - Valid Azure location. Defaults to the location of the resource group.
        type: str
    virtual_network_name:
        description:
            - Name of the virtual network containing the subnet.
        type: str
        required: true
    address_prefix:
        description:
            - Address prefix in CIDR notation for the subnet.
        type: str
        required: true
    network_security_group_id:
        description:
            - Resource ID of the network security group to associate.
        type: str
    route_table_id:
        description:
            - Resource ID of the route table to associate.
        type: str
    service_endpoints:
        description:
            - List of service endpoint strings.
        type: list
    private_endpoint_network_policies:
        description:
            - Enable or disable private endpoint network policies.
        type: str
        choices:
            - "Enabled"
            - "Disabled"
    delegation_name:
        description:
            - Name of the delegation.
        type: str
    delegation_service_name:
        description:
            - Service name for the delegation.
        type: str
    state:
        description:
            - Assert the state of the subnet.
            - Use C(present) to create or update and C(absent) to delete.
        type: str
        default: present
        choices:
            - present
            - absent
extends_documentation_fragment:
    - azure.azcollection.azure
    - azure.azcollection.azure_tags
author:
    - "Azure Magic Modules Generator (@azure-magic-modules)"
seealso:
    - description: Azure Subnet REST API
      link: https://learn.microsoft.com/en-us/azure/virtual-network/manage-subnet-delegation
'''

EXAMPLES = r'''
- name: Create Subnet
  azure_rm_subnet:
    resource_group: myResourceGroup
    name: mySubnet
    location: eastus
    virtual_network_name: "example_value"
    address_prefix: "example_value"
    state: present

- name: Delete Subnet
  azure_rm_subnet:
    resource_group: myResourceGroup
    name: mySubnet
    state: absent
'''

RETURN = r'''
state:
    description: Current state of the subnet.
    returned: always
    type: dict
    contains:
        id:
            description: Resource ID.
            type: str
        name:
            description: Resource name.
            type: str
        location:
            description: Resource location.
            type: str
        tags:
            description: Resource tags.
            type: dict
        virtual_network_name:
            description: Name of the virtual network containing the subnet.
            type: str
        address_prefix:
            description: Address prefix in CIDR notation for the subnet.
            type: str
        network_security_group_id:
            description: Resource ID of the network security group to associate.
            type: str
        route_table_id:
            description: Resource ID of the route table to associate.
            type: str
        service_endpoints:
            description: List of service endpoint strings.
            type: list
        private_endpoint_network_policies:
            description: Enable or disable private endpoint network policies.
            type: str
        delegation_name:
            description: Name of the delegation.
            type: str
        delegation_service_name:
            description: Service name for the delegation.
            type: str
'''

import json
from ansible_collections.azure.azcollection.plugins.module_utils.azure_rm_common import AzureRMModuleBase


class AzureRMSubnet(AzureRMModuleBase):

    def __init__(self):
        self.module_arg_spec = dict(
            resource_group=dict(type='str', required=True, aliases=['resource_group_name']),
            name=dict(type='str', required=True),
            location=dict(type='str'),
            virtual_network_name=dict(
                type='str',
                required=True,
            ),
            address_prefix=dict(
                type='str',
                required=True,
            ),
            network_security_group_id=dict(
                type='str',
            ),
            route_table_id=dict(
                type='str',
            ),
            service_endpoints=dict(
                type='list',
            ),
            private_endpoint_network_policies=dict(
                type='str',
                choices=['Enabled', 'Disabled'],
            ),
            delegation_name=dict(
                type='str',
            ),
            delegation_service_name=dict(
                type='str',
            ),
            state=dict(type='str', default='present', choices=['present', 'absent']),
        )

        self.resource_group = None
        self.name = None
        self.location = None
        self.virtual_network_name = None
        self.address_prefix = None
        self.network_security_group_id = None
        self.route_table_id = None
        self.service_endpoints = None
        self.private_endpoint_network_policies = None
        self.delegation_name = None
        self.delegation_service_name = None
        self.state = None
        self.tags = None

        self.results = dict(changed=False, state=dict())

        required_if = [
            ('state', 'present', ['resource_group', 'name']),
        ]

        super().__init__(
            derived_arg_spec=self.module_arg_spec,
            supports_check_mode=True,
            supports_tags=True,
            required_if=required_if,
        )

    def exec_module(self, **kwargs):
        for key in list(self.module_arg_spec.keys()) + ['tags']:
            setattr(self, key, kwargs[key])

        resource_group = self.resource_group
        name = self.name

        # Get existing resource
        response = self.get_resource()

        if self.state == 'present':
            if not self.location:
                rg = self.get_resource_group(resource_group)
                self.location = rg.location

            # Build the resource body from parameters
            body = self.build_body()

            if response:
                # Check if update needed
                update_tags, new_tags = self.update_tags(response.get('tags'))
                if update_tags:
                    body['tags'] = new_tags
                    self.results['changed'] = True

                if self.check_update(response, body):
                    self.results['changed'] = True

                if self.results['changed']:
                    if not self.check_mode:
                        response = self.create_or_update(resource_group, name, body)
                else:
                    response = response
            else:
                if self.tags:
                    body['tags'] = self.tags
                if not self.check_mode:
                    response = self.create_or_update(resource_group, name, body)
                self.results['changed'] = True

        elif self.state == 'absent':
            if response:
                if not self.check_mode:
                    self.delete_resource(resource_group, name)
                self.results['changed'] = True

        if response:
            self.results['state'] = self.format_response(response)

        return self.results

    def build_body(self):
        body = dict(
            location=self.location,
        )
        if self.virtual_network_name is not None:
            body['virtualNetworkName'] = self.virtual_network_name
        if self.address_prefix is not None:
            body['addressPrefix'] = self.address_prefix
        if self.network_security_group_id is not None:
            _target = body
            _target = _target.setdefault('networkSecurityGroup', {})
            _target['id'] = self.network_security_group_id
        if self.route_table_id is not None:
            _target = body
            _target = _target.setdefault('routeTable', {})
            _target['id'] = self.route_table_id
        if self.service_endpoints is not None:
            body['serviceEndpoints'] = self.service_endpoints
        if self.private_endpoint_network_policies is not None:
            body['privateEndpointNetworkPolicies'] = self.private_endpoint_network_policies
        if self.delegation_name is not None:
            _target = body
            _target = _target.setdefault('delegations[0]', {})
            _target['name'] = self.delegation_name
        if self.delegation_service_name is not None:
            _target = body
            _target = _target.setdefault('delegations[0]', {})
            _target['serviceName'] = self.delegation_service_name

        if self.tags:
            body['tags'] = self.tags

        return body

    def check_update(self, existing, desired):
        """Compare existing resource with desired state."""
        # Check virtual_network_name
        if self.virtual_network_name is not None:
            if existing.get('virtualNetworkName') != self.virtual_network_name:
                return True
        # Check address_prefix
        if self.address_prefix is not None:
            if existing.get('addressPrefix') != self.address_prefix:
                return True
        # Check network_security_group_id
        if self.network_security_group_id is not None:
            _existing = existing
            _existing = _existing.get('networkSecurityGroup', {}) if isinstance(_existing, dict) else {}
            if _existing.get('id') != self.network_security_group_id:
                return True
        # Check route_table_id
        if self.route_table_id is not None:
            _existing = existing
            _existing = _existing.get('routeTable', {}) if isinstance(_existing, dict) else {}
            if _existing.get('id') != self.route_table_id:
                return True
        # Check service_endpoints
        if self.service_endpoints is not None:
            if existing.get('serviceEndpoints') != self.service_endpoints:
                return True
        # Check private_endpoint_network_policies
        if self.private_endpoint_network_policies is not None:
            if existing.get('privateEndpointNetworkPolicies') != self.private_endpoint_network_policies:
                return True
        # Check delegation_name
        if self.delegation_name is not None:
            _existing = existing
            _existing = _existing.get('delegations[0]', {}) if isinstance(_existing, dict) else {}
            if _existing.get('name') != self.delegation_name:
                return True
        # Check delegation_service_name
        if self.delegation_service_name is not None:
            _existing = existing
            _existing = _existing.get('delegations[0]', {}) if isinstance(_existing, dict) else {}
            if _existing.get('serviceName') != self.delegation_service_name:
                return True

        return False

    def get_resource(self):
        try:
            url = self.get_resource_url()
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2024-03-01'},
                None, None, [200], 0, 0,
            )
            return self.deserialize_response(response)
        except Exception:
            return None

    def create_or_update(self, resource_group, name, body):
        url = self.get_resource_url()
        response = self.mgmt_client.query(
            url, "PUT",
            {'api-version': '2024-03-01'},
            None, body, [200, 201], 0, 0,
        )
        return self.deserialize_response(response)

    def delete_resource(self, resource_group, name):
        url = self.get_resource_url()
        self.mgmt_client.query(
            url, "DELETE",
            {'api-version': '2024-03-01'},
            None, None, [200, 202, 204], 0, 0,
        )

    def get_resource_url(self):
        return (
            '/subscriptions/{subscription_id}'
            '/resourceGroups/{resource_group}'
            '/providers/Microsoft.Network/virtualNetworks/subnets/{name}'
        ).format(
            subscription_id=self.subscription_id,
            resource_group=self.resource_group,
            name=self.name,
        )

    def format_response(self, response):
        result = dict(
            id=response.get('id'),
            name=response.get('name'),
            location=response.get('location'),
            tags=response.get('tags'),
        )
        result['virtual_network_name'] = response.get('virtualNetworkName')
        result['address_prefix'] = response.get('addressPrefix')
        _body = response
        _body = _body.get('networkSecurityGroup', {}) if isinstance(_body, dict) else {}
        result['network_security_group_id'] = _body.get('id')
        _body = response
        _body = _body.get('routeTable', {}) if isinstance(_body, dict) else {}
        result['route_table_id'] = _body.get('id')
        result['service_endpoints'] = response.get('serviceEndpoints')
        result['private_endpoint_network_policies'] = response.get('privateEndpointNetworkPolicies')
        _body = response
        _body = _body.get('delegations[0]', {}) if isinstance(_body, dict) else {}
        result['delegation_name'] = _body.get('name')
        _body = response
        _body = _body.get('delegations[0]', {}) if isinstance(_body, dict) else {}
        result['delegation_service_name'] = _body.get('serviceName')
        return result

    @staticmethod
    def deserialize_response(response):
        try:
            return json.loads(response.text)
        except (ValueError, AttributeError):
            return None


def main():
    AzureRMSubnet()


if __name__ == '__main__':
    main()
