#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2024, Azure Magic Modules Generator
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Auto-generated by Azure Magic Modules — do not edit manually

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: azure_rm_storagecontainer_info
version_added: "0.1.0"
short_description: Get facts for Azure StorageContainer
description:
    - Get facts for a specific StorageContainer or list all StorageContainers in a resource group.
    - This module was auto-generated by Azure Magic Modules.
options:
    resource_group:
        description:
            - Name of the resource group.
        type: str
        required: true
    name:
        description:
            - Name of the storagecontainer.
            - If not specified, all storagecontainers in the resource group will be listed.
        type: str
extends_documentation_fragment:
    - azure.azcollection.azure
    - azure.azcollection.azure_tags
author:
    - "Azure Magic Modules Generator (@azure-magic-modules)"
seealso:
    - description: Azure StorageContainer REST API
      link: https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blobs-introduction
'''

EXAMPLES = r'''
- name: Get facts for a specific StorageContainer
  azure_rm_storagecontainer_info:
    resource_group: myResourceGroup
    name: myStorageContainer

- name: List all StorageContainers in a resource group
  azure_rm_storagecontainer_info:
    resource_group: myResourceGroup
'''

RETURN = r'''
storagecontainers:
    description:
        - List of storagecontainer dicts.
    returned: always
    type: list
    elements: dict
    contains:
        id:
            description: Resource ID.
            type: str
        name:
            description: Resource name.
            type: str
        location:
            description: Resource location.
            type: str
        tags:
            description: Resource tags.
            type: dict
        account_name:
            description: Name of the storage account.
            type: str
        public_access:
            description: Level of public access to the container.
            type: str
        default_encryption_scope:
            description: Default encryption scope for the container.
            type: str
        deny_encryption_scope_override:
            description: Whether to deny encryption scope override.
            type: bool
        immutable_storage_with_versioning_enabled:
            description: Whether immutable storage with versioning is enabled.
            type: bool
'''

import json
from ansible_collections.azure.azcollection.plugins.module_utils.azure_rm_common import AzureRMModuleBase


class AzureRMStorageContainerInfo(AzureRMModuleBase):

    def __init__(self):
        self.module_arg_spec = dict(
            resource_group=dict(type='str', required=True, aliases=['resource_group_name']),
            name=dict(type='str'),
        )

        self.resource_group = None
        self.name = None
        self.tags = None

        self.results = dict(
            changed=False,
            storagecontainers=[],
        )

        super().__init__(
            derived_arg_spec=self.module_arg_spec,
            supports_check_mode=True,
            supports_tags=False,
            facts_module=True,
        )

    def exec_module(self, **kwargs):
        for key in list(self.module_arg_spec.keys()) + ['tags']:
            setattr(self, key, kwargs[key])

        result_key = 'storagecontainers'

        if self.name:
            response = self.get_resource()
            if response:
                if self.has_tags(response.get('tags'), self.tags):
                    self.results[result_key] = [self.format_response(response)]
        else:
            responses = self.list_by_resource_group()
            for item in responses:
                if self.has_tags(item.get('tags'), self.tags):
                    self.results[result_key].append(self.format_response(item))

        return self.results

    def get_resource(self):
        try:
            url = (
                '/subscriptions/{subscription_id}'
                '/resourceGroups/{resource_group}'
                '/providers/Microsoft.Storage/storageAccounts/blobServices/containers/{name}'
            ).format(
                subscription_id=self.subscription_id,
                resource_group=self.resource_group,
                name=self.name,
            )
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2023-05-01'},
                None, None, [200], 0, 0,
            )
            return self.deserialize_response(response)
        except Exception:
            return None

    def list_by_resource_group(self):
        try:
            url = (
                '/subscriptions/{subscription_id}'
                '/resourceGroups/{resource_group}'
                '/providers/Microsoft.Storage/storageAccounts/blobServices/containers'
            ).format(
                subscription_id=self.subscription_id,
                resource_group=self.resource_group,
            )
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2023-05-01'},
                None, None, [200], 0, 0,
            )
            result = self.deserialize_response(response)
            if result and isinstance(result, dict):
                return result.get('value', [])
            return []
        except Exception:
            return []

    def format_response(self, response):
        result = dict(
            id=response.get('id'),
            name=response.get('name'),
            location=response.get('location'),
            tags=response.get('tags'),
        )
        result['account_name'] = response.get('AccountName')
        result['public_access'] = response.get('publicAccess')
        result['default_encryption_scope'] = response.get('defaultEncryptionScope')
        result['deny_encryption_scope_override'] = response.get('denyEncryptionScopeOverride')
        _body = response
        _body = _body.get('immutableStorageWithVersioning', {}) if isinstance(_body, dict) else {}
        result['immutable_storage_with_versioning_enabled'] = _body.get('enabled')
        return result

    @staticmethod
    def deserialize_response(response):
        try:
            return json.loads(response.text)
        except (ValueError, AttributeError):
            return None


def main():
    AzureRMStorageContainerInfo()


if __name__ == '__main__':
    main()
