#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2024, Azure Magic Modules Generator
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Auto-generated by Azure Magic Modules — do not edit manually

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: azure_rm_image
version_added: "0.1.0"
short_description: Manage Azure custom image instances.
description:
    - Create, update, or delete an Azure Image.
    - This module was auto-generated by Azure Magic Modules.
options:
    resource_group:
        description:
            - Name of the resource group.
        type: str
        required: true
    name:
        description:
            - Name of the image.
        type: str
        required: true
    location:
        description:
            - Valid Azure location. Defaults to the location of the resource group.
        type: str
    source_virtual_machine_id:
        description:
            - Resource ID of the source virtual machine.
        type: str
    os_type:
        description:
            - Operating system type of the image.
        type: str
        choices:
            - "Linux"
            - "Windows"
    os_state:
        description:
            - Operating system state of the image.
        type: str
        choices:
            - "Generalized"
            - "Specialized"
    os_disk_blob_uri:
        description:
            - URI of the OS disk blob.
        type: str
    hyper_v_generation:
        description:
            - Hyper-V generation of the virtual machine.
        type: str
        choices:
            - "V1"
            - "V2"
    state:
        description:
            - Assert the state of the image.
            - Use C(present) to create or update and C(absent) to delete.
        type: str
        default: present
        choices:
            - present
            - absent
extends_documentation_fragment:
    - azure.azcollection.azure
    - azure.azcollection.azure_tags
author:
    - "Azure Magic Modules Generator (@azure-magic-modules)"
seealso:
    - description: Azure Image REST API
      link: https://learn.microsoft.com/en-us/azure/virtual-machines/image-version
'''

EXAMPLES = r'''
- name: Create Image
  azure_rm_image:
    resource_group: myResourceGroup
    name: myImage
    location: eastus
    state: present

- name: Delete Image
  azure_rm_image:
    resource_group: myResourceGroup
    name: myImage
    state: absent
'''

RETURN = r'''
state:
    description: Current state of the image.
    returned: always
    type: dict
    contains:
        id:
            description: Resource ID.
            type: str
        name:
            description: Resource name.
            type: str
        location:
            description: Resource location.
            type: str
        tags:
            description: Resource tags.
            type: dict
        source_virtual_machine_id:
            description: Resource ID of the source virtual machine.
            type: str
        os_type:
            description: Operating system type of the image.
            type: str
        os_state:
            description: Operating system state of the image.
            type: str
        os_disk_blob_uri:
            description: URI of the OS disk blob.
            type: str
        hyper_v_generation:
            description: Hyper-V generation of the virtual machine.
            type: str
'''

import json
from ansible_collections.azure.azcollection.plugins.module_utils.azure_rm_common import AzureRMModuleBase


class AzureRMImage(AzureRMModuleBase):

    def __init__(self):
        self.module_arg_spec = dict(
            resource_group=dict(type='str', required=True, aliases=['resource_group_name']),
            name=dict(type='str', required=True),
            location=dict(type='str'),
            source_virtual_machine_id=dict(
                type='str',
            ),
            os_type=dict(
                type='str',
                choices=['Linux', 'Windows'],
            ),
            os_state=dict(
                type='str',
                choices=['Generalized', 'Specialized'],
            ),
            os_disk_blob_uri=dict(
                type='str',
            ),
            hyper_v_generation=dict(
                type='str',
                choices=['V1', 'V2'],
            ),
            state=dict(type='str', default='present', choices=['present', 'absent']),
        )

        self.resource_group = None
        self.name = None
        self.location = None
        self.source_virtual_machine_id = None
        self.os_type = None
        self.os_state = None
        self.os_disk_blob_uri = None
        self.hyper_v_generation = None
        self.state = None
        self.tags = None

        self.results = dict(changed=False, state=dict())

        required_if = [
            ('state', 'present', ['resource_group', 'name']),
        ]

        super().__init__(
            derived_arg_spec=self.module_arg_spec,
            supports_check_mode=True,
            supports_tags=True,
            required_if=required_if,
        )

    def exec_module(self, **kwargs):
        for key in list(self.module_arg_spec.keys()) + ['tags']:
            setattr(self, key, kwargs[key])

        resource_group = self.resource_group
        name = self.name

        # Get existing resource
        response = self.get_resource()

        if self.state == 'present':
            if not self.location:
                rg = self.get_resource_group(resource_group)
                self.location = rg.location

            # Build the resource body from parameters
            body = self.build_body()

            if response:
                # Check if update needed
                update_tags, new_tags = self.update_tags(response.get('tags'))
                if update_tags:
                    body['tags'] = new_tags
                    self.results['changed'] = True

                if self.check_update(response, body):
                    self.results['changed'] = True

                if self.results['changed']:
                    if not self.check_mode:
                        response = self.create_or_update(resource_group, name, body)
                else:
                    response = response
            else:
                if self.tags:
                    body['tags'] = self.tags
                if not self.check_mode:
                    response = self.create_or_update(resource_group, name, body)
                self.results['changed'] = True

        elif self.state == 'absent':
            if response:
                if not self.check_mode:
                    self.delete_resource(resource_group, name)
                self.results['changed'] = True

        if response:
            self.results['state'] = self.format_response(response)

        return self.results

    def build_body(self):
        body = dict(
            location=self.location,
        )
        if self.source_virtual_machine_id is not None:
            _target = body
            _target = _target.setdefault('sourceVirtualMachine', {})
            _target['id'] = self.source_virtual_machine_id
        if self.os_type is not None:
            _target = body
            _target = _target.setdefault('storageProfile', {})
            _target = _target.setdefault('osDisk', {})
            _target['osType'] = self.os_type
        if self.os_state is not None:
            _target = body
            _target = _target.setdefault('storageProfile', {})
            _target = _target.setdefault('osDisk', {})
            _target['osState'] = self.os_state
        if self.os_disk_blob_uri is not None:
            _target = body
            _target = _target.setdefault('storageProfile', {})
            _target = _target.setdefault('osDisk', {})
            _target['blobUri'] = self.os_disk_blob_uri
        if self.hyper_v_generation is not None:
            body['hyperVGeneration'] = self.hyper_v_generation

        if self.tags:
            body['tags'] = self.tags

        return body

    def check_update(self, existing, desired):
        """Compare existing resource with desired state."""
        # Check source_virtual_machine_id
        if self.source_virtual_machine_id is not None:
            _existing = existing
            _existing = _existing.get('sourceVirtualMachine', {}) if isinstance(_existing, dict) else {}
            if _existing.get('id') != self.source_virtual_machine_id:
                return True
        # Check os_type
        if self.os_type is not None:
            _existing = existing
            _existing = _existing.get('storageProfile', {}) if isinstance(_existing, dict) else {}
            _existing = _existing.get('osDisk', {}) if isinstance(_existing, dict) else {}
            if _existing.get('osType') != self.os_type:
                return True
        # Check os_state
        if self.os_state is not None:
            _existing = existing
            _existing = _existing.get('storageProfile', {}) if isinstance(_existing, dict) else {}
            _existing = _existing.get('osDisk', {}) if isinstance(_existing, dict) else {}
            if _existing.get('osState') != self.os_state:
                return True
        # Check os_disk_blob_uri
        if self.os_disk_blob_uri is not None:
            _existing = existing
            _existing = _existing.get('storageProfile', {}) if isinstance(_existing, dict) else {}
            _existing = _existing.get('osDisk', {}) if isinstance(_existing, dict) else {}
            if _existing.get('blobUri') != self.os_disk_blob_uri:
                return True
        # Check hyper_v_generation
        if self.hyper_v_generation is not None:
            if existing.get('hyperVGeneration') != self.hyper_v_generation:
                return True

        return False

    def get_resource(self):
        try:
            url = self.get_resource_url()
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2024-03-01'},
                None, None, [200], 0, 0,
            )
            return self.deserialize_response(response)
        except Exception:
            return None

    def create_or_update(self, resource_group, name, body):
        url = self.get_resource_url()
        response = self.mgmt_client.query(
            url, "PUT",
            {'api-version': '2024-03-01'},
            None, body, [200, 201], 0, 0,
        )
        return self.deserialize_response(response)

    def delete_resource(self, resource_group, name):
        url = self.get_resource_url()
        self.mgmt_client.query(
            url, "DELETE",
            {'api-version': '2024-03-01'},
            None, None, [200, 202, 204], 0, 0,
        )

    def get_resource_url(self):
        return (
            '/subscriptions/{subscription_id}'
            '/resourceGroups/{resource_group}'
            '/providers/Microsoft.Compute/images/{name}'
        ).format(
            subscription_id=self.subscription_id,
            resource_group=self.resource_group,
            name=self.name,
        )

    def format_response(self, response):
        result = dict(
            id=response.get('id'),
            name=response.get('name'),
            location=response.get('location'),
            tags=response.get('tags'),
        )
        _body = response
        _body = _body.get('sourceVirtualMachine', {}) if isinstance(_body, dict) else {}
        result['source_virtual_machine_id'] = _body.get('id')
        _body = response
        _body = _body.get('storageProfile', {}) if isinstance(_body, dict) else {}
        _body = _body.get('osDisk', {}) if isinstance(_body, dict) else {}
        result['os_type'] = _body.get('osType')
        _body = response
        _body = _body.get('storageProfile', {}) if isinstance(_body, dict) else {}
        _body = _body.get('osDisk', {}) if isinstance(_body, dict) else {}
        result['os_state'] = _body.get('osState')
        _body = response
        _body = _body.get('storageProfile', {}) if isinstance(_body, dict) else {}
        _body = _body.get('osDisk', {}) if isinstance(_body, dict) else {}
        result['os_disk_blob_uri'] = _body.get('blobUri')
        result['hyper_v_generation'] = response.get('hyperVGeneration')
        return result

    @staticmethod
    def deserialize_response(response):
        try:
            return json.loads(response.text)
        except (ValueError, AttributeError):
            return None


def main():
    AzureRMImage()


if __name__ == '__main__':
    main()
