#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2024, Azure Magic Modules Generator
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Auto-generated by Azure Magic Modules — do not edit manually

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: azure_rm_storageaccount
version_added: "0.1.0"
short_description: Manage Azure storage accounts
description:
    - Create, update, or delete an Azure StorageAccount.
    - This module was auto-generated by Azure Magic Modules.
options:
    resource_group:
        description:
            - Name of the resource group.
        type: str
        required: true
    name:
        description:
            - Name of the storageaccount.
        type: str
        required: true
    location:
        description:
            - Valid Azure location. Defaults to the location of the resource group.
        type: str
    account_type:
        description:
            - The SKU name for the storage account, determining replication strategy.
        type: str
        required: true
        choices:
            - "Standard_LRS"
            - "Standard_GRS"
            - "Standard_RAGRS"
            - "Premium_LRS"
            - "Standard_ZRS"
    kind:
        description:
            - The kind of storage account.
        type: str
        default: "StorageV2"
        choices:
            - "Storage"
            - "StorageV2"
            - "BlobStorage"
    access_tier:
        description:
            - The access tier used for billing. Required for BlobStorage kind.
        type: str
        choices:
            - "Hot"
            - "Cool"
    https_only:
        description:
            - Allow only HTTPS traffic to the storage account.
        type: bool
        default: "True"
    minimum_tls_version:
        description:
            - The minimum TLS version permitted on requests to the storage account.
        type: str
        default: "TLS1_2"
        choices:
            - "TLS1_0"
            - "TLS1_1"
            - "TLS1_2"
    state:
        description:
            - Assert the state of the storageaccount.
            - Use C(present) to create or update and C(absent) to delete.
        type: str
        default: present
        choices:
            - present
            - absent
extends_documentation_fragment:
    - azure.azcollection.azure
    - azure.azcollection.azure_tags
author:
    - "Azure Magic Modules Generator (@azure-magic-modules)"
seealso:
    - description: Azure StorageAccount REST API
      link: https://learn.microsoft.com/en-us/rest/api/storagerp/storage-accounts
'''

EXAMPLES = r'''
- name: Create StorageAccount
  azure_rm_storageaccount:
    resource_group: myResourceGroup
    name: myStorageAccount
    location: eastus
    account_type: "example_value"
    state: present

- name: Delete StorageAccount
  azure_rm_storageaccount:
    resource_group: myResourceGroup
    name: myStorageAccount
    state: absent
'''

RETURN = r'''
state:
    description: Current state of the storageaccount.
    returned: always
    type: dict
    contains:
        id:
            description: Resource ID.
            type: str
        name:
            description: Resource name.
            type: str
        location:
            description: Resource location.
            type: str
        tags:
            description: Resource tags.
            type: dict
        account_type:
            description: The SKU name for the storage account, determining replication strategy.
            type: str
        kind:
            description: The kind of storage account.
            type: str
        access_tier:
            description: The access tier used for billing. Required for BlobStorage kind.
            type: str
        https_only:
            description: Allow only HTTPS traffic to the storage account.
            type: bool
        minimum_tls_version:
            description: The minimum TLS version permitted on requests to the storage account.
            type: str
'''

import json
from ansible_collections.azure.azcollection.plugins.module_utils.azure_rm_common import AzureRMModuleBase


class AzureRMStorageAccount(AzureRMModuleBase):

    def __init__(self):
        self.module_arg_spec = dict(
            resource_group=dict(type='str', required=True, aliases=['resource_group_name']),
            name=dict(type='str', required=True),
            location=dict(type='str'),
            account_type=dict(
                type='str',
                required=True,
                choices=["Standard_LRS", "Standard_GRS", "Standard_RAGRS", "Premium_LRS", "Standard_ZRS"],
            ),
            kind=dict(
                type='str',
                default='StorageV2',
                choices=["Storage", "StorageV2", "BlobStorage"],
            ),
            access_tier=dict(
                type='str',
                choices=["Hot", "Cool"],
            ),
            https_only=dict(
                type='bool',
                default=True,
            ),
            minimum_tls_version=dict(
                type='str',
                default='TLS1_2',
                choices=["TLS1_0", "TLS1_1", "TLS1_2"],
            ),
            state=dict(type='str', default='present', choices=['present', 'absent']),
        )

        self.resource_group = None
        self.name = None
        self.location = None
        self.account_type = None
        self.kind = None
        self.access_tier = None
        self.https_only = None
        self.minimum_tls_version = None
        self.state = None
        self.tags = None

        self.results = dict(changed=False, state=dict())

        required_if = [
            ('state', 'present', ['resource_group', 'name']),
        ]

        super().__init__(
            derived_arg_spec=self.module_arg_spec,
            supports_check_mode=True,
            supports_tags=True,
            required_if=required_if,
        )

    def exec_module(self, **kwargs):
        for key in list(self.module_arg_spec.keys()) + ['tags']:
            setattr(self, key, kwargs[key])

        resource_group = self.resource_group
        name = self.name

        # Get existing resource
        response = self.get_resource()

        if self.state == 'present':
            if not self.location:
                rg = self.get_resource_group(resource_group)
                self.location = rg.location

            # Build the resource body from parameters
            body = self.build_body()

            if response:
                # Check if update needed
                update_tags, new_tags = self.update_tags(response.get('tags'))
                if update_tags:
                    body['tags'] = new_tags
                    self.results['changed'] = True

                if self.check_update(response, body):
                    self.results['changed'] = True

                if self.results['changed']:
                    if not self.check_mode:
                        response = self.create_or_update(resource_group, name, body)
                else:
                    response = response
            else:
                if self.tags:
                    body['tags'] = self.tags
                if not self.check_mode:
                    response = self.create_or_update(resource_group, name, body)
                self.results['changed'] = True

        elif self.state == 'absent':
            if response:
                if not self.check_mode:
                    self.delete_resource(resource_group, name)
                self.results['changed'] = True

        if response:
            self.results['state'] = self.format_response(response)

        return self.results

    def build_body(self):
        body = dict(
            location=self.location,
        )
        if self.account_type is not None:
            _target = body
            _target = _target.setdefault('sku', {})
            _target['name'] = self.account_type
        if self.kind is not None:
            body['kind'] = self.kind

        properties = body.setdefault('properties', {})
        if self.access_tier is not None:
            properties['accessTier'] = self.access_tier
        if self.https_only is not None:
            properties['supportsHttpsTrafficOnly'] = self.https_only
        if self.minimum_tls_version is not None:
            properties['minimumTlsVersion'] = self.minimum_tls_version

        if self.tags:
            body['tags'] = self.tags

        return body

    def check_update(self, existing, desired):
        """Compare existing resource with desired state."""
        # Check account_type
        if self.account_type is not None:
            _existing = existing
            _existing = _existing.get('sku', {}) if isinstance(_existing, dict) else {}
            if _existing.get('name') != self.account_type:
                return True
        # Check kind
        if self.kind is not None:
            if existing.get('kind') != self.kind:
                return True
        # Check access_tier
        if self.access_tier is not None:
            if existing.get('properties', {}).get('accessTier') != self.access_tier:
                return True
        # Check https_only
        if self.https_only is not None:
            if existing.get('properties', {}).get('supportsHttpsTrafficOnly') != self.https_only:
                return True
        # Check minimum_tls_version
        if self.minimum_tls_version is not None:
            if existing.get('properties', {}).get('minimumTlsVersion') != self.minimum_tls_version:
                return True

        return False

    def get_resource(self):
        try:
            url = self.get_resource_url()
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2023-05-01'},
                None, None, [200], 0, 0,
            )
            return self.deserialize_response(response)
        except Exception:
            return None

    def create_or_update(self, resource_group, name, body):
        url = self.get_resource_url()
        response = self.mgmt_client.query(
            url, "PUT",
            {'api-version': '2023-05-01'},
            None, body, [200, 201], 0, 0,
        )
        return self.deserialize_response(response)

    def delete_resource(self, resource_group, name):
        url = self.get_resource_url()
        self.mgmt_client.query(
            url, "DELETE",
            {'api-version': '2023-05-01'},
            None, None, [200, 202, 204], 0, 0,
        )

    def get_resource_url(self):
        return (
            '/subscriptions/{subscription_id}'
            '/resourceGroups/{resource_group}'
            '/providers/Microsoft.Storage/storageAccounts/{name}'
        ).format(
            subscription_id=self.subscription_id,
            resource_group=self.resource_group,
            name=self.name,
        )

    def format_response(self, response):
        result = dict(
            id=response.get('id'),
            name=response.get('name'),
            location=response.get('location'),
            tags=response.get('tags'),
        )
        _body = response
        _body = _body.get('sku', {}) if isinstance(_body, dict) else {}
        result['account_type'] = _body.get('name')
        result['kind'] = response.get('kind')
        result['access_tier'] = response.get('properties', {}).get('accessTier')
        result['https_only'] = response.get('properties', {}).get('supportsHttpsTrafficOnly')
        result['minimum_tls_version'] = response.get('properties', {}).get('minimumTlsVersion')
        return result

    @staticmethod
    def deserialize_response(response):
        try:
            return json.loads(response.text)
        except (ValueError, AttributeError):
            return None


def main():
    AzureRMStorageAccount()


if __name__ == '__main__':
    main()
