#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2024, Azure Magic Modules Generator
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Auto-generated by Azure Magic Modules — do not edit manually

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: azure_rm_devtestlab_info
version_added: "0.1.0"
short_description: Get facts for Azure DevTestLab
description:
    - Get facts for a specific DevTestLab or list all DevTestLabs in a resource group.
    - This module was auto-generated by Azure Magic Modules.
options:
    resource_group:
        description:
            - Name of the resource group.
        type: str
        required: true
    name:
        description:
            - Name of the devtestlab.
            - If not specified, all devtestlabs in the resource group will be listed.
        type: str
extends_documentation_fragment:
    - azure.azcollection.azure
    - azure.azcollection.azure_tags
author:
    - "Azure Magic Modules Generator (@azure-magic-modules)"
seealso:
    - description: Azure DevTestLab REST API
      link: https://learn.microsoft.com/en-us/azure/devtest-labs/devtest-lab-overview
'''

EXAMPLES = r'''
- name: Get facts for a specific DevTestLab
  azure_rm_devtestlab_info:
    resource_group: myResourceGroup
    name: myDevTestLab

- name: List all DevTestLabs in a resource group
  azure_rm_devtestlab_info:
    resource_group: myResourceGroup
'''

RETURN = r'''
devtestlabs:
    description:
        - List of devtestlab dicts.
    returned: always
    type: list
    elements: dict
    contains:
        id:
            description: Resource ID.
            type: str
        name:
            description: Resource name.
            type: str
        location:
            description: Resource location.
            type: str
        tags:
            description: Resource tags.
            type: dict
        lab_storage_type:
            description: Storage type for the lab.
            type: str
        mandatory_artifacts_resource_ids_linux:
            description: Mandatory artifact resource IDs for Linux VMs.
            type: list
        mandatory_artifacts_resource_ids_windows:
            description: Mandatory artifact resource IDs for Windows VMs.
            type: list
        premium_data_disks:
            description: Whether premium data disks are allowed.
            type: str
        environment_permission:
            description: Access permission for lab environments.
            type: str
'''

import json
from ansible_collections.azure.azcollection.plugins.module_utils.azure_rm_common import AzureRMModuleBase


class AzureRMDevTestLabInfo(AzureRMModuleBase):

    def __init__(self):
        self.module_arg_spec = dict(
            resource_group=dict(type='str', required=True, aliases=['resource_group_name']),
            name=dict(type='str'),
        )

        self.resource_group = None
        self.name = None
        self.tags = None

        self.results = dict(
            changed=False,
            devtestlabs=[],
        )

        super().__init__(
            derived_arg_spec=self.module_arg_spec,
            supports_check_mode=True,
            supports_tags=False,
            facts_module=True,
        )

    def exec_module(self, **kwargs):
        for key in list(self.module_arg_spec.keys()) + ['tags']:
            setattr(self, key, kwargs[key])

        result_key = 'devtestlabs'

        if self.name:
            response = self.get_resource()
            if response:
                if self.has_tags(response.get('tags'), self.tags):
                    self.results[result_key] = [self.format_response(response)]
        else:
            responses = self.list_by_resource_group()
            for item in responses:
                if self.has_tags(item.get('tags'), self.tags):
                    self.results[result_key].append(self.format_response(item))

        return self.results

    def get_resource(self):
        try:
            url = (
                '/subscriptions/{subscription_id}'
                '/resourceGroups/{resource_group}'
                '/providers/Microsoft.DevTestLab/labs/{name}'
            ).format(
                subscription_id=self.subscription_id,
                resource_group=self.resource_group,
                name=self.name,
            )
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2018-09-15'},
                None, None, [200], 0, 0,
            )
            return self.deserialize_response(response)
        except Exception:
            return None

    def list_by_resource_group(self):
        try:
            url = (
                '/subscriptions/{subscription_id}'
                '/resourceGroups/{resource_group}'
                '/providers/Microsoft.DevTestLab/labs'
            ).format(
                subscription_id=self.subscription_id,
                resource_group=self.resource_group,
            )
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2018-09-15'},
                None, None, [200], 0, 0,
            )
            result = self.deserialize_response(response)
            if result and isinstance(result, dict):
                return result.get('value', [])
            return []
        except Exception:
            return []

    def format_response(self, response):
        result = dict(
            id=response.get('id'),
            name=response.get('name'),
            location=response.get('location'),
            tags=response.get('tags'),
        )
        result['lab_storage_type'] = response.get('labStorageType')
        result['mandatory_artifacts_resource_ids_linux'] = response.get('mandatoryArtifactsResourceIdsLinux')
        result['mandatory_artifacts_resource_ids_windows'] = response.get('mandatoryArtifactsResourceIdsWindows')
        result['premium_data_disks'] = response.get('premiumDataDisks')
        result['environment_permission'] = response.get('environmentPermission')
        return result

    @staticmethod
    def deserialize_response(response):
        try:
            return json.loads(response.text)
        except (ValueError, AttributeError):
            return None


def main():
    AzureRMDevTestLabInfo()


if __name__ == '__main__':
    main()
