#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2024, Azure Magic Modules Generator
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Auto-generated by Azure Magic Modules — do not edit manually

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: azure_rm_virtualmachine
version_added: "0.1.0"
short_description: Manage Azure virtual machine instances.
description:
    - Create, update, or delete an Azure VirtualMachine.
    - This module was auto-generated by Azure Magic Modules.
options:
    resource_group:
        description:
            - Name of the resource group.
        type: str
        required: true
    name:
        description:
            - Name of the virtualmachine.
        type: str
        required: true
    location:
        description:
            - Valid Azure location. Defaults to the location of the resource group.
        type: str
    vm_size:
        description:
            - Size of the virtual machine.
        type: str
        required: true
    admin_username:
        description:
            - Administrator username for the virtual machine.
        type: str
    admin_password:
        description:
            - Administrator password for the virtual machine.
        type: str
    admin_ssh_key:
        description:
            - SSH public key for the virtual machine.
        type: str
    os_disk_type:
        description:
            - Managed disk storage account type for the OS disk.
        type: str
        choices:
            - "Premium_LRS"
            - "StandardSSD_LRS"
            - "Standard_LRS"
    os_disk_size_gb:
        description:
            - Size of the OS disk in GB.
        type: int
    image_publisher:
        description:
            - Publisher of the VM image.
        type: str
    image_offer:
        description:
            - Offer of the VM image.
        type: str
    image_sku:
        description:
            - SKU of the VM image.
        type: str
    image_version:
        description:
            - Version of the VM image.
        type: str
        default: "latest"
    network_interface_ids:
        description:
            - List of network interface resource IDs.
        type: list
    availability_set_id:
        description:
            - Resource ID of the availability set.
        type: str
    zone:
        description:
            - Availability zone for the virtual machine.
        type: str
    state:
        description:
            - Assert the state of the virtualmachine.
            - Use C(present) to create or update and C(absent) to delete.
        type: str
        default: present
        choices:
            - present
            - absent
extends_documentation_fragment:
    - azure.azcollection.azure
    - azure.azcollection.azure_tags
author:
    - "Azure Magic Modules Generator (@azure-magic-modules)"
seealso:
    - description: Azure VirtualMachine REST API
      link: https://learn.microsoft.com/en-us/azure/virtual-machines/
'''

EXAMPLES = r'''
- name: Create VirtualMachine
  azure_rm_virtualmachine:
    resource_group: myResourceGroup
    name: myVirtualMachine
    location: eastus
    vm_size: "example_value"
    state: present

- name: Delete VirtualMachine
  azure_rm_virtualmachine:
    resource_group: myResourceGroup
    name: myVirtualMachine
    state: absent
'''

RETURN = r'''
state:
    description: Current state of the virtualmachine.
    returned: always
    type: dict
    contains:
        id:
            description: Resource ID.
            type: str
        name:
            description: Resource name.
            type: str
        location:
            description: Resource location.
            type: str
        tags:
            description: Resource tags.
            type: dict
        vm_size:
            description: Size of the virtual machine.
            type: str
        admin_username:
            description: Administrator username for the virtual machine.
            type: str
        admin_password:
            description: Administrator password for the virtual machine.
            type: str
        admin_ssh_key:
            description: SSH public key for the virtual machine.
            type: str
        os_disk_type:
            description: Managed disk storage account type for the OS disk.
            type: str
        os_disk_size_gb:
            description: Size of the OS disk in GB.
            type: int
        image_publisher:
            description: Publisher of the VM image.
            type: str
        image_offer:
            description: Offer of the VM image.
            type: str
        image_sku:
            description: SKU of the VM image.
            type: str
        image_version:
            description: Version of the VM image.
            type: str
        network_interface_ids:
            description: List of network interface resource IDs.
            type: list
        availability_set_id:
            description: Resource ID of the availability set.
            type: str
        zone:
            description: Availability zone for the virtual machine.
            type: str
'''

import json
from ansible_collections.azure.azcollection.plugins.module_utils.azure_rm_common import AzureRMModuleBase


class AzureRMVirtualMachine(AzureRMModuleBase):

    def __init__(self):
        self.module_arg_spec = dict(
            resource_group=dict(type='str', required=True, aliases=['resource_group_name']),
            name=dict(type='str', required=True),
            location=dict(type='str'),
            vm_size=dict(
                type='str',
                required=True,
            ),
            admin_username=dict(
                type='str',
            ),
            admin_password=dict(
                type='str',
            ),
            admin_ssh_key=dict(
                type='str',
            ),
            os_disk_type=dict(
                type='str',
                choices=['Premium_LRS', 'StandardSSD_LRS', 'Standard_LRS'],
            ),
            os_disk_size_gb=dict(
                type='int',
            ),
            image_publisher=dict(
                type='str',
            ),
            image_offer=dict(
                type='str',
            ),
            image_sku=dict(
                type='str',
            ),
            image_version=dict(
                type='str',
                default='latest',
            ),
            network_interface_ids=dict(
                type='list',
            ),
            availability_set_id=dict(
                type='str',
            ),
            zone=dict(
                type='str',
            ),
            state=dict(type='str', default='present', choices=['present', 'absent']),
        )

        self.resource_group = None
        self.name = None
        self.location = None
        self.vm_size = None
        self.admin_username = None
        self.admin_password = None
        self.admin_ssh_key = None
        self.os_disk_type = None
        self.os_disk_size_gb = None
        self.image_publisher = None
        self.image_offer = None
        self.image_sku = None
        self.image_version = None
        self.network_interface_ids = None
        self.availability_set_id = None
        self.zone = None
        self.state = None
        self.tags = None

        self.results = dict(changed=False, state=dict())

        required_if = [
            ('state', 'present', ['resource_group', 'name']),
        ]

        super().__init__(
            derived_arg_spec=self.module_arg_spec,
            supports_check_mode=True,
            supports_tags=True,
            required_if=required_if,
        )

    def exec_module(self, **kwargs):
        for key in list(self.module_arg_spec.keys()) + ['tags']:
            setattr(self, key, kwargs[key])

        resource_group = self.resource_group
        name = self.name

        # Get existing resource
        response = self.get_resource()

        if self.state == 'present':
            if not self.location:
                rg = self.get_resource_group(resource_group)
                self.location = rg.location

            # Build the resource body from parameters
            body = self.build_body()

            if response:
                # Check if update needed
                update_tags, new_tags = self.update_tags(response.get('tags'))
                if update_tags:
                    body['tags'] = new_tags
                    self.results['changed'] = True

                if self.check_update(response, body):
                    self.results['changed'] = True

                if self.results['changed']:
                    if not self.check_mode:
                        response = self.create_or_update(resource_group, name, body)
                else:
                    response = response
            else:
                if self.tags:
                    body['tags'] = self.tags
                if not self.check_mode:
                    response = self.create_or_update(resource_group, name, body)
                self.results['changed'] = True

        elif self.state == 'absent':
            if response:
                if not self.check_mode:
                    self.delete_resource(resource_group, name)
                self.results['changed'] = True

        if response:
            self.results['state'] = self.format_response(response)

        return self.results

    def build_body(self):
        body = dict(
            location=self.location,
        )
        if self.vm_size is not None:
            _target = body
            _target = _target.setdefault('hardwareProfile', {})
            _target['vmSize'] = self.vm_size
        if self.admin_username is not None:
            _target = body
            _target = _target.setdefault('osProfile', {})
            _target['adminUsername'] = self.admin_username
        if self.admin_password is not None:
            _target = body
            _target = _target.setdefault('osProfile', {})
            _target['adminPassword'] = self.admin_password
        if self.admin_ssh_key is not None:
            _target = body
            _target = _target.setdefault('osProfile', {})
            _target = _target.setdefault('linuxConfiguration', {})
            _target = _target.setdefault('ssh', {})
            _target['publicKeys'] = self.admin_ssh_key
        if self.os_disk_type is not None:
            _target = body
            _target = _target.setdefault('storageProfile', {})
            _target = _target.setdefault('osDisk', {})
            _target = _target.setdefault('managedDisk', {})
            _target['storageAccountType'] = self.os_disk_type
        if self.os_disk_size_gb is not None:
            _target = body
            _target = _target.setdefault('storageProfile', {})
            _target = _target.setdefault('osDisk', {})
            _target['diskSizeGB'] = self.os_disk_size_gb
        if self.image_publisher is not None:
            _target = body
            _target = _target.setdefault('storageProfile', {})
            _target = _target.setdefault('imageReference', {})
            _target['publisher'] = self.image_publisher
        if self.image_offer is not None:
            _target = body
            _target = _target.setdefault('storageProfile', {})
            _target = _target.setdefault('imageReference', {})
            _target['offer'] = self.image_offer
        if self.image_sku is not None:
            _target = body
            _target = _target.setdefault('storageProfile', {})
            _target = _target.setdefault('imageReference', {})
            _target['sku'] = self.image_sku
        if self.image_version is not None:
            _target = body
            _target = _target.setdefault('storageProfile', {})
            _target = _target.setdefault('imageReference', {})
            _target['version'] = self.image_version
        if self.network_interface_ids is not None:
            _target = body
            _target = _target.setdefault('networkProfile', {})
            _target['networkInterfaces'] = self.network_interface_ids
        if self.availability_set_id is not None:
            _target = body
            _target = _target.setdefault('availabilitySet', {})
            _target['id'] = self.availability_set_id
        if self.zone is not None:
            body['zones'] = self.zone

        if self.tags:
            body['tags'] = self.tags

        return body

    def check_update(self, existing, desired):
        """Compare existing resource with desired state."""
        # Check vm_size
        if self.vm_size is not None:
            _existing = existing
            _existing = _existing.get('hardwareProfile', {}) if isinstance(_existing, dict) else {}
            if _existing.get('vmSize') != self.vm_size:
                return True
        # Check admin_username
        if self.admin_username is not None:
            _existing = existing
            _existing = _existing.get('osProfile', {}) if isinstance(_existing, dict) else {}
            if _existing.get('adminUsername') != self.admin_username:
                return True
        # Check admin_password
        if self.admin_password is not None:
            _existing = existing
            _existing = _existing.get('osProfile', {}) if isinstance(_existing, dict) else {}
            if _existing.get('adminPassword') != self.admin_password:
                return True
        # Check admin_ssh_key
        if self.admin_ssh_key is not None:
            _existing = existing
            _existing = _existing.get('osProfile', {}) if isinstance(_existing, dict) else {}
            _existing = _existing.get('linuxConfiguration', {}) if isinstance(_existing, dict) else {}
            _existing = _existing.get('ssh', {}) if isinstance(_existing, dict) else {}
            if _existing.get('publicKeys') != self.admin_ssh_key:
                return True
        # Check os_disk_type
        if self.os_disk_type is not None:
            _existing = existing
            _existing = _existing.get('storageProfile', {}) if isinstance(_existing, dict) else {}
            _existing = _existing.get('osDisk', {}) if isinstance(_existing, dict) else {}
            _existing = _existing.get('managedDisk', {}) if isinstance(_existing, dict) else {}
            if _existing.get('storageAccountType') != self.os_disk_type:
                return True
        # Check os_disk_size_gb
        if self.os_disk_size_gb is not None:
            _existing = existing
            _existing = _existing.get('storageProfile', {}) if isinstance(_existing, dict) else {}
            _existing = _existing.get('osDisk', {}) if isinstance(_existing, dict) else {}
            if _existing.get('diskSizeGB') != self.os_disk_size_gb:
                return True
        # Check image_publisher
        if self.image_publisher is not None:
            _existing = existing
            _existing = _existing.get('storageProfile', {}) if isinstance(_existing, dict) else {}
            _existing = _existing.get('imageReference', {}) if isinstance(_existing, dict) else {}
            if _existing.get('publisher') != self.image_publisher:
                return True
        # Check image_offer
        if self.image_offer is not None:
            _existing = existing
            _existing = _existing.get('storageProfile', {}) if isinstance(_existing, dict) else {}
            _existing = _existing.get('imageReference', {}) if isinstance(_existing, dict) else {}
            if _existing.get('offer') != self.image_offer:
                return True
        # Check image_sku
        if self.image_sku is not None:
            _existing = existing
            _existing = _existing.get('storageProfile', {}) if isinstance(_existing, dict) else {}
            _existing = _existing.get('imageReference', {}) if isinstance(_existing, dict) else {}
            if _existing.get('sku') != self.image_sku:
                return True
        # Check image_version
        if self.image_version is not None:
            _existing = existing
            _existing = _existing.get('storageProfile', {}) if isinstance(_existing, dict) else {}
            _existing = _existing.get('imageReference', {}) if isinstance(_existing, dict) else {}
            if _existing.get('version') != self.image_version:
                return True
        # Check network_interface_ids
        if self.network_interface_ids is not None:
            _existing = existing
            _existing = _existing.get('networkProfile', {}) if isinstance(_existing, dict) else {}
            if _existing.get('networkInterfaces') != self.network_interface_ids:
                return True
        # Check availability_set_id
        if self.availability_set_id is not None:
            _existing = existing
            _existing = _existing.get('availabilitySet', {}) if isinstance(_existing, dict) else {}
            if _existing.get('id') != self.availability_set_id:
                return True
        # Check zone
        if self.zone is not None:
            if existing.get('zones') != self.zone:
                return True

        return False

    def get_resource(self):
        try:
            url = self.get_resource_url()
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2024-03-01'},
                None, None, [200], 0, 0,
            )
            return self.deserialize_response(response)
        except Exception:
            return None

    def create_or_update(self, resource_group, name, body):
        url = self.get_resource_url()
        response = self.mgmt_client.query(
            url, "PUT",
            {'api-version': '2024-03-01'},
            None, body, [200, 201], 0, 0,
        )
        return self.deserialize_response(response)

    def delete_resource(self, resource_group, name):
        url = self.get_resource_url()
        self.mgmt_client.query(
            url, "DELETE",
            {'api-version': '2024-03-01'},
            None, None, [200, 202, 204], 0, 0,
        )

    def get_resource_url(self):
        return (
            '/subscriptions/{subscription_id}'
            '/resourceGroups/{resource_group}'
            '/providers/Microsoft.Compute/virtualMachines/{name}'
        ).format(
            subscription_id=self.subscription_id,
            resource_group=self.resource_group,
            name=self.name,
        )

    def format_response(self, response):
        result = dict(
            id=response.get('id'),
            name=response.get('name'),
            location=response.get('location'),
            tags=response.get('tags'),
        )
        _body = response
        _body = _body.get('hardwareProfile', {}) if isinstance(_body, dict) else {}
        result['vm_size'] = _body.get('vmSize')
        _body = response
        _body = _body.get('osProfile', {}) if isinstance(_body, dict) else {}
        result['admin_username'] = _body.get('adminUsername')
        _body = response
        _body = _body.get('osProfile', {}) if isinstance(_body, dict) else {}
        result['admin_password'] = _body.get('adminPassword')
        _body = response
        _body = _body.get('osProfile', {}) if isinstance(_body, dict) else {}
        _body = _body.get('linuxConfiguration', {}) if isinstance(_body, dict) else {}
        _body = _body.get('ssh', {}) if isinstance(_body, dict) else {}
        result['admin_ssh_key'] = _body.get('publicKeys')
        _body = response
        _body = _body.get('storageProfile', {}) if isinstance(_body, dict) else {}
        _body = _body.get('osDisk', {}) if isinstance(_body, dict) else {}
        _body = _body.get('managedDisk', {}) if isinstance(_body, dict) else {}
        result['os_disk_type'] = _body.get('storageAccountType')
        _body = response
        _body = _body.get('storageProfile', {}) if isinstance(_body, dict) else {}
        _body = _body.get('osDisk', {}) if isinstance(_body, dict) else {}
        result['os_disk_size_gb'] = _body.get('diskSizeGB')
        _body = response
        _body = _body.get('storageProfile', {}) if isinstance(_body, dict) else {}
        _body = _body.get('imageReference', {}) if isinstance(_body, dict) else {}
        result['image_publisher'] = _body.get('publisher')
        _body = response
        _body = _body.get('storageProfile', {}) if isinstance(_body, dict) else {}
        _body = _body.get('imageReference', {}) if isinstance(_body, dict) else {}
        result['image_offer'] = _body.get('offer')
        _body = response
        _body = _body.get('storageProfile', {}) if isinstance(_body, dict) else {}
        _body = _body.get('imageReference', {}) if isinstance(_body, dict) else {}
        result['image_sku'] = _body.get('sku')
        _body = response
        _body = _body.get('storageProfile', {}) if isinstance(_body, dict) else {}
        _body = _body.get('imageReference', {}) if isinstance(_body, dict) else {}
        result['image_version'] = _body.get('version')
        _body = response
        _body = _body.get('networkProfile', {}) if isinstance(_body, dict) else {}
        result['network_interface_ids'] = _body.get('networkInterfaces')
        _body = response
        _body = _body.get('availabilitySet', {}) if isinstance(_body, dict) else {}
        result['availability_set_id'] = _body.get('id')
        result['zone'] = response.get('zones')
        return result

    @staticmethod
    def deserialize_response(response):
        try:
            return json.loads(response.text)
        except (ValueError, AttributeError):
            return None


def main():
    AzureRMVirtualMachine()


if __name__ == '__main__':
    main()
