#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2024, Azure Magic Modules Generator
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Auto-generated by Azure Magic Modules — do not edit manually

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: azure_rm_hdinsightcluster_info
version_added: "0.1.0"
short_description: Get facts for Azure HDInsightCluster
description:
    - Get facts for a specific HDInsightCluster or list all HDInsightClusters in a resource group.
    - This module was auto-generated by Azure Magic Modules.
options:
    resource_group:
        description:
            - Name of the resource group.
        type: str
        required: true
    name:
        description:
            - Name of the hdinsightcluster.
            - If not specified, all hdinsightclusters in the resource group will be listed.
        type: str
extends_documentation_fragment:
    - azure.azcollection.azure
    - azure.azcollection.azure_tags
author:
    - "Azure Magic Modules Generator (@azure-magic-modules)"
seealso:
    - description: Azure HDInsightCluster REST API
      link: https://learn.microsoft.com/en-us/azure/hdinsight/
'''

EXAMPLES = r'''
- name: Get facts for a specific HDInsightCluster
  azure_rm_hdinsightcluster_info:
    resource_group: myResourceGroup
    name: myHDInsightCluster

- name: List all HDInsightClusters in a resource group
  azure_rm_hdinsightcluster_info:
    resource_group: myResourceGroup
'''

RETURN = r'''
hdinsightclusters:
    description:
        - List of hdinsightcluster dicts.
    returned: always
    type: list
    elements: dict
    contains:
        id:
            description: Resource ID.
            type: str
        name:
            description: Resource name.
            type: str
        location:
            description: Resource location.
            type: str
        tags:
            description: Resource tags.
            type: dict
        cluster_version:
            description: HDInsight cluster version.
            type: str
        os_type:
            description: Operating system type for the cluster.
            type: str
        tier:
            description: Cluster tier.
            type: str
        kind:
            description: Type of HDInsight cluster.
            type: str
        gateway_username:
            description: Gateway HTTP username for the cluster.
            type: str
        gateway_password:
            description: Gateway HTTP password for the cluster.
            type: str
        head_node_vm_size:
            description: VM size for the head nodes.
            type: str
        worker_node_vm_size:
            description: VM size for the worker nodes.
            type: str
        worker_node_count:
            description: Number of worker nodes in the cluster.
            type: int
'''

import json
from ansible_collections.azure.azcollection.plugins.module_utils.azure_rm_common import AzureRMModuleBase


class AzureRMHDInsightClusterInfo(AzureRMModuleBase):

    def __init__(self):
        self.module_arg_spec = dict(
            resource_group=dict(type='str', required=True, aliases=['resource_group_name']),
            name=dict(type='str'),
        )

        self.resource_group = None
        self.name = None
        self.tags = None

        self.results = dict(
            changed=False,
            hdinsightclusters=[],
        )

        super().__init__(
            derived_arg_spec=self.module_arg_spec,
            supports_check_mode=True,
            supports_tags=False,
            facts_module=True,
        )

    def exec_module(self, **kwargs):
        for key in list(self.module_arg_spec.keys()) + ['tags']:
            setattr(self, key, kwargs[key])

        result_key = 'hdinsightclusters'

        if self.name:
            response = self.get_resource()
            if response:
                if self.has_tags(response.get('tags'), self.tags):
                    self.results[result_key] = [self.format_response(response)]
        else:
            responses = self.list_by_resource_group()
            for item in responses:
                if self.has_tags(item.get('tags'), self.tags):
                    self.results[result_key].append(self.format_response(item))

        return self.results

    def get_resource(self):
        try:
            url = (
                '/subscriptions/{subscription_id}'
                '/resourceGroups/{resource_group}'
                '/providers/Microsoft.HDInsight/clusters/{name}'
            ).format(
                subscription_id=self.subscription_id,
                resource_group=self.resource_group,
                name=self.name,
            )
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2021-06-01'},
                None, None, [200], 0, 0,
            )
            return self.deserialize_response(response)
        except Exception:
            return None

    def list_by_resource_group(self):
        try:
            url = (
                '/subscriptions/{subscription_id}'
                '/resourceGroups/{resource_group}'
                '/providers/Microsoft.HDInsight/clusters'
            ).format(
                subscription_id=self.subscription_id,
                resource_group=self.resource_group,
            )
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2021-06-01'},
                None, None, [200], 0, 0,
            )
            result = self.deserialize_response(response)
            if result and isinstance(result, dict):
                return result.get('value', [])
            return []
        except Exception:
            return []

    def format_response(self, response):
        result = dict(
            id=response.get('id'),
            name=response.get('name'),
            location=response.get('location'),
            tags=response.get('tags'),
        )
        result['cluster_version'] = response.get('clusterVersion')
        result['os_type'] = response.get('osType')
        result['tier'] = response.get('tier')
        result['kind'] = response.get('kind')
        _body = response
        _body = _body.get('gateway', {}) if isinstance(_body, dict) else {}
        _body = _body.get('restAuthCredential', {}) if isinstance(_body, dict) else {}
        result['gateway_username'] = _body.get('username')
        _body = response
        _body = _body.get('gateway', {}) if isinstance(_body, dict) else {}
        _body = _body.get('restAuthCredential', {}) if isinstance(_body, dict) else {}
        result['gateway_password'] = _body.get('password')
        _body = response
        _body = _body.get('computeProfile', {}) if isinstance(_body, dict) else {}
        _body = _body.get('roles', {}) if isinstance(_body, dict) else {}
        _body = _body.get('headnode', {}) if isinstance(_body, dict) else {}
        _body = _body.get('hardwareProfile', {}) if isinstance(_body, dict) else {}
        result['head_node_vm_size'] = _body.get('vmSize')
        _body = response
        _body = _body.get('computeProfile', {}) if isinstance(_body, dict) else {}
        _body = _body.get('roles', {}) if isinstance(_body, dict) else {}
        _body = _body.get('workernode', {}) if isinstance(_body, dict) else {}
        _body = _body.get('hardwareProfile', {}) if isinstance(_body, dict) else {}
        result['worker_node_vm_size'] = _body.get('vmSize')
        _body = response
        _body = _body.get('computeProfile', {}) if isinstance(_body, dict) else {}
        _body = _body.get('roles', {}) if isinstance(_body, dict) else {}
        _body = _body.get('workernode', {}) if isinstance(_body, dict) else {}
        result['worker_node_count'] = _body.get('targetInstanceCount')
        return result

    @staticmethod
    def deserialize_response(response):
        try:
            return json.loads(response.text)
        except (ValueError, AttributeError):
            return None


def main():
    AzureRMHDInsightClusterInfo()


if __name__ == '__main__':
    main()
