#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2024, Azure Magic Modules Generator
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Auto-generated by Azure Magic Modules — do not edit manually

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: azure_rm_servicebustopic
version_added: "0.1.0"
short_description: Manage Azure Service Bus Topic instances.
description:
    - Create, update, or delete an Azure ServiceBusTopic.
    - This module was auto-generated by Azure Magic Modules.
options:
    resource_group:
        description:
            - Name of the resource group.
        type: str
        required: true
    name:
        description:
            - Name of the servicebustopic.
        type: str
        required: true
    location:
        description:
            - Valid Azure location. Defaults to the location of the resource group.
        type: str
    namespace_name:
        description:
            - Name of the Service Bus Namespace.
        type: str
        required: true
    max_size_in_megabytes:
        description:
            - Maximum size of the topic in megabytes.
        type: int
    default_message_ttl:
        description:
            - Default message time-to-live in ISO 8601 format.
        type: str
    requires_duplicate_detection:
        description:
            - Whether duplicate detection is required.
        type: bool
    enable_partitioning:
        description:
            - Whether partitioning is enabled.
        type: bool
    support_ordering:
        description:
            - Whether ordering is supported.
        type: bool
    max_message_size_in_kilobytes:
        description:
            - Maximum message size in kilobytes.
        type: int
    state:
        description:
            - Assert the state of the servicebustopic.
            - Use C(present) to create or update and C(absent) to delete.
        type: str
        default: present
        choices:
            - present
            - absent
extends_documentation_fragment:
    - azure.azcollection.azure
    - azure.azcollection.azure_tags
author:
    - "Azure Magic Modules Generator (@azure-magic-modules)"
seealso:
    - description: Azure ServiceBusTopic REST API
      link: https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-queues-topics-subscriptions
'''

EXAMPLES = r'''
- name: Create ServiceBusTopic
  azure_rm_servicebustopic:
    resource_group: myResourceGroup
    name: myServiceBusTopic
    location: eastus
    namespace_name: "example_value"
    state: present

- name: Delete ServiceBusTopic
  azure_rm_servicebustopic:
    resource_group: myResourceGroup
    name: myServiceBusTopic
    state: absent
'''

RETURN = r'''
state:
    description: Current state of the servicebustopic.
    returned: always
    type: dict
    contains:
        id:
            description: Resource ID.
            type: str
        name:
            description: Resource name.
            type: str
        location:
            description: Resource location.
            type: str
        tags:
            description: Resource tags.
            type: dict
        namespace_name:
            description: Name of the Service Bus Namespace.
            type: str
        max_size_in_megabytes:
            description: Maximum size of the topic in megabytes.
            type: int
        default_message_ttl:
            description: Default message time-to-live in ISO 8601 format.
            type: str
        requires_duplicate_detection:
            description: Whether duplicate detection is required.
            type: bool
        enable_partitioning:
            description: Whether partitioning is enabled.
            type: bool
        support_ordering:
            description: Whether ordering is supported.
            type: bool
        max_message_size_in_kilobytes:
            description: Maximum message size in kilobytes.
            type: int
'''

import json
from ansible_collections.azure.azcollection.plugins.module_utils.azure_rm_common import AzureRMModuleBase


class AzureRMServiceBusTopic(AzureRMModuleBase):

    def __init__(self):
        self.module_arg_spec = dict(
            resource_group=dict(type='str', required=True, aliases=['resource_group_name']),
            name=dict(type='str', required=True),
            location=dict(type='str'),
            namespace_name=dict(
                type='str',
                required=True,
            ),
            max_size_in_megabytes=dict(
                type='int',
            ),
            default_message_ttl=dict(
                type='str',
            ),
            requires_duplicate_detection=dict(
                type='bool',
            ),
            enable_partitioning=dict(
                type='bool',
            ),
            support_ordering=dict(
                type='bool',
            ),
            max_message_size_in_kilobytes=dict(
                type='int',
            ),
            state=dict(type='str', default='present', choices=['present', 'absent']),
        )

        self.resource_group = None
        self.name = None
        self.location = None
        self.namespace_name = None
        self.max_size_in_megabytes = None
        self.default_message_ttl = None
        self.requires_duplicate_detection = None
        self.enable_partitioning = None
        self.support_ordering = None
        self.max_message_size_in_kilobytes = None
        self.state = None
        self.tags = None

        self.results = dict(changed=False, state=dict())

        required_if = [
            ('state', 'present', ['resource_group', 'name']),
        ]

        super().__init__(
            derived_arg_spec=self.module_arg_spec,
            supports_check_mode=True,
            supports_tags=True,
            required_if=required_if,
        )

    def exec_module(self, **kwargs):
        for key in list(self.module_arg_spec.keys()) + ['tags']:
            setattr(self, key, kwargs[key])

        resource_group = self.resource_group
        name = self.name

        # Get existing resource
        response = self.get_resource()

        if self.state == 'present':
            if not self.location:
                rg = self.get_resource_group(resource_group)
                self.location = rg.location

            # Build the resource body from parameters
            body = self.build_body()

            if response:
                # Check if update needed
                update_tags, new_tags = self.update_tags(response.get('tags'))
                if update_tags:
                    body['tags'] = new_tags
                    self.results['changed'] = True

                if self.check_update(response, body):
                    self.results['changed'] = True

                if self.results['changed']:
                    if not self.check_mode:
                        response = self.create_or_update(resource_group, name, body)
                else:
                    response = response
            else:
                if self.tags:
                    body['tags'] = self.tags
                if not self.check_mode:
                    response = self.create_or_update(resource_group, name, body)
                self.results['changed'] = True

        elif self.state == 'absent':
            if response:
                if not self.check_mode:
                    self.delete_resource(resource_group, name)
                self.results['changed'] = True

        if response:
            self.results['state'] = self.format_response(response)

        return self.results

    def build_body(self):
        body = dict(
            location=self.location,
        )
        if self.namespace_name is not None:
            body['NamespaceName'] = self.namespace_name
        if self.max_size_in_megabytes is not None:
            body['maxSizeInMegabytes'] = self.max_size_in_megabytes
        if self.default_message_ttl is not None:
            body['defaultMessageTimeToLive'] = self.default_message_ttl
        if self.requires_duplicate_detection is not None:
            body['requiresDuplicateDetection'] = self.requires_duplicate_detection
        if self.enable_partitioning is not None:
            body['enablePartitioning'] = self.enable_partitioning
        if self.support_ordering is not None:
            body['supportOrdering'] = self.support_ordering
        if self.max_message_size_in_kilobytes is not None:
            body['maxMessageSizeInKilobytes'] = self.max_message_size_in_kilobytes

        if self.tags:
            body['tags'] = self.tags

        return body

    def check_update(self, existing, desired):
        """Compare existing resource with desired state."""
        # Check namespace_name
        if self.namespace_name is not None:
            if existing.get('NamespaceName') != self.namespace_name:
                return True
        # Check max_size_in_megabytes
        if self.max_size_in_megabytes is not None:
            if existing.get('maxSizeInMegabytes') != self.max_size_in_megabytes:
                return True
        # Check default_message_ttl
        if self.default_message_ttl is not None:
            if existing.get('defaultMessageTimeToLive') != self.default_message_ttl:
                return True
        # Check requires_duplicate_detection
        if self.requires_duplicate_detection is not None:
            if existing.get('requiresDuplicateDetection') != self.requires_duplicate_detection:
                return True
        # Check enable_partitioning
        if self.enable_partitioning is not None:
            if existing.get('enablePartitioning') != self.enable_partitioning:
                return True
        # Check support_ordering
        if self.support_ordering is not None:
            if existing.get('supportOrdering') != self.support_ordering:
                return True
        # Check max_message_size_in_kilobytes
        if self.max_message_size_in_kilobytes is not None:
            if existing.get('maxMessageSizeInKilobytes') != self.max_message_size_in_kilobytes:
                return True

        return False

    def get_resource(self):
        try:
            url = self.get_resource_url()
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2022-10-01-preview'},
                None, None, [200], 0, 0,
            )
            return self.deserialize_response(response)
        except Exception:
            return None

    def create_or_update(self, resource_group, name, body):
        url = self.get_resource_url()
        response = self.mgmt_client.query(
            url, "PUT",
            {'api-version': '2022-10-01-preview'},
            None, body, [200, 201], 0, 0,
        )
        return self.deserialize_response(response)

    def delete_resource(self, resource_group, name):
        url = self.get_resource_url()
        self.mgmt_client.query(
            url, "DELETE",
            {'api-version': '2022-10-01-preview'},
            None, None, [200, 202, 204], 0, 0,
        )

    def get_resource_url(self):
        return (
            '/subscriptions/{subscription_id}'
            '/resourceGroups/{resource_group}'
            '/providers/Microsoft.ServiceBus/namespaces/topics/{name}'
        ).format(
            subscription_id=self.subscription_id,
            resource_group=self.resource_group,
            name=self.name,
        )

    def format_response(self, response):
        result = dict(
            id=response.get('id'),
            name=response.get('name'),
            location=response.get('location'),
            tags=response.get('tags'),
        )
        result['namespace_name'] = response.get('NamespaceName')
        result['max_size_in_megabytes'] = response.get('maxSizeInMegabytes')
        result['default_message_ttl'] = response.get('defaultMessageTimeToLive')
        result['requires_duplicate_detection'] = response.get('requiresDuplicateDetection')
        result['enable_partitioning'] = response.get('enablePartitioning')
        result['support_ordering'] = response.get('supportOrdering')
        result['max_message_size_in_kilobytes'] = response.get('maxMessageSizeInKilobytes')
        return result

    @staticmethod
    def deserialize_response(response):
        try:
            return json.loads(response.text)
        except (ValueError, AttributeError):
            return None


def main():
    AzureRMServiceBusTopic()


if __name__ == '__main__':
    main()
