#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2024, Azure Magic Modules Generator
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Auto-generated by Azure Magic Modules — do not edit manually

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: azure_rm_trafficmanagerprofile
version_added: "0.1.0"
short_description: Manage Azure Traffic Manager profiles.
description:
    - Create, update, or delete an Azure TrafficManagerProfile.
    - This module was auto-generated by Azure Magic Modules.
options:
    resource_group:
        description:
            - Name of the resource group.
        type: str
        required: true
    name:
        description:
            - Name of the trafficmanagerprofile.
        type: str
        required: true
    location:
        description:
            - Valid Azure location. Defaults to the location of the resource group.
        type: str
    traffic_routing_method:
        description:
            - Traffic routing method for the profile.
        type: str
        choices:
            - "Performance"
            - "Priority"
            - "Weighted"
            - "Geographic"
            - "MultiValue"
            - "Subnet"
    dns_config_relative_name:
        description:
            - Relative DNS name for the Traffic Manager profile.
        type: str
    dns_config_ttl:
        description:
            - DNS TTL in seconds.
        type: int
        default: "60"
    monitor_protocol:
        description:
            - Protocol for endpoint health monitoring.
        type: str
        choices:
            - "HTTP"
            - "HTTPS"
            - "TCP"
    monitor_port:
        description:
            - Port for endpoint health monitoring.
        type: int
    monitor_path:
        description:
            - Path for endpoint health monitoring.
        type: str
    profile_status:
        description:
            - Status of the Traffic Manager profile.
        type: str
        choices:
            - "Enabled"
            - "Disabled"
    state:
        description:
            - Assert the state of the trafficmanagerprofile.
            - Use C(present) to create or update and C(absent) to delete.
        type: str
        default: present
        choices:
            - present
            - absent
extends_documentation_fragment:
    - azure.azcollection.azure
    - azure.azcollection.azure_tags
author:
    - "Azure Magic Modules Generator (@azure-magic-modules)"
seealso:
    - description: Azure TrafficManagerProfile REST API
      link: https://learn.microsoft.com/en-us/azure/traffic-manager/traffic-manager-overview
'''

EXAMPLES = r'''
- name: Create TrafficManagerProfile
  azure_rm_trafficmanagerprofile:
    resource_group: myResourceGroup
    name: myTrafficManagerProfile
    location: eastus
    state: present

- name: Delete TrafficManagerProfile
  azure_rm_trafficmanagerprofile:
    resource_group: myResourceGroup
    name: myTrafficManagerProfile
    state: absent
'''

RETURN = r'''
state:
    description: Current state of the trafficmanagerprofile.
    returned: always
    type: dict
    contains:
        id:
            description: Resource ID.
            type: str
        name:
            description: Resource name.
            type: str
        location:
            description: Resource location.
            type: str
        tags:
            description: Resource tags.
            type: dict
        traffic_routing_method:
            description: Traffic routing method for the profile.
            type: str
        dns_config_relative_name:
            description: Relative DNS name for the Traffic Manager profile.
            type: str
        dns_config_ttl:
            description: DNS TTL in seconds.
            type: int
        monitor_protocol:
            description: Protocol for endpoint health monitoring.
            type: str
        monitor_port:
            description: Port for endpoint health monitoring.
            type: int
        monitor_path:
            description: Path for endpoint health monitoring.
            type: str
        profile_status:
            description: Status of the Traffic Manager profile.
            type: str
'''

import json
from ansible_collections.azure.azcollection.plugins.module_utils.azure_rm_common import AzureRMModuleBase


class AzureRMTrafficManagerProfile(AzureRMModuleBase):

    def __init__(self):
        self.module_arg_spec = dict(
            resource_group=dict(type='str', required=True, aliases=['resource_group_name']),
            name=dict(type='str', required=True),
            location=dict(type='str'),
            traffic_routing_method=dict(
                type='str',
                choices=['Performance', 'Priority', 'Weighted', 'Geographic', 'MultiValue', 'Subnet'],
            ),
            dns_config_relative_name=dict(
                type='str',
            ),
            dns_config_ttl=dict(
                type='int',
                default=60,
            ),
            monitor_protocol=dict(
                type='str',
                choices=['HTTP', 'HTTPS', 'TCP'],
            ),
            monitor_port=dict(
                type='int',
            ),
            monitor_path=dict(
                type='str',
            ),
            profile_status=dict(
                type='str',
                choices=['Enabled', 'Disabled'],
            ),
            state=dict(type='str', default='present', choices=['present', 'absent']),
        )

        self.resource_group = None
        self.name = None
        self.location = None
        self.traffic_routing_method = None
        self.dns_config_relative_name = None
        self.dns_config_ttl = None
        self.monitor_protocol = None
        self.monitor_port = None
        self.monitor_path = None
        self.profile_status = None
        self.state = None
        self.tags = None

        self.results = dict(changed=False, state=dict())

        required_if = [
            ('state', 'present', ['resource_group', 'name']),
        ]

        super().__init__(
            derived_arg_spec=self.module_arg_spec,
            supports_check_mode=True,
            supports_tags=True,
            required_if=required_if,
        )

    def exec_module(self, **kwargs):
        for key in list(self.module_arg_spec.keys()) + ['tags']:
            setattr(self, key, kwargs[key])

        resource_group = self.resource_group
        name = self.name

        # Get existing resource
        response = self.get_resource()

        if self.state == 'present':
            if not self.location:
                rg = self.get_resource_group(resource_group)
                self.location = rg.location

            # Build the resource body from parameters
            body = self.build_body()

            if response:
                # Check if update needed
                update_tags, new_tags = self.update_tags(response.get('tags'))
                if update_tags:
                    body['tags'] = new_tags
                    self.results['changed'] = True

                if self.check_update(response, body):
                    self.results['changed'] = True

                if self.results['changed']:
                    if not self.check_mode:
                        response = self.create_or_update(resource_group, name, body)
                else:
                    response = response
            else:
                if self.tags:
                    body['tags'] = self.tags
                if not self.check_mode:
                    response = self.create_or_update(resource_group, name, body)
                self.results['changed'] = True

        elif self.state == 'absent':
            if response:
                if not self.check_mode:
                    self.delete_resource(resource_group, name)
                self.results['changed'] = True

        if response:
            self.results['state'] = self.format_response(response)

        return self.results

    def build_body(self):
        body = dict(
            location=self.location,
        )
        if self.traffic_routing_method is not None:
            body['trafficRoutingMethod'] = self.traffic_routing_method
        if self.dns_config_relative_name is not None:
            _target = body
            _target = _target.setdefault('dnsConfig', {})
            _target['relativeName'] = self.dns_config_relative_name
        if self.dns_config_ttl is not None:
            _target = body
            _target = _target.setdefault('dnsConfig', {})
            _target['ttl'] = self.dns_config_ttl
        if self.monitor_protocol is not None:
            _target = body
            _target = _target.setdefault('monitorConfig', {})
            _target['protocol'] = self.monitor_protocol
        if self.monitor_port is not None:
            _target = body
            _target = _target.setdefault('monitorConfig', {})
            _target['port'] = self.monitor_port
        if self.monitor_path is not None:
            _target = body
            _target = _target.setdefault('monitorConfig', {})
            _target['path'] = self.monitor_path
        if self.profile_status is not None:
            body['profileStatus'] = self.profile_status

        if self.tags:
            body['tags'] = self.tags

        return body

    def check_update(self, existing, desired):
        """Compare existing resource with desired state."""
        # Check traffic_routing_method
        if self.traffic_routing_method is not None:
            if existing.get('trafficRoutingMethod') != self.traffic_routing_method:
                return True
        # Check dns_config_relative_name
        if self.dns_config_relative_name is not None:
            _existing = existing
            _existing = _existing.get('dnsConfig', {}) if isinstance(_existing, dict) else {}
            if _existing.get('relativeName') != self.dns_config_relative_name:
                return True
        # Check dns_config_ttl
        if self.dns_config_ttl is not None:
            _existing = existing
            _existing = _existing.get('dnsConfig', {}) if isinstance(_existing, dict) else {}
            if _existing.get('ttl') != self.dns_config_ttl:
                return True
        # Check monitor_protocol
        if self.monitor_protocol is not None:
            _existing = existing
            _existing = _existing.get('monitorConfig', {}) if isinstance(_existing, dict) else {}
            if _existing.get('protocol') != self.monitor_protocol:
                return True
        # Check monitor_port
        if self.monitor_port is not None:
            _existing = existing
            _existing = _existing.get('monitorConfig', {}) if isinstance(_existing, dict) else {}
            if _existing.get('port') != self.monitor_port:
                return True
        # Check monitor_path
        if self.monitor_path is not None:
            _existing = existing
            _existing = _existing.get('monitorConfig', {}) if isinstance(_existing, dict) else {}
            if _existing.get('path') != self.monitor_path:
                return True
        # Check profile_status
        if self.profile_status is not None:
            if existing.get('profileStatus') != self.profile_status:
                return True

        return False

    def get_resource(self):
        try:
            url = self.get_resource_url()
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2024-03-01'},
                None, None, [200], 0, 0,
            )
            return self.deserialize_response(response)
        except Exception:
            return None

    def create_or_update(self, resource_group, name, body):
        url = self.get_resource_url()
        response = self.mgmt_client.query(
            url, "PUT",
            {'api-version': '2024-03-01'},
            None, body, [200, 201], 0, 0,
        )
        return self.deserialize_response(response)

    def delete_resource(self, resource_group, name):
        url = self.get_resource_url()
        self.mgmt_client.query(
            url, "DELETE",
            {'api-version': '2024-03-01'},
            None, None, [200, 202, 204], 0, 0,
        )

    def get_resource_url(self):
        return (
            '/subscriptions/{subscription_id}'
            '/resourceGroups/{resource_group}'
            '/providers/Microsoft.Network/trafficmanagerprofiles/{name}'
        ).format(
            subscription_id=self.subscription_id,
            resource_group=self.resource_group,
            name=self.name,
        )

    def format_response(self, response):
        result = dict(
            id=response.get('id'),
            name=response.get('name'),
            location=response.get('location'),
            tags=response.get('tags'),
        )
        result['traffic_routing_method'] = response.get('trafficRoutingMethod')
        _body = response
        _body = _body.get('dnsConfig', {}) if isinstance(_body, dict) else {}
        result['dns_config_relative_name'] = _body.get('relativeName')
        _body = response
        _body = _body.get('dnsConfig', {}) if isinstance(_body, dict) else {}
        result['dns_config_ttl'] = _body.get('ttl')
        _body = response
        _body = _body.get('monitorConfig', {}) if isinstance(_body, dict) else {}
        result['monitor_protocol'] = _body.get('protocol')
        _body = response
        _body = _body.get('monitorConfig', {}) if isinstance(_body, dict) else {}
        result['monitor_port'] = _body.get('port')
        _body = response
        _body = _body.get('monitorConfig', {}) if isinstance(_body, dict) else {}
        result['monitor_path'] = _body.get('path')
        result['profile_status'] = response.get('profileStatus')
        return result

    @staticmethod
    def deserialize_response(response):
        try:
            return json.loads(response.text)
        except (ValueError, AttributeError):
            return None


def main():
    AzureRMTrafficManagerProfile()


if __name__ == '__main__':
    main()
