#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2024, Azure Magic Modules Generator
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Auto-generated by Azure Magic Modules — do not edit manually

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: azure_rm_cosmosdbaccount
version_added: "0.1.0"
short_description: Manage Azure Cosmos DB account instances.
description:
    - Create, update, or delete an Azure CosmosDbAccount.
    - This module was auto-generated by Azure Magic Modules.
options:
    resource_group:
        description:
            - Name of the resource group.
        type: str
        required: true
    name:
        description:
            - Name of the cosmosdbaccount.
        type: str
        required: true
    location:
        description:
            - Valid Azure location. Defaults to the location of the resource group.
        type: str
    kind:
        description:
            - Kind of the Cosmos DB account.
        type: str
        choices:
            - "GlobalDocumentDB"
            - "MongoDB"
            - "Parse"
    consistency_level:
        description:
            - Default consistency level for the account.
        type: str
        choices:
            - "Strong"
            - "BoundedStaleness"
            - "Session"
            - "ConsistentPrefix"
            - "Eventual"
    geo_locations:
        description:
            - List of geo-replication locations for the account.
        type: list
        suboptions:
            location_name:
                description:
                    - Name of the Azure region.
                type: str
                required: true
            failover_priority:
                description:
                    - Failover priority of the region.
                type: int
                required: true
            is_zone_redundant:
                description:
                    - Whether the region is zone redundant.
                type: bool
    enable_automatic_failover:
        description:
            - Enable automatic failover for the account.
        type: bool
    enable_free_tier:
        description:
            - Enable free tier for the account.
        type: bool
    database_account_offer_type:
        description:
            - Offer type for the database account.
        type: str
        default: "Standard"
    state:
        description:
            - Assert the state of the cosmosdbaccount.
            - Use C(present) to create or update and C(absent) to delete.
        type: str
        default: present
        choices:
            - present
            - absent
extends_documentation_fragment:
    - azure.azcollection.azure
    - azure.azcollection.azure_tags
author:
    - "Azure Magic Modules Generator (@azure-magic-modules)"
seealso:
    - description: Azure CosmosDbAccount REST API
      link: https://learn.microsoft.com/en-us/azure/cosmos-db/introduction
'''

EXAMPLES = r'''
- name: Create CosmosDbAccount
  azure_rm_cosmosdbaccount:
    resource_group: myResourceGroup
    name: myCosmosDbAccount
    location: eastus
    state: present

- name: Delete CosmosDbAccount
  azure_rm_cosmosdbaccount:
    resource_group: myResourceGroup
    name: myCosmosDbAccount
    state: absent
'''

RETURN = r'''
state:
    description: Current state of the cosmosdbaccount.
    returned: always
    type: dict
    contains:
        id:
            description: Resource ID.
            type: str
        name:
            description: Resource name.
            type: str
        location:
            description: Resource location.
            type: str
        tags:
            description: Resource tags.
            type: dict
        kind:
            description: Kind of the Cosmos DB account.
            type: str
        consistency_level:
            description: Default consistency level for the account.
            type: str
        geo_locations:
            description: List of geo-replication locations for the account.
            type: list
        enable_automatic_failover:
            description: Enable automatic failover for the account.
            type: bool
        enable_free_tier:
            description: Enable free tier for the account.
            type: bool
        database_account_offer_type:
            description: Offer type for the database account.
            type: str
'''

import json
from ansible_collections.azure.azcollection.plugins.module_utils.azure_rm_common import AzureRMModuleBase


class AzureRMCosmosDbAccount(AzureRMModuleBase):

    def __init__(self):
        self.module_arg_spec = dict(
            resource_group=dict(type='str', required=True, aliases=['resource_group_name']),
            name=dict(type='str', required=True),
            location=dict(type='str'),
            kind=dict(
                type='str',
                choices=['GlobalDocumentDB', 'MongoDB', 'Parse'],
            ),
            consistency_level=dict(
                type='str',
                choices=['Strong', 'BoundedStaleness', 'Session', 'ConsistentPrefix', 'Eventual'],
            ),
            geo_locations=dict(
                type='list',
                options=dict(
                    location_name=dict(
                        type='str',
                        required=True,
                    ),
                    failover_priority=dict(
                        type='int',
                        required=True,
                    ),
                    is_zone_redundant=dict(
                        type='bool',
                    ),
                ),
            ),
            enable_automatic_failover=dict(
                type='bool',
            ),
            enable_free_tier=dict(
                type='bool',
            ),
            database_account_offer_type=dict(
                type='str',
                default='Standard',
            ),
            state=dict(type='str', default='present', choices=['present', 'absent']),
        )

        self.resource_group = None
        self.name = None
        self.location = None
        self.kind = None
        self.consistency_level = None
        self.geo_locations = None
        self.enable_automatic_failover = None
        self.enable_free_tier = None
        self.database_account_offer_type = None
        self.state = None
        self.tags = None

        self.results = dict(changed=False, state=dict())

        required_if = [
            ('state', 'present', ['resource_group', 'name']),
        ]

        super().__init__(
            derived_arg_spec=self.module_arg_spec,
            supports_check_mode=True,
            supports_tags=True,
            required_if=required_if,
        )

    def exec_module(self, **kwargs):
        for key in list(self.module_arg_spec.keys()) + ['tags']:
            setattr(self, key, kwargs[key])

        resource_group = self.resource_group
        name = self.name

        # Get existing resource
        response = self.get_resource()

        if self.state == 'present':
            if not self.location:
                rg = self.get_resource_group(resource_group)
                self.location = rg.location

            # Build the resource body from parameters
            body = self.build_body()

            if response:
                # Check if update needed
                update_tags, new_tags = self.update_tags(response.get('tags'))
                if update_tags:
                    body['tags'] = new_tags
                    self.results['changed'] = True

                if self.check_update(response, body):
                    self.results['changed'] = True

                if self.results['changed']:
                    if not self.check_mode:
                        response = self.create_or_update(resource_group, name, body)
                else:
                    response = response
            else:
                if self.tags:
                    body['tags'] = self.tags
                if not self.check_mode:
                    response = self.create_or_update(resource_group, name, body)
                self.results['changed'] = True

        elif self.state == 'absent':
            if response:
                if not self.check_mode:
                    self.delete_resource(resource_group, name)
                self.results['changed'] = True

        if response:
            self.results['state'] = self.format_response(response)

        return self.results

    def build_body(self):
        body = dict(
            location=self.location,
        )
        if self.kind is not None:
            body['kind'] = self.kind

        properties = body.setdefault('properties', {})
        if self.consistency_level is not None:
            properties['defaultConsistencyLevel'] = self.consistency_level
        if self.geo_locations is not None:
            properties['locations'] = self.geo_locations
        if self.enable_automatic_failover is not None:
            properties['enableAutomaticFailover'] = self.enable_automatic_failover
        if self.enable_free_tier is not None:
            properties['enableFreeTier'] = self.enable_free_tier
        if self.database_account_offer_type is not None:
            properties['databaseAccountOfferType'] = self.database_account_offer_type

        if self.tags:
            body['tags'] = self.tags

        return body

    def check_update(self, existing, desired):
        """Compare existing resource with desired state."""
        # Check kind
        if self.kind is not None:
            if existing.get('kind') != self.kind:
                return True
        # Check consistency_level
        if self.consistency_level is not None:
            if existing.get('properties', {}).get('defaultConsistencyLevel') != self.consistency_level:
                return True
        # Check geo_locations
        if self.geo_locations is not None:
            if existing.get('properties', {}).get('locations') != self.geo_locations:
                return True
        # Check enable_automatic_failover
        if self.enable_automatic_failover is not None:
            if existing.get('properties', {}).get('enableAutomaticFailover') != self.enable_automatic_failover:
                return True
        # Check enable_free_tier
        if self.enable_free_tier is not None:
            if existing.get('properties', {}).get('enableFreeTier') != self.enable_free_tier:
                return True
        # Check database_account_offer_type
        if self.database_account_offer_type is not None:
            if existing.get('properties', {}).get('databaseAccountOfferType') != self.database_account_offer_type:
                return True

        return False

    def get_resource(self):
        try:
            url = self.get_resource_url()
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2024-05-15'},
                None, None, [200], 0, 0,
            )
            return self.deserialize_response(response)
        except Exception:
            return None

    def create_or_update(self, resource_group, name, body):
        url = self.get_resource_url()
        response = self.mgmt_client.query(
            url, "PUT",
            {'api-version': '2024-05-15'},
            None, body, [200, 201], 0, 0,
        )
        return self.deserialize_response(response)

    def delete_resource(self, resource_group, name):
        url = self.get_resource_url()
        self.mgmt_client.query(
            url, "DELETE",
            {'api-version': '2024-05-15'},
            None, None, [200, 202, 204], 0, 0,
        )

    def get_resource_url(self):
        return (
            '/subscriptions/{subscription_id}'
            '/resourceGroups/{resource_group}'
            '/providers/Microsoft.DocumentDB/databaseAccounts/{name}'
        ).format(
            subscription_id=self.subscription_id,
            resource_group=self.resource_group,
            name=self.name,
        )

    def format_response(self, response):
        result = dict(
            id=response.get('id'),
            name=response.get('name'),
            location=response.get('location'),
            tags=response.get('tags'),
        )
        result['kind'] = response.get('kind')
        result['consistency_level'] = response.get('properties', {}).get('defaultConsistencyLevel')
        result['geo_locations'] = response.get('properties', {}).get('locations')
        result['enable_automatic_failover'] = response.get('properties', {}).get('enableAutomaticFailover')
        result['enable_free_tier'] = response.get('properties', {}).get('enableFreeTier')
        result['database_account_offer_type'] = response.get('properties', {}).get('databaseAccountOfferType')
        return result

    @staticmethod
    def deserialize_response(response):
        try:
            return json.loads(response.text)
        except (ValueError, AttributeError):
            return None


def main():
    AzureRMCosmosDbAccount()


if __name__ == '__main__':
    main()
