#!/usr/bin/python
# -*- coding: utf-8 -*-
# Auto-generated by Azure Magic Modules — do not edit manually

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: azure_rm_manageddisk
version_added: "0.1.0"
short_description: Manage Azure managed disks
description:
    - Create, update, or delete an Azure ManagedDisk.
    - This module was auto-generated by Azure Magic Modules.
options:
    resource_group:
        description:
            - Name of the resource group.
        type: str
        required: true
    name:
        description:
            - Name of the manageddisk.
        type: str
        required: true
    location:
        description:
            - Valid Azure location. Defaults to the location of the resource group.
        type: str
    disk_size_gb:
        description:
            - Size of the managed disk in gigabytes.
        type: int
        required: true
    sku:
        description:
            - The SKU name for the managed disk, determining storage type and performance tier.
        type: str
        choices:
            - Standard_LRS
            - Premium_LRS
            - StandardSSD_LRS
            - UltraSSD_LRS
            - Premium_ZRS
    create_option:
        description:
            - Specifies how the managed disk is to be created.
        type: str
        default: Empty
        choices:
            - Empty
            - Copy
            - Import
            - FromImage
    source_uri:
        description:
            - URI to the source blob for Import create option, or resource ID for Copy create option.
        type: str
    os_type:
        description:
            - The operating system type of the disk.
        type: str
        choices:
            - Linux
            - Windows
    zone:
        description:
            - The availability zone where the managed disk will be created.
        type: str
    state:
        description:
            - Assert the state of the manageddisk.
            - Use C(present) to create or update and C(absent) to delete.
        type: str
        default: present
        choices:
            - present
            - absent
extends_documentation_fragment:
    - azure.azcollection.azure
    - azure.azcollection.azure_tags
author:
    - "Azure Magic Modules Generator"
seealso:
    - name: Azure ManagedDisk REST API
      link: https://learn.microsoft.com/en-us/rest/api/compute/disks
'''

EXAMPLES = r'''
- name: Create ManagedDisk
  azure_rm_manageddisk:
    resource_group: myResourceGroup
    name: myManagedDisk
    location: eastus
    disk_size_gb: 1
    state: present

- name: Delete ManagedDisk
  azure_rm_manageddisk:
    resource_group: myResourceGroup
    name: myManagedDisk
    state: absent
'''

RETURN = r'''
state:
    description: Current state of the manageddisk.
    returned: always
    type: dict
    contains:
        id:
            description: Resource ID.
            type: str
        name:
            description: Resource name.
            type: str
        location:
            description: Resource location.
            type: str
        tags:
            description: Resource tags.
            type: dict
        disk_size_gb:
            description: Size of the managed disk in gigabytes.
            type: int
        sku:
            description: The SKU name for the managed disk, determining storage type and performance tier.
            type: str
        create_option:
            description: Specifies how the managed disk is to be created.
            type: str
        source_uri:
            description: URI to the source blob for Import create option, or resource ID for Copy create option.
            type: str
        os_type:
            description: The operating system type of the disk.
            type: str
        zone:
            description: The availability zone where the managed disk will be created.
            type: str
'''

import json
from ansible_collections.azure.azcollection.plugins.module_utils.azure_rm_common import AzureRMModuleBase


class AzureRMManagedDisk(AzureRMModuleBase):

    def __init__(self):
        self.module_arg_spec = dict(
            resource_group=dict(type='str', required=True, aliases=['resource_group_name']),
            name=dict(type='str', required=True),
            location=dict(type='str'),
            disk_size_gb=dict(
                type='int',
                required=True,
            ),
            sku=dict(
                type='str',
                choices=["Standard_LRS", "Premium_LRS", "StandardSSD_LRS", "UltraSSD_LRS", "Premium_ZRS"],
            ),
            create_option=dict(
                type='str',
                default='Empty',
                choices=["Empty", "Copy", "Import", "FromImage"],
            ),
            source_uri=dict(
                type='str',
            ),
            os_type=dict(
                type='str',
                choices=["Linux", "Windows"],
            ),
            zone=dict(
                type='str',
            ),
            state=dict(type='str', default='present', choices=['present', 'absent']),
        )

        self.resource_group = None
        self.name = None
        self.location = None
        self.disk_size_gb = None
        self.sku = None
        self.create_option = None
        self.source_uri = None
        self.os_type = None
        self.zone = None
        self.state = None
        self.tags = None

        self.results = dict(changed=False, state=dict())

        required_if = [
            ('state', 'present', ['resource_group', 'name']),
        ]

        super().__init__(
            derived_arg_spec=self.module_arg_spec,
            supports_check_mode=True,
            supports_tags=True,
            required_if=required_if,
        )

    def exec_module(self, **kwargs):
        for key in list(self.module_arg_spec.keys()) + ['tags']:
            setattr(self, key, kwargs[key])

        resource_group = self.resource_group
        name = self.name

        # Get existing resource
        response = self.get_resource()

        if self.state == 'present':
            if not self.location:
                rg = self.get_resource_group(resource_group)
                self.location = rg.location

            # Build the resource body from parameters
            body = self.build_body()

            if response:
                # Check if update needed
                update_tags, new_tags = self.update_tags(response.get('tags'))
                if update_tags:
                    body['tags'] = new_tags
                    self.results['changed'] = True

                if self.check_update(response, body):
                    self.results['changed'] = True

                if self.results['changed']:
                    if not self.check_mode:
                        response = self.create_or_update(resource_group, name, body)
                else:
                    response = response
            else:
                if self.tags:
                    body['tags'] = self.tags
                if not self.check_mode:
                    response = self.create_or_update(resource_group, name, body)
                self.results['changed'] = True

        elif self.state == 'absent':
            if response:
                if not self.check_mode:
                    self.delete_resource(resource_group, name)
                self.results['changed'] = True

        if response:
            self.results['state'] = self.format_response(response)

        return self.results

    def build_body(self):
        body = dict(
            location=self.location,
        )
        if self.sku is not None:
            _target = body
            _target = _target.setdefault('sku', {})
            _target['name'] = self.sku
        if self.zone is not None:
            body['zones'] = self.zone

        properties = body.setdefault('properties', {})
        if self.disk_size_gb is not None:
            properties['diskSizeGB'] = self.disk_size_gb
        if self.create_option is not None:
            _target = properties
            _target = _target.setdefault('creationData', {})
            _target['createOption'] = self.create_option
        if self.source_uri is not None:
            _target = properties
            _target = _target.setdefault('creationData', {})
            _target['sourceUri'] = self.source_uri
        if self.os_type is not None:
            properties['osType'] = self.os_type

        if self.tags:
            body['tags'] = self.tags

        return body

    def check_update(self, existing, desired):
        """Compare existing resource with desired state."""
        # Check disk_size_gb
        if self.disk_size_gb is not None:
            if existing.get('properties', {}).get('diskSizeGB') != self.disk_size_gb:
                return True
        # Check sku
        if self.sku is not None:
            _existing = existing
            _existing = _existing.get('sku', {}) if isinstance(_existing, dict) else {}
            if _existing.get('name') != self.sku:
                return True
        # Check create_option
        if self.create_option is not None:
            _existing = existing.get('properties', {})
            _existing = _existing.get('creationData', {}) if isinstance(_existing, dict) else {}
            if _existing.get('createOption') != self.create_option:
                return True
        # Check source_uri
        if self.source_uri is not None:
            _existing = existing.get('properties', {})
            _existing = _existing.get('creationData', {}) if isinstance(_existing, dict) else {}
            if _existing.get('sourceUri') != self.source_uri:
                return True
        # Check os_type
        if self.os_type is not None:
            if existing.get('properties', {}).get('osType') != self.os_type:
                return True
        # Check zone
        if self.zone is not None:
            if existing.get('zones') != self.zone:
                return True

        return False

    def get_resource(self):
        try:
            url = self.get_resource_url()
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2024-03-02'},
                None, None, [200], 0, 0,
            )
            return self.deserialize_response(response)
        except Exception:
            return None

    def create_or_update(self, resource_group, name, body):
        url = self.get_resource_url()
        response = self.mgmt_client.query(
            url, "PUT",
            {'api-version': '2024-03-02'},
            None, body, [200, 201], 0, 0,
        )
        return self.deserialize_response(response)

    def delete_resource(self, resource_group, name):
        url = self.get_resource_url()
        self.mgmt_client.query(
            url, "DELETE",
            {'api-version': '2024-03-02'},
            None, None, [200, 202, 204], 0, 0,
        )

    def get_resource_url(self):
        return (
            '/subscriptions/{subscription_id}'
            '/resourceGroups/{resource_group}'
            '/providers/Microsoft.Compute/disks/{name}'
        ).format(
            subscription_id=self.subscription_id,
            resource_group=self.resource_group,
            name=self.name,
        )

    def format_response(self, response):
        result = dict(
            id=response.get('id'),
            name=response.get('name'),
            location=response.get('location'),
            tags=response.get('tags'),
        )
        result['disk_size_gb'] = response.get('properties', {}).get('diskSizeGB')
        _body = response
        _body = _body.get('sku', {}) if isinstance(_body, dict) else {}
        result['sku'] = _body.get('name')
        _props = response.get('properties', {})
        _props = _props.get('creationData', {}) if isinstance(_props, dict) else {}
        result['create_option'] = _props.get('createOption')
        _props = response.get('properties', {})
        _props = _props.get('creationData', {}) if isinstance(_props, dict) else {}
        result['source_uri'] = _props.get('sourceUri')
        result['os_type'] = response.get('properties', {}).get('osType')
        result['zone'] = response.get('zones')
        return result

    @staticmethod
    def deserialize_response(response):
        try:
            return json.loads(response.text)
        except (ValueError, AttributeError):
            return None


def main():
    AzureRMManagedDisk()


if __name__ == '__main__':
    main()
