#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2024, Azure Magic Modules Generator
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Auto-generated by Azure Magic Modules — do not edit manually

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: azure_rm_recoveryservicesvault_info
version_added: "0.1.0"
short_description: Get facts for Azure RecoveryServicesVault
description:
    - Get facts for a specific RecoveryServicesVault or list all RecoveryServicesVaults in a resource group.
    - This module was auto-generated by Azure Magic Modules.
options:
    resource_group:
        description:
            - Name of the resource group.
        type: str
        required: true
    name:
        description:
            - Name of the recoveryservicesvault.
            - If not specified, all recoveryservicesvaults in the resource group will be listed.
        type: str
extends_documentation_fragment:
    - azure.azcollection.azure
    - azure.azcollection.azure_tags
author:
    - "Azure Magic Modules Generator (@azure-magic-modules)"
seealso:
    - description: Azure RecoveryServicesVault REST API
      link: https://learn.microsoft.com/en-us/azure/backup/backup-azure-recovery-services-vault-overview
'''

EXAMPLES = r'''
- name: Get facts for a specific RecoveryServicesVault
  azure_rm_recoveryservicesvault_info:
    resource_group: myResourceGroup
    name: myRecoveryServicesVault

- name: List all RecoveryServicesVaults in a resource group
  azure_rm_recoveryservicesvault_info:
    resource_group: myResourceGroup
'''

RETURN = r'''
recoveryservicesvaults:
    description:
        - List of recoveryservicesvault dicts.
    returned: always
    type: list
    elements: dict
    contains:
        id:
            description: Resource ID.
            type: str
        name:
            description: Resource name.
            type: str
        location:
            description: Resource location.
            type: str
        tags:
            description: Resource tags.
            type: dict
        sku_name:
            description: SKU name of the vault.
            type: str
        identity_type:
            description: Type of managed identity for the vault.
            type: str
        public_network_access:
            description: Whether public network access is allowed.
            type: str
        immutability_state:
            description: Immutability state of the vault.
            type: str
        cross_subscription_restore_state:
            description: Cross subscription restore state of the vault.
            type: str
        soft_delete_retention_in_days:
            description: Soft delete retention period in days.
            type: int
'''

import json
from ansible_collections.azure.azcollection.plugins.module_utils.azure_rm_common import AzureRMModuleBase


class AzureRMRecoveryServicesVaultInfo(AzureRMModuleBase):

    def __init__(self):
        self.module_arg_spec = dict(
            resource_group=dict(type='str', required=True, aliases=['resource_group_name']),
            name=dict(type='str'),
        )

        self.resource_group = None
        self.name = None
        self.tags = None

        self.results = dict(
            changed=False,
            recoveryservicesvaults=[],
        )

        super().__init__(
            derived_arg_spec=self.module_arg_spec,
            supports_check_mode=True,
            supports_tags=False,
            facts_module=True,
        )

    def exec_module(self, **kwargs):
        for key in list(self.module_arg_spec.keys()) + ['tags']:
            setattr(self, key, kwargs[key])

        result_key = 'recoveryservicesvaults'

        if self.name:
            response = self.get_resource()
            if response:
                if self.has_tags(response.get('tags'), self.tags):
                    self.results[result_key] = [self.format_response(response)]
        else:
            responses = self.list_by_resource_group()
            for item in responses:
                if self.has_tags(item.get('tags'), self.tags):
                    self.results[result_key].append(self.format_response(item))

        return self.results

    def get_resource(self):
        try:
            url = (
                '/subscriptions/{subscription_id}'
                '/resourceGroups/{resource_group}'
                '/providers/Microsoft.RecoveryServices/vaults/{name}'
            ).format(
                subscription_id=self.subscription_id,
                resource_group=self.resource_group,
                name=self.name,
            )
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2024-04-01'},
                None, None, [200], 0, 0,
            )
            return self.deserialize_response(response)
        except Exception:
            return None

    def list_by_resource_group(self):
        try:
            url = (
                '/subscriptions/{subscription_id}'
                '/resourceGroups/{resource_group}'
                '/providers/Microsoft.RecoveryServices/vaults'
            ).format(
                subscription_id=self.subscription_id,
                resource_group=self.resource_group,
            )
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2024-04-01'},
                None, None, [200], 0, 0,
            )
            result = self.deserialize_response(response)
            if result and isinstance(result, dict):
                return result.get('value', [])
            return []
        except Exception:
            return []

    def format_response(self, response):
        result = dict(
            id=response.get('id'),
            name=response.get('name'),
            location=response.get('location'),
            tags=response.get('tags'),
        )
        _body = response
        _body = _body.get('sku', {}) if isinstance(_body, dict) else {}
        result['sku_name'] = _body.get('name')
        _body = response
        _body = _body.get('identity', {}) if isinstance(_body, dict) else {}
        result['identity_type'] = _body.get('type')
        result['public_network_access'] = response.get('publicNetworkAccess')
        _body = response
        _body = _body.get('immutabilitySettings', {}) if isinstance(_body, dict) else {}
        result['immutability_state'] = _body.get('immutabilityState')
        _body = response
        _body = _body.get('restoreSettings', {}) if isinstance(_body, dict) else {}
        _body = _body.get('crossSubscriptionRestoreSettings', {}) if isinstance(_body, dict) else {}
        result['cross_subscription_restore_state'] = _body.get('crossSubscriptionRestoreState')
        _body = response
        _body = _body.get('softDeleteSettings', {}) if isinstance(_body, dict) else {}
        result['soft_delete_retention_in_days'] = _body.get('softDeleteRetentionPeriodInDays')
        return result

    @staticmethod
    def deserialize_response(response):
        try:
            return json.loads(response.text)
        except (ValueError, AttributeError):
            return None


def main():
    AzureRMRecoveryServicesVaultInfo()


if __name__ == '__main__':
    main()
