#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2024, Azure Magic Modules Generator
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Auto-generated by Azure Magic Modules — do not edit manually

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: azure_rm_firewallpolicy
version_added: "0.1.0"
short_description: Manage Azure firewall policies.
description:
    - Create, update, or delete an Azure FirewallPolicy.
    - This module was auto-generated by Azure Magic Modules.
options:
    resource_group:
        description:
            - Name of the resource group.
        type: str
        required: true
    name:
        description:
            - Name of the firewallpolicy.
        type: str
        required: true
    location:
        description:
            - Valid Azure location. Defaults to the location of the resource group.
        type: str
    sku_tier:
        description:
            - SKU tier of the firewall policy.
        type: str
        choices:
            - "Standard"
            - "Premium"
            - "Basic"
    threat_intel_mode:
        description:
            - Threat intelligence operation mode.
        type: str
        choices:
            - "Alert"
            - "Deny"
            - "Off"
    dns_servers:
        description:
            - List of custom DNS server IP addresses.
        type: list
    enable_dns_proxy:
        description:
            - Enable DNS proxy on the firewall policy.
        type: bool
    state:
        description:
            - Assert the state of the firewallpolicy.
            - Use C(present) to create or update and C(absent) to delete.
        type: str
        default: present
        choices:
            - present
            - absent
extends_documentation_fragment:
    - azure.azcollection.azure
    - azure.azcollection.azure_tags
author:
    - "Azure Magic Modules Generator (@azure-magic-modules)"
seealso:
    - description: Azure FirewallPolicy REST API
      link: https://learn.microsoft.com/en-us/azure/firewall/policy-rule-sets
'''

EXAMPLES = r'''
- name: Create FirewallPolicy
  azure_rm_firewallpolicy:
    resource_group: myResourceGroup
    name: myFirewallPolicy
    location: eastus
    state: present

- name: Delete FirewallPolicy
  azure_rm_firewallpolicy:
    resource_group: myResourceGroup
    name: myFirewallPolicy
    state: absent
'''

RETURN = r'''
state:
    description: Current state of the firewallpolicy.
    returned: always
    type: dict
    contains:
        id:
            description: Resource ID.
            type: str
        name:
            description: Resource name.
            type: str
        location:
            description: Resource location.
            type: str
        tags:
            description: Resource tags.
            type: dict
        sku_tier:
            description: SKU tier of the firewall policy.
            type: str
        threat_intel_mode:
            description: Threat intelligence operation mode.
            type: str
        dns_servers:
            description: List of custom DNS server IP addresses.
            type: list
        enable_dns_proxy:
            description: Enable DNS proxy on the firewall policy.
            type: bool
'''

import json
from ansible_collections.azure.azcollection.plugins.module_utils.azure_rm_common import AzureRMModuleBase


class AzureRMFirewallPolicy(AzureRMModuleBase):

    def __init__(self):
        self.module_arg_spec = dict(
            resource_group=dict(type='str', required=True, aliases=['resource_group_name']),
            name=dict(type='str', required=True),
            location=dict(type='str'),
            sku_tier=dict(
                type='str',
                choices=['Standard', 'Premium', 'Basic'],
            ),
            threat_intel_mode=dict(
                type='str',
                choices=['Alert', 'Deny', 'Off'],
            ),
            dns_servers=dict(
                type='list',
            ),
            enable_dns_proxy=dict(
                type='bool',
            ),
            state=dict(type='str', default='present', choices=['present', 'absent']),
        )

        self.resource_group = None
        self.name = None
        self.location = None
        self.sku_tier = None
        self.threat_intel_mode = None
        self.dns_servers = None
        self.enable_dns_proxy = None
        self.state = None
        self.tags = None

        self.results = dict(changed=False, state=dict())

        required_if = [
            ('state', 'present', ['resource_group', 'name']),
        ]

        super().__init__(
            derived_arg_spec=self.module_arg_spec,
            supports_check_mode=True,
            supports_tags=True,
            required_if=required_if,
        )

    def exec_module(self, **kwargs):
        for key in list(self.module_arg_spec.keys()) + ['tags']:
            setattr(self, key, kwargs[key])

        resource_group = self.resource_group
        name = self.name

        # Get existing resource
        response = self.get_resource()

        if self.state == 'present':
            if not self.location:
                rg = self.get_resource_group(resource_group)
                self.location = rg.location

            # Build the resource body from parameters
            body = self.build_body()

            if response:
                # Check if update needed
                update_tags, new_tags = self.update_tags(response.get('tags'))
                if update_tags:
                    body['tags'] = new_tags
                    self.results['changed'] = True

                if self.check_update(response, body):
                    self.results['changed'] = True

                if self.results['changed']:
                    if not self.check_mode:
                        response = self.create_or_update(resource_group, name, body)
                else:
                    response = response
            else:
                if self.tags:
                    body['tags'] = self.tags
                if not self.check_mode:
                    response = self.create_or_update(resource_group, name, body)
                self.results['changed'] = True

        elif self.state == 'absent':
            if response:
                if not self.check_mode:
                    self.delete_resource(resource_group, name)
                self.results['changed'] = True

        if response:
            self.results['state'] = self.format_response(response)

        return self.results

    def build_body(self):
        body = dict(
            location=self.location,
        )
        if self.sku_tier is not None:
            _target = body
            _target = _target.setdefault('sku', {})
            _target['tier'] = self.sku_tier
        if self.threat_intel_mode is not None:
            body['threatIntelMode'] = self.threat_intel_mode
        if self.dns_servers is not None:
            _target = body
            _target = _target.setdefault('dnsSettings', {})
            _target['servers'] = self.dns_servers
        if self.enable_dns_proxy is not None:
            _target = body
            _target = _target.setdefault('dnsSettings', {})
            _target['enableProxy'] = self.enable_dns_proxy

        if self.tags:
            body['tags'] = self.tags

        return body

    def check_update(self, existing, desired):
        """Compare existing resource with desired state."""
        # Check sku_tier
        if self.sku_tier is not None:
            _existing = existing
            _existing = _existing.get('sku', {}) if isinstance(_existing, dict) else {}
            if _existing.get('tier') != self.sku_tier:
                return True
        # Check threat_intel_mode
        if self.threat_intel_mode is not None:
            if existing.get('threatIntelMode') != self.threat_intel_mode:
                return True
        # Check dns_servers
        if self.dns_servers is not None:
            _existing = existing
            _existing = _existing.get('dnsSettings', {}) if isinstance(_existing, dict) else {}
            if _existing.get('servers') != self.dns_servers:
                return True
        # Check enable_dns_proxy
        if self.enable_dns_proxy is not None:
            _existing = existing
            _existing = _existing.get('dnsSettings', {}) if isinstance(_existing, dict) else {}
            if _existing.get('enableProxy') != self.enable_dns_proxy:
                return True

        return False

    def get_resource(self):
        try:
            url = self.get_resource_url()
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2024-03-01'},
                None, None, [200], 0, 0,
            )
            return self.deserialize_response(response)
        except Exception:
            return None

    def create_or_update(self, resource_group, name, body):
        url = self.get_resource_url()
        response = self.mgmt_client.query(
            url, "PUT",
            {'api-version': '2024-03-01'},
            None, body, [200, 201], 0, 0,
        )
        return self.deserialize_response(response)

    def delete_resource(self, resource_group, name):
        url = self.get_resource_url()
        self.mgmt_client.query(
            url, "DELETE",
            {'api-version': '2024-03-01'},
            None, None, [200, 202, 204], 0, 0,
        )

    def get_resource_url(self):
        return (
            '/subscriptions/{subscription_id}'
            '/resourceGroups/{resource_group}'
            '/providers/Microsoft.Network/firewallPolicies/{name}'
        ).format(
            subscription_id=self.subscription_id,
            resource_group=self.resource_group,
            name=self.name,
        )

    def format_response(self, response):
        result = dict(
            id=response.get('id'),
            name=response.get('name'),
            location=response.get('location'),
            tags=response.get('tags'),
        )
        _body = response
        _body = _body.get('sku', {}) if isinstance(_body, dict) else {}
        result['sku_tier'] = _body.get('tier')
        result['threat_intel_mode'] = response.get('threatIntelMode')
        _body = response
        _body = _body.get('dnsSettings', {}) if isinstance(_body, dict) else {}
        result['dns_servers'] = _body.get('servers')
        _body = response
        _body = _body.get('dnsSettings', {}) if isinstance(_body, dict) else {}
        result['enable_dns_proxy'] = _body.get('enableProxy')
        return result

    @staticmethod
    def deserialize_response(response):
        try:
            return json.loads(response.text)
        except (ValueError, AttributeError):
            return None


def main():
    AzureRMFirewallPolicy()


if __name__ == '__main__':
    main()
