#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2024, Azure Magic Modules Generator
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Auto-generated by Azure Magic Modules — do not edit manually

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r'''
---
module: azure_rm_securitycentercontact
version_added: "0.1.0"
short_description: Manage Azure Security Center contact configuration.
description:
    - Create, update, or delete an Azure SecurityCenterContact.
    - This module was auto-generated by Azure Magic Modules.
options:
    resource_group:
        description:
            - Name of the resource group.
        type: str
        required: true
    name:
        description:
            - Name of the securitycentercontact.
        type: str
        required: true
    location:
        description:
            - Valid Azure location. Defaults to the location of the resource group.
        type: str
    email:
        description:
            - Email address for security notifications.
        type: str
        required: true
    phone:
        description:
            - Phone number for security notifications.
        type: str
    alert_notifications_state:
        description:
            - Whether to send alert notifications.
        type: str
        choices:
            - "On"
            - "Off"
    alerts_to_admins_state:
        description:
            - Whether to send alerts to subscription admins.
        type: str
        choices:
            - "On"
            - "Off"
    state:
        description:
            - Assert the state of the securitycentercontact.
            - Use C(present) to create or update and C(absent) to delete.
        type: str
        default: present
        choices:
            - present
            - absent
extends_documentation_fragment:
    - azure.azcollection.azure
    - azure.azcollection.azure_tags
author:
    - "Azure Magic Modules Generator (@azure-magic-modules)"
seealso:
    - description: Azure SecurityCenterContact REST API
      link: https://learn.microsoft.com/en-us/azure/defender-for-cloud/configure-email-notifications
'''

EXAMPLES = r'''
- name: Create SecurityCenterContact
  azure_rm_securitycentercontact:
    resource_group: myResourceGroup
    name: mySecurityCenterContact
    location: eastus
    email: "example_value"
    state: present

- name: Delete SecurityCenterContact
  azure_rm_securitycentercontact:
    resource_group: myResourceGroup
    name: mySecurityCenterContact
    state: absent
'''

RETURN = r'''
state:
    description: Current state of the securitycentercontact.
    returned: always
    type: dict
    contains:
        id:
            description: Resource ID.
            type: str
        name:
            description: Resource name.
            type: str
        location:
            description: Resource location.
            type: str
        tags:
            description: Resource tags.
            type: dict
        email:
            description: Email address for security notifications.
            type: str
        phone:
            description: Phone number for security notifications.
            type: str
        alert_notifications_state:
            description: Whether to send alert notifications.
            type: str
        alerts_to_admins_state:
            description: Whether to send alerts to subscription admins.
            type: str
'''

import json
from ansible_collections.azure.azcollection.plugins.module_utils.azure_rm_common import AzureRMModuleBase


class AzureRMSecurityCenterContact(AzureRMModuleBase):

    def __init__(self):
        self.module_arg_spec = dict(
            resource_group=dict(type='str', required=True, aliases=['resource_group_name']),
            name=dict(type='str', required=True),
            location=dict(type='str'),
            email=dict(
                type='str',
                required=True,
            ),
            phone=dict(
                type='str',
            ),
            alert_notifications_state=dict(
                type='str',
                choices=['On', 'Off'],
            ),
            alerts_to_admins_state=dict(
                type='str',
                choices=['On', 'Off'],
            ),
            state=dict(type='str', default='present', choices=['present', 'absent']),
        )

        self.resource_group = None
        self.name = None
        self.location = None
        self.email = None
        self.phone = None
        self.alert_notifications_state = None
        self.alerts_to_admins_state = None
        self.state = None
        self.tags = None

        self.results = dict(changed=False, state=dict())

        required_if = [
            ('state', 'present', ['resource_group', 'name']),
        ]

        super().__init__(
            derived_arg_spec=self.module_arg_spec,
            supports_check_mode=True,
            supports_tags=True,
            required_if=required_if,
        )

    def exec_module(self, **kwargs):
        for key in list(self.module_arg_spec.keys()) + ['tags']:
            setattr(self, key, kwargs[key])

        resource_group = self.resource_group
        name = self.name

        # Get existing resource
        response = self.get_resource()

        if self.state == 'present':
            if not self.location:
                rg = self.get_resource_group(resource_group)
                self.location = rg.location

            # Build the resource body from parameters
            body = self.build_body()

            if response:
                # Check if update needed
                update_tags, new_tags = self.update_tags(response.get('tags'))
                if update_tags:
                    body['tags'] = new_tags
                    self.results['changed'] = True

                if self.check_update(response, body):
                    self.results['changed'] = True

                if self.results['changed']:
                    if not self.check_mode:
                        response = self.create_or_update(resource_group, name, body)
                else:
                    response = response
            else:
                if self.tags:
                    body['tags'] = self.tags
                if not self.check_mode:
                    response = self.create_or_update(resource_group, name, body)
                self.results['changed'] = True

        elif self.state == 'absent':
            if response:
                if not self.check_mode:
                    self.delete_resource(resource_group, name)
                self.results['changed'] = True

        if response:
            self.results['state'] = self.format_response(response)

        return self.results

    def build_body(self):
        body = dict(
            location=self.location,
        )

        properties = body.setdefault('properties', {})
        if self.email is not None:
            properties['email'] = self.email
        if self.phone is not None:
            properties['phone'] = self.phone
        if self.alert_notifications_state is not None:
            _target = properties
            _target = _target.setdefault('alertNotifications', {})
            _target['state'] = self.alert_notifications_state
        if self.alerts_to_admins_state is not None:
            _target = properties
            _target = _target.setdefault('alertsToAdmins', {})
            _target['state'] = self.alerts_to_admins_state

        if self.tags:
            body['tags'] = self.tags

        return body

    def check_update(self, existing, desired):
        """Compare existing resource with desired state."""
        # Check email
        if self.email is not None:
            if existing.get('properties', {}).get('email') != self.email:
                return True
        # Check phone
        if self.phone is not None:
            if existing.get('properties', {}).get('phone') != self.phone:
                return True
        # Check alert_notifications_state
        if self.alert_notifications_state is not None:
            _existing = existing.get('properties', {})
            _existing = _existing.get('alertNotifications', {}) if isinstance(_existing, dict) else {}
            if _existing.get('state') != self.alert_notifications_state:
                return True
        # Check alerts_to_admins_state
        if self.alerts_to_admins_state is not None:
            _existing = existing.get('properties', {})
            _existing = _existing.get('alertsToAdmins', {}) if isinstance(_existing, dict) else {}
            if _existing.get('state') != self.alerts_to_admins_state:
                return True

        return False

    def get_resource(self):
        try:
            url = self.get_resource_url()
            response = self.mgmt_client.query(
                url, "GET",
                {'api-version': '2020-01-01-preview'},
                None, None, [200], 0, 0,
            )
            return self.deserialize_response(response)
        except Exception:
            return None

    def create_or_update(self, resource_group, name, body):
        url = self.get_resource_url()
        response = self.mgmt_client.query(
            url, "PUT",
            {'api-version': '2020-01-01-preview'},
            None, body, [200, 201], 0, 0,
        )
        return self.deserialize_response(response)

    def delete_resource(self, resource_group, name):
        url = self.get_resource_url()
        self.mgmt_client.query(
            url, "DELETE",
            {'api-version': '2020-01-01-preview'},
            None, None, [200, 202, 204], 0, 0,
        )

    def get_resource_url(self):
        return (
            '/subscriptions/{subscription_id}'
            '/resourceGroups/{resource_group}'
            '/providers/Microsoft.Security/securityContacts/{name}'
        ).format(
            subscription_id=self.subscription_id,
            resource_group=self.resource_group,
            name=self.name,
        )

    def format_response(self, response):
        result = dict(
            id=response.get('id'),
            name=response.get('name'),
            location=response.get('location'),
            tags=response.get('tags'),
        )
        result['email'] = response.get('properties', {}).get('email')
        result['phone'] = response.get('properties', {}).get('phone')
        _props = response.get('properties', {})
        _props = _props.get('alertNotifications', {}) if isinstance(_props, dict) else {}
        result['alert_notifications_state'] = _props.get('state')
        _props = response.get('properties', {})
        _props = _props.get('alertsToAdmins', {}) if isinstance(_props, dict) else {}
        result['alerts_to_admins_state'] = _props.get('state')
        return result

    @staticmethod
    def deserialize_response(response):
        try:
            return json.loads(response.text)
        except (ValueError, AttributeError):
            return None


def main():
    AzureRMSecurityCenterContact()


if __name__ == '__main__':
    main()
